{easy
	{balancingFactorBonus {cp 1.00} {mpStart 0.75} {mpFinish 0.75} {payback 0.50} {charge 0}}
}
{normal
	{balancingFactorBonus {cp 1.10} {mpStart 1.0}  {mpFinish 1.0}  {payback 1.00} {charge 0}}
}                                                                  
{hard                                                              
	{balancingFactorBonus {cp 1.20} {mpStart 2.0}  {mpFinish 2.0}  {payback 2.00} {charge 0}}
}                                                                  
{heroic                                                            
	{balancingFactorBonus {cp 1.30} {mpStart 3.0}  {mpFinish 3.0}  {payback 4.00} {charge 0}}
}