;-------------------------health_damage/
(define "health_damage_4x30"		; 4.6x30mm
	{healthDamage (* 0.120 %d)}
)

(define "health_damage_545x39"		; 5.45x39mm
	{healthDamage (* 0.1245 %d)}
)

(define "health_damage_556x45"		; 5.56x45mm
	{healthDamage (* 0.125 %d)}
)

(define "health_damage_762x39"		; 7.62x39mm
	{healthDamage (* 0.250 %d)}
)

(define "health_damage_762x51"		; 7.62x51mm
	{healthDamage (* 0.270 %d)}
)

(define "health_damage_762x54"		; 7.62x54mm
	{healthDamage (* 0.250 %d)}
)

(define "health_damage_792x57"		; 7.62x54mm
	{healthDamage (* 0.290 %d)}
)
(define "health_damage_762x67"		; 7.62x67mm
	{healthDamage (* 0.240 %d)}
)

(define "health_damage_9x18"		; 9x18mm
	{healthDamage (* 0.090 %d)}
)

(define "health_damage_9x19"		; 9x19mm
	{healthDamage (* 0.095 %d)}
)

(define "health_damage_9x39"		; 9x39mm	
	{healthDamage (* 0.210 %d)}
)

(define "health_damage_11x23"		; 11.43x23mm
	{healthDamage (* 0.190 %d)}
)

(define "health_damage_127x99"		; 12.7x99mm
	{healthDamage (* 0.400 %d)}
)

(define "health_damage_127x108"		; 12.7x108mm
	{healthDamage (* 0.500 %d)}
)

(define "health_damage_12gauge"		; 12-gauge
	{healthDamage (* 0.250 %d)}
)

(define "health_damage_9x64"		; 9.3x64mm
	{healthDamage (* 0.210 %d)}
)

(define "health_damage_127x55"		; 12.7x55mm
	{healthDamage (* 0.210 %d)}
)

(define "health_damage_762x67"		;
	{healthDamage (* 0.254 %d)}
)



;-------------------------------
