(define "projectileDamage_556x45_sp"
	{projectileDamage 4.5}
	{projectileDamageClip 4.5}
	{projectileDamageTable {25 4.5} {50 4.3} {75 3.7} {100 3} {150 2.5} {200 2} {250 1.7} {400 1.5} {800 0.5} }
)
(define "projectileDamage_556x45_fg"
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3} {50 2.7} {75 2.1} {100 2} {150 1.5} {200 1} {250 0.7} {400 0.5} {800 0.2} }
)
(define "projectileDamage_556x45_ap"
	{projectileDamage 5.5}
	{projectileDamageClip 5.5}
	{projectileDamageTable {25 5.5} {50 5} {75 4.3} {100 4.2} {150 3.5} {200 3} {250 2.5} {400 1.5} {800 0.5} {1200 0.2}}
)
(define "projectileDamage_545x39_sp"
	{projectileDamage 4.5}
	{projectileDamageClip 4.5}
	{projectileDamageTable {25 4.5} {50 4.1} {75 3.2} {100 2.4} {150 2.1} {200 1.8} {250 1.3} {400 1.1} {800 0.5} }
)
(define "projectileDamage_545x39_ap"
	{projectileDamage 5.5}
	{projectileDamageClip 5.5}
	{projectileDamageTable {25 5.5} {50 4.6} {75 3.6} {100 2.8} {150 2.4} {200 1.8} {250 1.3} {400 1.1} {800 0.5} }
)
(define "projectileDamage_762x39_sp"
	{projectileDamage 7.3}
	{projectileDamageClip 7.3}
	{projectileDamageTable {25 7.3} {50 6.3} {75 5.7} {100 5} {150 4.5} {200 4} {250 3.7} {400 2.5} {800 1.5} {1000 0.5}}
)
(define "projectileDamage_762x39_ap"
	{projectileDamage 8}
	{projectileDamageClip 8}
	{projectileDamageTable {25 8} {50 7.5} {75 7} {100 6.1} {150 5.5} {200 5} {250 4.5} {400 3.5} {800 2.5} {1500 0.2}}
)
(define "projectileDamage_762x51_sp"
	{projectileDamage 7.3}
	{projectileDamageClip 7.3}
	{projectileDamageTable {25 7.3} {50 6.7} {75 6.1} {100 5.4} {150 4.8} {200 4} {250 3.7} {400 2.5} {800 1.5} {1000 0.5}}
)
(define "projectileDamage_762x51_ap"
	{projectileDamage 8}
	{projectileDamageClip 8}
	{projectileDamageTable {25 8} {50 6.9} {75 6.6} {100 6.1} {150 5.5} {200 5} {250 4.5} {400 3.5} {800 2.5} {1500 0.2}}
)
(define "projectileDamage_762x51_fg"
	{projectileDamage 4.5}
	{projectileDamageClip 4.5}
	{projectileDamageTable {25 4.5} {50 4.1} {75 3.2} {100 2.4} {150 2.1} {200 1.8} {250 1.3} {400 1.1} {800 0.5} }
)
(define "projectileDamage_762x54_sp"
	{projectileDamage 8}
	{projectileDamageClip 8}
	{projectileDamageTable {25 8} {50 7.5} {75 7.1} {100 5.4} {150 4.8} {200 4} {250 3.7} {400 2.5} {800 1.5} {1000 0.5}}
)
(define "projectileDamage_762x54_ap"
	{projectileDamage 9}
	{projectileDamageClip 9}
	{projectileDamageTable {25 9} {50 8.5} {75 7.2} {100 6.4} {150 5.8} {200 5} {250 4.5} {400 3.5} {800 2.5} {1500 0.2}}
)
(define "projectileDamage_792x57_sp"
	{projectileDamage 7.3}
	{projectileDamageClip 7.3}
	{projectileDamageTable {25 7.3} {50 6.7} {75 6.1} {100 5.4} {150 4.8} {200 4} {250 3.7} {400 2.5} {800 1.5} {1000 0.5}}
)
(define "projectileDamage_792x57_ap"
	{projectileDamage 8}
	{projectileDamageClip 8}
	{projectileDamageTable {25 8} {50 6.9} {75 6.6} {100 6.1} {150 5.5} {200 5} {250 4.5} {400 3.5} {800 2.5} {1500 0.2}}
)
(define "projectileDamage_792x57_fg"
	{projectileDamage 4.5}
	{projectileDamageClip 4.5}
	{projectileDamageTable {25 4.5} {50 4.1} {75 3.2} {100 2.4} {150 2.1} {200 1.8} {250 1.3} {400 1.1} {800 0.5} }
)
(define "projectileDamage_127x99_sp"
	{projectileDamage 35}
	{projectileDamageClip 35}
	{projectileDamageTable {25 35} {50 32} {75 30} {100 25} {150 20} {200 17} {250 15} {400 12} {800 8} {1000 5}}
)
(define "projectileDamage_127x99_ap"
	{projectileDamage 45}
	{projectileDamageClip 45}
	{projectileDamageTable {25 45} {50 43} {75 37} {100 32} {150 27} {200 22} {250 17} {400 14} {800 12} {1000 7}}
)
(define "projectileDamage_127x55_short_sp"
	{projectileDamage 27}
	{projectileDamageClip 27}
	{projectileDamageTable {15 27} {25 25} {50 22} {75 12} {90 9} {110 8} {140 6} {170 3} {250 2} {400 0.5}}
)
(define "projectileDamage_127x55_short_ap"
	{projectileDamage 34}
	{projectileDamageClip 34}
	{projectileDamageTable {15 34} {25 28} {50 25} {75 17} {90 12} {110 9} {140 7} {170 3} {250 2} {400 0.5}}
)




;------9x19------------------------------------------------------------------------

(define "short_barrel_9x19_sp_pierce"
	("accuracy_pistol_short_sp_9x19")
	("speed" s(350))
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3} {50 1} {100 0.3} {250 0.1}}
)
(define "short_barrel_9x19_ap_pierce"
	("accuracy_pistol_short_ap_9x19")
	("speed" s(520))
	{projectileDamage 4.2}
	{projectileDamageClip 4.2}
	{projectileDamageTable {25 4.2} {50 2} {120 0.3} {250 0.1}}
)
(define "short_barrel_sil_9x19_sp_pierce"
	("accuracy_pistol_med_sp_9x19")
	("speed" s(310))
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3} {50 1} {100 0.3} {250 0.1}}
)
(define "short_barrel_sil_9x19_ap_pierce"
	("accuracy_pistol_med_ap_9x19")
	("speed" s(375))
	{projectileDamage 4.2}
	{projectileDamageClip 4.2}
	{projectileDamageTable {25 4.2} {50 2} {120 0.3} {250 0.1}}
)

(define "med_barrel_9x19_sp_pierce"
	("accuracy_pistol_med_sp_9x19")
	("speed" s(350))
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3} {50 1} {100 0.3} {250 0.1}}
)
(define "med_barrel_9x19_ap_pierce"
	("accuracy_pistol_med_ap_9x19")
	("speed" s(410))
	{projectileDamage 4.2}
	{projectileDamageClip 4.2}
	{projectileDamageTable {25 4.2} {50 2} {120 0.3} {250 0.1}}
)

(define "med_barrel_sil_9x19_sp_pierce"
	("accuracy_pistol_med_sp_9x19")
	("speed" s(380))
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3.5} {50 1.4} {100 0.3} {250 0.1}}
)
(define "med_barrel_sil_9x19_ap_pierce"
	("accuracy_pistol_med_ap_9x19")
	("speed" s(450))
	{projectileDamage 4.2}
	{projectileDamageClip 4.2}
	{projectileDamageTable {25 4.2} {50 2.8} {120 0.3} {250 0.1}}
)

(define "long_barrel_9x19_sp_pierce"
	("accuracy_pistol_long_sp_9x19")
	("speed" s(350))
	{projectileDamage 3}
	{projectileDamageClip 3}
	{projectileDamageTable {25 3} {50 1} {100 0.3} {250 0.1}}
)
(define "long_barrel_9x19_ap_pierce"
	("accuracy_pistol_long_ap_9x19")
	("speed" s(410))
	{projectileDamage 4.2}
	{projectileDamageClip 4.2}
	{projectileDamageTable {25 4.2} {50 2} {120 0.3} {250 0.1}}
)
;------11x23------------------------------------------------------------------------
(define "short_barrel_11x23_sp_pierce"  ; .45 ACP
	("accuracy_pistol_short_sp_11x23")
	("speed" s(260))
	{projectileDamage 2}
	{projectileDamageClip 2}
	{projectileDamageTable {25 2} {50 1} {70 0.1} {140 0}}
)
(define "short_barrel_11x23_ap_pierce"
	("accuracy_pistol_short_ap_11x23")
	("speed" s(310))
	{projectileDamage 2.7}
	{projectileDamageClip 2.7}
	{projectileDamageTable {25 2.7} {50 1.5} {80 0.1} {140 0}}
)

(define "med_barrel_11x23_sp_pierce"  ; 
	("accuracy_pistol_med_sp_11x23")
	("speed" s(312))
	{projectileDamage 2}
	{projectileDamageClip 2}
	{projectileDamageTable {25 2} {50 1} {70 0.1} {140 0}}
)
(define "med_barrel_11x23_ap_pierce"
	("accuracy_pistol_med_ap_11x23")
	("speed" s(375))
	{projectileDamage 2.7}
	{projectileDamageClip 2.7}
	{projectileDamageTable {25 2.7} {50 1.5} {80 0.1} {140 0}}
)

(define "long_barrel_11x23_sp_pierce"  ; 
	("accuracy_pistol_long_sp_11x23")
	("speed" s(352))
	{projectileDamage 2}
	{projectileDamageClip 2}
	{projectileDamageTable {25 2} {50 1} {70 0.1} {140 0}}
)
(define "long_barrel_11x23_ap_pierce"
	("accuracy_pistol_long_ap_11x23")
	("speed" s(435))
	{projectileDamage 2.7}
	{projectileDamageClip 2.7}
	{projectileDamageTable {25 2.7} {50 1.5} {80 0.1} {140 0}}
)
;------127x33------------------------------------------------------------------------

(define "med_barrel_127x33_sp_pierce"  ; 
	("accuracy_pistol_med_sp_127x33")
	{projectileDamage 15}
	{projectileDamageClip 15}
	{projectileDamageTable {10 15} {25 12} {60 8} {200 6}}
	("speed" s(442))
)
(define "med_barrel_127x33_ap_pierce"
	("accuracy_pistol_med_ap_127x33")
	("speed" s(383))
	{projectileDamage 25}
	{projectileDamageClip 25}
	{projectileDamageTable {10 25} {25 18} {60 12} {200 6}}
)

(define "long_barrel_127x33_sp_pierce"  ; 
	("accuracy_pistol_long_sp_127x33")
	{projectileDamage 15}
	{projectileDamageClip 15}
	{projectileDamageTable {10 15} {25 12} {60 8} {200 6}}
	("speed" s(475))
)
(define "long_barrel_127x33_ap_pierce"
	("accuracy_pistol_long_ap_127x33")
	("speed" s(435))
	{projectileDamage 25}
	{projectileDamageClip 25}
	{projectileDamageTable {10 25} {25 18} {60 12} {200 6}}
)
;		("projectileDamage_range_2km" damping(1) damage(37))
(define "projectileDamage_range_2km" 
	{projectileDamageTable
		{50  			(* (* 1 %damping) %damage)} 
		{100 			(* (* 0.97 %damping) %damage)} 
		{150 			(* (* 0.95 %damping) %damage)}
		{200 			(* (* 0.90 %damping) %damage)} 
		{300 			(* (* 0.85 %damping) %damage)}
		{400 			(* (* 0.8 %damping) %damage)} 
		{500 			(* (* 0.75 %damping) %damage)}
		{600 			(* (* 0.7 %damping) %damage)}
		{700 			(* (* 0.65 %damping) %damage)}
		{800 			(* (* 0.6 %damping) %damage)}
		{900 			(* (* 0.55 %damping) %damage)}
		{1000 			(* (* 0.5 %damping) %damage)}
		{1100 			(* (* 0.45 %damping) %damage)}
		{1200 			(* (* 0.4 %damping) %damage)}
		{1300 			(* (* 0.35 %damping) %damage)}
		{1400 			(* (* 0.3 %damping) %damage)}
		{1500 			(* (* 0.25 %damping) %damage)}
		{1600 			(* (* 0.2 %damping) %damage)}
		{1700 			(* (* 0.15 %damping) %damage)}
		{1800 			(* (* 0.1 %damping) %damage)}
		{1900 			(* (* 0.05 %damping) %damage)}
		{2000 			(* (* 0.01 %damping) %damage)}
	}
)

(define "projectileDamage_range_500m" 
	{projectileDamageTable
		{25  			(* (* 1 %damping) %damage)} 
		{50 			(* (* 0.98 %damping) %damage)} 
		{75 			(* (* 0.96 %damping) %damage)}
		{100 			(* (* 0.93 %damping) %damage)} 
		{125 			(* (* 0.85 %damping) %damage)}
		{150 			(* (* 0.8 %damping) %damage)} 
		{175 			(* (* 0.75 %damping) %damage)}
		{200 			(* (* 0.7 %damping) %damage)}
		{225 			(* (* 0.65 %damping) %damage)}
		{250 			(* (* 0.6 %damping) %damage)}
		{275 			(* (* 0.5 %damping) %damage)}
		{300 			(* (* 0.4 %damping) %damage)}
		{325 			(* (* 0.38 %damping) %damage)}
		{350 			(* (* 0.3 %damping) %damage)}
		{375 			(* (* 0.25 %damping) %damage)}
		{400 			(* (* 0.2 %damping) %damage)}
		{425 			(* (* 0.15 %damping) %damage)}
		{450 			(* (* 0.12 %damping) %damage)}
		{475 			(* (* 0.1 %damping) %damage)}
		{500 			(* (* 0.06 %damping) %damage)}
		{700 			(* (* 0.01 %damping) %damage)}
		{950 			(* (* 0.001 %damping) %damage)}
	}
)
