;-------------------sway
(define "sway_high"
	{swayparams
		{bounds -0.4 0.25 -0.4 0.4}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.4}						; sway speed coef
	}
)
(define "sway_very_high"
	{swayparams
		{bounds -0.7 0.35 -0.5 0.5}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.2}						; sway speed coef
	}
)
(define "sway_medium_long"
	{swayparams
		{bounds -0.4 0.25 -0.45 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.35}						; sway speed coef
	}
)
(define "sway_medium"
	{swayparams
		{bounds -0.3 0.2 -0.4 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.4}						; sway speed coef
	}
)
(define "sway_low"
	{swayparams
		{bounds -0.17 0.1 -0.2 0.17}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.2}						; sway speed coef
	}
)
(define "sway_low_2"
	{swayparams
		{bounds -0.15 0.08 -0.18 0.15}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.14}						; sway speed coef
	}
)

(define "sway_pistol"
	{swayparams
		{bounds -0.25 0.2 -0.35 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.1}						; sway speed coef
	}
)

(define "sway_smg"
	{swayparams
		{bounds -0.25 0.2 -0.35 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.1}						; sway speed coef
	}
)

(define "sway_mg"
	{swayparams
		{bounds -0.3 0.2 -0.4 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.3}						; sway speed coef
	}
)

(define "sway_rifle"
	{swayparams
		{bounds -0.3 0.2 -0.4 0.3}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.2}						; sway speed coef
	}
)

(define "sway_sniper"
	{swayparams
		{bounds -0.35 0.25 -0.45 0.35}		; x -> negativeYaw, y -> positiveYaw, z -> negativePitch, w -> positive Pitch (in degree)
		{speed 0.2}						; sway speed coef
	}
)

