	{Volume "glass_front_wind_full_damage"
		{Tags  "hold"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_front_wind_full_broken"
		{Tags  "hold"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_damage"
		{Tags  "hold" "glass_back_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_broken"
		{Tags  "hold" "glass_back_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_damage"
		{Tags  "glass_l1_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_damage"
		{Tags  "glass_r1_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_damage"
		{Tags  "glass_l2_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_damage"
		{Tags  "glass_r2_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_damage"
		{Tags  "glass_l3_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_damage"
		{Tags  "glass_r3_damage"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_broken"
		{tags "holded_sharp"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	
	
	
	
	
	
	
	
	{Volume "glass_l1_sharp_00"
		{tags "shard" "glass_l1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_01"
		{tags "shard" "glass_l1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_02"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_03"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_04"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_05"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_06"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_07"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_08"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_09"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_10"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_11"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_12"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_13"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_14"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_15"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_16"
		{thickness hollow 1}
		{tags "shard" "glass_l1_broken"}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_17"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_18"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_19"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_20"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_21"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_22"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_23"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_24"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l1_sharp_25"
		{tags "shard" "glass_l1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	
	
	
	
	
	
	
	{Volume "glass_r1_sharp_00"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_01"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_02"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_03"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_04"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_05"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_06"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_07"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_08"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_09"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_10"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_11"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_12"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_13"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_14"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_15"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_16"
		{tags "shard" "glass_r1_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_17"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_18"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_19"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_20"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_21"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_22"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_23"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_24"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r1_sharp_25"
		{tags "shard" "glass_r1_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}


	{Volume "glass_l2_sharp_00"
		{tags "shard" "glass_l2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_01"
		{tags "shard" "glass_l2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_02"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_03"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_04"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_05"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_06"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_07"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_08"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_09"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_10"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_11"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_12"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_13"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_14"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_15"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_16"
		{thickness hollow 1}
		{tags "shard" "glass_l2_broken"}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_17"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_18"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_19"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_20"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_21"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_22"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_23"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_24"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l2_sharp_25"
		{tags "shard" "glass_l2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	
	
	
	{Volume "glass_r2_sharp_00"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_01"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_02"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_03"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_04"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_05"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_06"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_07"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_08"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_09"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_10"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_11"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_12"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_13"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_14"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_15"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_16"
		{tags "shard" "glass_r2_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_17"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_18"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_19"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_20"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_21"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_22"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_23"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_24"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r2_sharp_25"
		{tags "shard" "glass_r2_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	
	
	
	
	{Volume "glass_l3_sharp_00"
		{tags "shard" "glass_l3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_01"
		{tags "shard" "glass_l3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_02"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_03"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_04"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_05"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_06"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_07"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_08"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_09"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_10"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_11"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_12"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_13"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_14"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_15"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_16"
		{thickness hollow 1}
		{tags "shard" "glass_l3_broken"}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_17"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_18"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_19"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_20"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_21"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_22"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_23"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_24"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_l3_sharp_25"
		{tags "shard" "glass_l3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	
	
	{Volume "glass_r3_sharp_00"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_01"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_02"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_03"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_04"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_05"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_06"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_07"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_08"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_09"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_10"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_11"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_12"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_13"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_14"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_15"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_16"
		{tags "shard" "glass_r3_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_17"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_18"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_19"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_20"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_21"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_22"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_23"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_24"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_r3_sharp_25"
		{tags "shard" "glass_r3_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_00"
		{tags "shard" "glass_back_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_01"
		{tags "shard" "glass_back_broken"}
		{able {window} {blockcamera 1}}
		{thickness hollow 1}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_02"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_03"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_04"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_05"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_06"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_07"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_08"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_09"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_10"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_11"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_12"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_13"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_14"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_15"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_16"
		{thickness hollow 1}
		{tags "shard" "glass_back_broken"}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_17"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_18"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_19"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_20"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_21"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_22"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_23"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_24"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	{Volume "glass_back_sharp_25"
		{tags "shard" "glass_back_broken"}
		{thickness hollow 1}
		{able {window} {blockcamera 1}}
		{material "wound_glass_small"}		
	}
	
