{bone "upgrade_left_laser5mw"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00185463	-0.343873	0.000456691
	}
	{bone "fx_laser_set_l_laser5mw"
		{Matrix34
			0.000316505	1	0
			-1	0.000314858	-0.000311369
			-0.00031138	0	1
			-0.0807567	1.00156	0.22223
		}
	}
	{bone "laser5mw_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	1	0
			0	0	1
			-1.21813	-1.52855	0.371755
		}
		{bone "laser5mw_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.17809	1.98721	-0.0762078
			}
			{VolumeView "laser5mw_l_ui.ply"}
			{bone "laser5mw_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00161982	0.0878763	-0.172851
				}
				{VolumeView "laser5mw_l_light_on_ui.ply"}
			}
			{bone "laser5mw_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00161815	-0.12981	-0.172851
				}
				{VolumeView "laser5mw_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_l_laser5mw"
		{Matrix34
			0.000316505	1	0
			-1	0.000314858	-0.000311369
			-0.00031138	0	1
			0.0233158	1.02274	0.372442
		}
	}
	{bone "laser5mw_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	-0.000678396
			1	0	0
			0	-0.000678405	-1
			0.00064835	0.286786	0.120229
		}
		{visibility 0}
		{LODView
			{VolumeView "laser5mw_l.ply"}
			{VolumeView "laser5mw_l_lod1.ply"}
			{VolumeView "laser5mw_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_zenitco"
	{parameters "Voxels=0;"}
	{Position -0.00892031	-0.249801	-0.0226002}
	{bone "fx_laser_set_l_zenitco"
		{Matrix34
			-0.000180081	1	0
			0.00018032	0	-1
			-1	-0.000180099	-0.00018032
			-0.241006	0.910451	0.238825
		}
	}
	{bone "zenitco_l_ui_bone"
		{parameters "Voxels=0;"}
		{Position -1.07091	-1.62892	0.262536}
		{bone "zenitco_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				0.99384	1.67641	-0.064289
			}
			{VolumeView "zenitco_l_ui.ply"}
			{bone "zenitco_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00136644	0.0741327	-0.145817
				}
				{VolumeView "zenitco_l_light_on_ui.ply"}
			}
			{bone "zenitco_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00136507	-0.109508	-0.145817
				}
				{VolumeView "zenitco_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_l_zenitco"
		{Matrix34
			-0.000180081	1	0
			0.00018032	0	-1
			-1	-0.000180099	-0.00018032
			0.00203425	0.896186	0.591979
		}
	}
	{bone "zenitco_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	0	-1
			0	1	0
			1	0	0
			-0.0269067	0.20205	0.46454
		}
		{visibility 0}
		{LODView
			{VolumeView "zenitco_l.ply"}
			{VolumeView "zenitco_l_lod1.ply"}
			{VolumeView "zenitco_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_laser1mw"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00618732	-0.231447	-0.00254381
	}
	{bone "fx_laser_set_l_laser1mw"
		{Matrix34
			0.000316505	1	0
			-1	0.000314858	-0.000311369
			-0.00031138	0	1
			0.00246751	0.571835	0.769714
		}
	}
	{bone "laser1mw_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	1	0
			0	0	1
			-1.25954	-1.41146	0.431901
		}
		{bone "laser1mw_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.17809	1.98721	-0.0762078
			}
			{VolumeView "laser1mw_l_ui.ply"}
			{bone "laser1mw_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.0016197	0.0878768	-0.172851
				}
				{VolumeView "laser1mw_l_light_on_ui.ply"}
			}
			{bone "laser1mw_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00161803	-0.12981	-0.172851
				}
				{VolumeView "laser1mw_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_l_laser1mw"
		{Matrix34
			0.000316505	1	0
			-1	0.000314858	-0.000311369
			-0.00031138	0	1
			0.00205988	1.36021	0.392719
		}
	}
	{bone "laser_1mw_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			1	0	0
			0	0	-1
			0.00417382	0.062006	0.12489
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_1mw_l.ply"}
			{VolumeView "laser_1mw_l_lod1.ply"}
			{VolumeView "laser_1mw_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_lasercylinder1"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00268102	0.157461	-0.0064159
	}
	{bone "fx_laser_set_l_lasercylinder1"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.0100235	1.11765	0.304968
		}
	}
	{bone "lasercylinder1_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	-1	0
			0	0	1
			-1.59637	1.97026	0.353394
		}
		{bone "lasercylinder1_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.47807	1.98721	-0.0762092
			}
			{VolumeView "lasercylinder1_l_ui.ply"}
			{bone "lasercylinder1_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.0016225	0.00722075	-0.00276136
				}
				{VolumeView "lasercylinder1_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser_rail_l_lasercylinder1"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0292079	-0.053637	0.0460587
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_l_lasercylinder1.ply"}
			{VolumeView "laser_rail_l_lasercylinder1_lod1.ply"}
			{VolumeView "laser_rail_l_lasercylinder1_lod2.ply"}
		}
		{bone "lasercylinder1_l"
			{parameters "CommonMesh;"}
			{Position 0.250167	-0.261446	-0.0368719}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder1_l.ply"}
				{VolumeView "lasercylinder1_l_lod1.ply"}
				{VolumeView "lasercylinder1_l_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_left_tactical_laser"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00461516	0.211131	0.000724792
	}
	{bone "fx_laser_set_l_tactical_laser"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.159248	0.113134	0.32853
		}
	}
	{bone "tactical_laser_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	1	0
			0	0	1
			-1.53178	-2.27558	0.552352
		}
		{bone "tactical_laser_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.47807	1.98721	-0.0762093
			}
			{VolumeView "tactical_laser_l_ui.ply"}
			{bone "tactical_laser_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162256	0.00722075	-0.00276142
				}
				{VolumeView "tactical_laser_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "tactical_laser_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			1	0	0
			0	0	-1
			-0.00161111	-0.286011	0.127223
		}
		{visibility 0}
		{LODView
			{VolumeView "tactical_laser_l.ply"}
			{VolumeView "tactical_laser_l_lod1.ply"}
			{VolumeView "tactical_laser_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_lasercylinder3"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		0.00109589	0.139271	-0.00611967
	}
	{bone "fx_laser_set_l_lasercylinder3"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00365877	0.72309	0.310561
		}
	}
	{bone "lasercylinder3_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	-1	0
			0	0	1
			-1.59637	1.97026	0.353394
		}
		{bone "lasercylinder3_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.47807	1.98721	-0.0762092
			}
			{VolumeView "lasercylinder3_l_ui.ply"}
			{bone "lasercylinder3_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.0016225	0.00722075	-0.00276142
				}
				{VolumeView "lasercylinder3_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser_rail_l_lasercylinder3"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0292079	-0.053637	0.0482932
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_l_lasercylinder3.ply"}
			{VolumeView "laser_rail_l_lasercylinder3_lod1.ply"}
			{VolumeView "laser_rail_l_lasercylinder3_lod2.ply"}
		}
		{bone "lasercylinder3_l"
			{parameters "CommonMesh;"}
			{Position 0.241947	-0.261764	-0.0280443}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder3_l.ply"}
				{VolumeView "lasercylinder3_l_lod1.ply"}
				{VolumeView "lasercylinder3_l_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_left_liner"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00385836	0.0217261	-0.00377792
	}
	{bone "fx_laser_set_l_liner"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.000596941	1.31678	0.352609
		}
	}
	{bone "liner_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			0.999943	-0.00634422	0.00855165
			-0.00639386	-0.999963	0.00579048
			-0.00851458	0.00584485	0.999947
			-1.35329	2.05296	0.217554
		}
		{bone "liner_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.40987	1.89551	-0.0726926
			}
			{VolumeView "liner_l_ui.ply"}
			{bone "liner_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00154769	0.00688839	-0.00263399
				}
				{VolumeView "liner_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "liner_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	0	-1
			0	1	0
			1	0	0
			-0.00763488	0.258032	-0.0219334
		}
		{visibility 0}
		{LODView
			{VolumeView "liner_l.ply"}
			{VolumeView "liner_l_lod1.ply"}
			{VolumeView "liner_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_peq15"
	{parameters "Voxels=0;"}
	{Position -0.0321905	0.0465231	-0.00151569}
	{bone "fx_light_set_l_peq15"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.373151	1.24864	0.264878
		}
	}
	{bone "fx_laser_set_l_peq15"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.328325	1.00628	0.237175
		}
	}
	{bone "caps_light_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	0.984808	0.173648
			0	0.173648	-0.984808
			-1	0	0
			-0.319889	0.886098	0.316915
		}
		{VolumeView "caps_light_l.ply"}
	}
	{bone "caps_laser_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	0	1
			-1	0	0
			0	-1	0
			0.296953	0.761898	0.316286
		}
		{VolumeView "caps_laser_l.ply"}
	}
	{bone "peq15_l_ui_bone"
		{parameters "Voxels=0;"}
		{Position -1.32405	-1.38751	0.344844}
		{bone "peq15_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.20749	1.87818	-0.0720267
			}
			{VolumeView "peq15_l_ui.ply"}
			{bone "peq15_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00153196	0.0067749	-0.00389129
				}
				{VolumeView "peq15_l_light_on_ui.ply"}
			}
			{bone "peq15_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00152028	0.00651836	-0.00389135
				}
				{VolumeView "peq15_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "peq15_l"
		{parameters "CommonMesh;"}
		{Position 8.61883e-05	-0.0283933	-0.0280395}
		{visibility 0}
		{LODView
			{VolumeView "peq15_l.ply"}
			{VolumeView "peq15_l_lod1.ply"}
			{VolumeView "peq15_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_lasercylinder4"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		0.000733942	0.134083	-0.0070712
	}
	{bone "fx_laser_set_l_lasercylinder4"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00365877	0.828101	0.310561
		}
	}
	{bone "lasercylinder4_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	-1	0
			0	0	1
			-1.59637	1.97026	0.353394
		}
		{bone "lasercylinder4_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.47807	1.98721	-0.0762092
			}
			{VolumeView "lasercylinder4_l_ui.ply"}
			{bone "lasercylinder4_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.0016225	0.00722075	-0.00276136
				}
				{VolumeView "lasercylinder4_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser_rail_l_lasercylinder4"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0299296	-0.0536375	0.0495801
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_l_lasercylinder4.ply"}
			{VolumeView "laser_rail_l_lasercylinder4_lod1.ply"}
			{VolumeView "laser_rail_l_lasercylinder4_lod2.ply"}
		}
		{bone "lasercylinder4_l"
			{parameters "CommonMesh;"}
			{Position 0.270352	-0.258995	-0.0325857}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder4_l.ply"}
				{VolumeView "lasercylinder4_l_lod1.ply"}
				{VolumeView "lasercylinder4_l_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_left_peq10"
	{parameters "Voxels=0;"}
	{Position 0.00552365	-0.193663	-0.0284675}
	{bone "fx_laser_set_l_peq10"
		{Matrix34
			-0.000180088	1	0
			0.00018032	0	-1
			-1	-0.000180103	-0.00018032
			-0.1905	0.98789	0.394042
		}
	}
	{bone "an_peq10_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	0	1
			0	1	0
			-1	0	0
			-0.0051879	-0.218757	0.109321
		}
		{visibility 0}
		{LODView
			{VolumeView "an_peq10_l.ply"}
			{VolumeView "an_peq10_l_lod1.ply"}
			{VolumeView "an_peq10_l_lod2.ply"}
		}
		{bone "caps_front_l"
			{parameters "CommonMesh;"}
			{Matrix34
				-0.087157	0.996195	-5.83522e-05
				0.996195	0.0871569	-5.77847e-05
				-5.2479e-05	-6.31664e-05	-1
				0.292672	1.00185	-0.00452268
			}
			{VolumeView "caps_front_l.ply"}
		}
	}
	{bone "peq10_l_ui_bone"
		{parameters "Voxels=0;"}
		{Position -1.19805	-1.95429	0.503607}
		{bone "peq10_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.19236	2.01127	-0.0771306
			}
			{VolumeView "peq10_l_ui.ply"}
			{bone "peq10_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0.00571888	0.999984	0
					1	0	0
					0.00164127	-0.00215578	-0.0123369
				}
				{VolumeView "peq10_l_light_on_ui.ply"}
			}
			{bone "peq10_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0.00571888	0.999984	0
					1	0	0
					0.00162923	-0.0123706	-0.0123392
				}
				{VolumeView "peq10_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_l_peq10"
		{Matrix34
			-0.000180088	1	0
			0.00018032	0	-1
			-1	-0.000180103	-0.00018032
			0.204111	0.98789	0.41678
		}
	}
}
{bone "upgrade_left_flashlight_sf"
	{parameters "Voxels=0;"}
	{Position 0.000446916	0.245163	-0.00651914}
	{bone "fx_light_set_l_flashlight_sf"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00437376	1.17743	0.529101
		}
	}
	{bone "flashlight_sf_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	1	0
			0	0	1
			-1.45763	-1.56612	0.611862
		}
		{bone "flashlight_sf_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.43113	1.9241	-0.0737888
			}
			{VolumeView "flashlight_sf_l_ui.ply"}
			{bone "flashlight_sf_l_light_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00157106	0.00699139	-0.00267369
				}
				{VolumeView "flashlight_sf_l_light_on_ui.ply"}
			}
		}
	}
	{bone "flashlight_sf_l"
		{parameters "CommonMesh;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	-1
			0.00048539	0	-7.96914e-05
		}
		{visibility 0}
		{LODView
			{VolumeView "flashlight_sf_l.ply"}
			{VolumeView "flashlight_sf_l_lod1.ply"}
			{VolumeView "flashlight_sf_l_lod2.ply"}
		}
	}
}
{bone "upgrade_left_tactical_laser2"
	{parameters "Voxels=0;"}
	{Matrix34
		1	0	0
		0	1	0
		0	0	1
		-0.00340492	0.208129	-0.00630337
	}
	{bone "fx_laser_set_l_tactical_laser2"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.298229	0.751893	0.133945
		}
	}
	{bone "tactical_laser2_l_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			1	0	0
			0	1	0
			0	0	1
			-1.34432	-2.04248	0.0766612
		}
		{bone "tactical_laser2_l_ui"
			{parameters "CommonMesh;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.47807	1.98721	-0.0762092
			}
			{VolumeView "tactical_laser2_l_ui.ply"}
			{bone "tactical_laser2_l_laser_on_ui"
				{parameters "CommonMesh;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162256	0.00722075	-0.00276139
				}
				{VolumeView "tactical_laser2_l_laser_on_ui.ply"}
			}
		}
	}
	{bone "tactical_laser2_l"
		{parameters "CommonMesh;"}
		{Matrix34
			0	1	0
			-1	0	0
			0	0	1
			0.0191546	-0.736454	0.102905
		}
		{visibility 0}
		{LODView
			{VolumeView "tactical_laser2_l.ply"}
			{VolumeView "tactical_laser2_l_lod1.ply"}
			{VolumeView "tactical_laser2_l_lod2.ply"}
		}
	}
}
