		{sequence "caps_laser_l"}
		{sequence "caps_light_l"}
		{sequence "caps_front_l"}
		{sequence "upgrade"}
		{sequence "view_upgrade"}
		{sequence "peq15_l_ui"}
		{sequence "peq10_l_ui"}
		{sequence "flashlight_sf_l_ui"}
		{sequence "laser1mw_l_ui"}
		{sequence "laser5mw_l_ui"}
		{sequence "tactical_laser_l_ui"}
		{sequence "zenitco_l_ui"}
		{sequence "liner_l_ui"}
		{sequence "tactical_laser2_l_ui"}
		{sequence "lasercylinder1_l_ui"}
		{sequence "lasercylinder3_l_ui"}
		{sequence "lasercylinder4_l_ui"}

