						{bone "upgrade_left_flashlight_sf"
							{parameters "Voxels=0;"}
							{Position 0	0.264104	0}
							{bone "fx_light_set_l_flashlight_sf"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									0.00456333	1.22846	0.55203
								}
							}
							{bone "flashlight_sf_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	1	0
									0	0	1
									-1.5208	-1.63399	0.638378
								}
								{bone "flashlight_sf_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.49315	2.00748	-0.0769866
									}
									{VolumeView "flashlight_sf_l_ui.ply"}
									{bone "flashlight_sf_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00163913	0.00729465	-0.00278962
										}
										{VolumeView "flashlight_sf_l_light_on_ui.ply"}
									}
								}
							}
							{bone "flashlight_sf_l"
								{parameters "CommonMesh;"}
								{Matrix34
									-1	0	0
									0	1	0
									0	0	-1
									0.000506401	0	-8.31783e-05
								}
								{visibility 0}
								{LODView
									{VolumeView "flashlight_sf_l.ply"}
									{VolumeView "flashlight_sf_l_lod1.ply"}
									{VolumeView "flashlight_sf_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_peq15"
							{parameters "Voxels=0;"}
							{Position -0.0340517	0.0568578	0.00521988}
							{bone "fx_light_set_l_peq15"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.389321	1.30276	0.276357
								}
							}
							{bone "fx_laser_set_l_peq15"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									0.342554	1.04989	0.247454
								}
							}
							{bone "caps_light_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	0.984808	0.173648
									0	0.173648	-0.984808
									-1	0	0
									-0.333751	0.924498	0.330649
								}
								{VolumeView "caps_light_l.ply"}
							}
							{bone "caps_laser_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	0	1
									-1	0	0
									0	-1	0
									0.309822	0.794915	0.329992
								}
								{VolumeView "caps_laser_l.ply"}
							}
							{bone "peq15_l_ui_bone"
								{parameters "Voxels=0;"}
								{Position -1.38142	-1.44764	0.359788}
								{bone "peq15_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.25982	1.95957	-0.075148
									}
									{VolumeView "peq15_l_ui.ply"}
									{bone "peq15_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00159836	0.00706863	-0.00406003
										}
										{VolumeView "peq15_l_light_on_ui.ply"}
									}
									{bone "peq15_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.0015862	0.00680065	-0.00406003
										}
										{VolumeView "peq15_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "peq15_l"
								{parameters "CommonMesh;"}
								{Position 8.98838e-05	-0.0296242	-0.0292546}
								{visibility 0}
								{LODView
									{VolumeView "peq15_l.ply"}
									{VolumeView "peq15_l_lod1.ply"}
									{VolumeView "peq15_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_laser1mw"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.00692117	-0.233158	0.00414735
							}
							{bone "fx_laser_set_l_laser1mw"
								{Matrix34
									0.000316155	1	0
									-1	0.000315203	-0.000311375
									-0.000311374	0	1
									0.00257421	0.596615	0.803071
								}
							}
							{bone "laser1mw_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	1	0
									0	0	1
									-1.31413	-1.47263	0.450618
								}
								{bone "laser1mw_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.22915	2.07333	-0.0795105
									}
									{VolumeView "laser1mw_l_ui.ply"}
									{bone "laser1mw_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169003	0.0916846	-0.180342
										}
										{VolumeView "laser1mw_l_light_on_ui.ply"}
									}
									{bone "laser1mw_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.0016883	-0.135436	-0.180342
										}
										{VolumeView "laser1mw_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "fx_light_set_l_laser1mw"
								{Matrix34
									0.000316155	1	0
									-1	0.000315203	-0.000311375
									-0.000311374	0	1
									0.00214863	1.41916	0.409738
								}
							}
							{bone "laser_1mw_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									1	0	0
									0	0	-1
									0.00435472	0.0646927	0.130302
								}
								{visibility 0}
								{LODView
									{VolumeView "laser_1mw_l.ply"}
									{VolumeView "laser_1mw_l_lod1.ply"}
									{VolumeView "laser_1mw_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_laser5mw"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.000185609	-0.350456	0.00867099
							}
							{bone "fx_laser_set_l_laser5mw"
								{Matrix34
									0.000316155	1	0
									-1	0.000315203	-0.000311375
									-0.000311374	0	1
									-0.084257	1.04496	0.231861
								}
							}
							{bone "laser5mw_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	1	0
									0	0	1
									-1.27092	-1.59479	0.387866
								}
								{bone "laser5mw_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.22915	2.07333	-0.0795104
									}
									{VolumeView "laser5mw_l_ui.ply"}
									{bone "laser5mw_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00168997	0.0916848	-0.180341
										}
										{VolumeView "laser5mw_l_light_on_ui.ply"}
									}
									{bone "laser5mw_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00168824	-0.135435	-0.180341
										}
										{VolumeView "laser5mw_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "fx_light_set_l_laser5mw"
								{Matrix34
									0.000316155	1	0
									-1	0.000315203	-0.000311375
									-0.000311374	0	1
									0.0243258	1.06706	0.388582
								}
							}
							{bone "laser5mw_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	-0.000678399
									1	0	0
									0	-0.000678401	-1
									0.000676274	0.299214	0.125439
								}
								{visibility 0}
								{LODView
									{VolumeView "laser5mw_l.ply"}
									{VolumeView "laser5mw_l_lod1.ply"}
									{VolumeView "laser5mw_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_zenitco"
							{parameters "Voxels=0;"}
							{Position -0.00977302	-0.252308	-0.0167778}
							{bone "fx_laser_set_l_zenitco"
								{Matrix34
									-0.000180082	1	0
									0.00018032	0	-1
									-1	-0.000180108	-0.00018032
									-0.25145	0.949906	0.249174
								}
							}
							{bone "zenitco_l_ui_bone"
								{parameters "Voxels=0;"}
								{Position -1.11732	-1.69951	0.273913}
								{bone "zenitco_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.03691	1.74906	-0.067075
									}
									{VolumeView "zenitco_l_ui.ply"}
									{bone "zenitco_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00142562	0.0773451	-0.152136
										}
										{VolumeView "zenitco_l_light_on_ui.ply"}
									}
									{bone "zenitco_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00142425	-0.114254	-0.152136
										}
										{VolumeView "zenitco_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "fx_light_set_l_zenitco"
								{Matrix34
									-0.000180082	1	0
									0.00018032	0	-1
									-1	-0.000180108	-0.00018032
									0.0021224	0.935023	0.617633
								}
							}
							{bone "zenitco_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	0	-1
									0	1	0
									1	0	0
									-0.0280726	0.210806	0.484672
								}
								{visibility 0}
								{LODView
									{VolumeView "zenitco_l.ply"}
									{VolumeView "zenitco_l_lod1.ply"}
									{VolumeView "zenitco_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_tactical_laser2"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.00401771	0.225453	0.00130218
							}
							{bone "fx_laser_set_l_tactical_laser2"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.311153	0.784477	0.13975
								}
							}
							{bone "tactical_laser2_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	1	0
									0	0	1
									-1.40258	-2.131	0.0799834
								}
								{bone "tactical_laser2_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.54213	2.07333	-0.0795118
									}
									{VolumeView "tactical_laser2_l_ui.ply"}
									{bone "tactical_laser2_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169286	0.00753379	-0.00288105
										}
										{VolumeView "tactical_laser2_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "tactical_laser2_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									-1	0	0
									0	0	1
									0.0199846	-0.768369	0.107365
								}
								{visibility 0}
								{LODView
									{VolumeView "tactical_laser2_l.ply"}
									{VolumeView "tactical_laser2_l_lod1.ply"}
									{VolumeView "tactical_laser2_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_tactical_laser"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.00528216	0.228599	0.00755748
							}
							{bone "fx_laser_set_l_tactical_laser"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.166149	0.118037	0.342767
								}
							}
							{bone "tactical_laser_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	1	0
									0	0	1
									-1.59816	-2.37419	0.576288
								}
								{bone "tactical_laser_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.54213	2.07333	-0.0795118
									}
									{VolumeView "tactical_laser_l_ui.ply"}
									{bone "tactical_laser_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169289	0.00753379	-0.00288105
										}
										{VolumeView "tactical_laser_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "tactical_laser_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									1	0	0
									0	0	-1
									-0.00168097	-0.298406	0.132737
								}
								{visibility 0}
								{LODView
									{VolumeView "tactical_laser_l.ply"}
									{VolumeView "tactical_laser_l_lod1.ply"}
									{VolumeView "tactical_laser_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_lasercylinder1"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.003263	0.172601	5.64754e-05
							}
							{bone "fx_laser_set_l_lasercylinder1"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									0.010458	1.16608	0.318184
								}
							}
							{bone "lasercylinder1_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	-1	0
									0	0	1
									-1.66555	2.05565	0.368709
								}
								{bone "lasercylinder1_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.54213	2.07333	-0.0795118
									}
									{VolumeView "lasercylinder1_l_ui.ply"}
									{bone "lasercylinder1_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169283	0.00753379	-0.00288105
										}
										{VolumeView "lasercylinder1_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "laser_rail_l_lasercylinder1"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.0304736	-0.0559611	0.0480547
								}
								{visibility 0}
								{LODView
									{VolumeView "laser_rail_l_lasercylinder1.ply"}
									{VolumeView "laser_rail_l_lasercylinder1_lod1.ply"}
									{VolumeView "laser_rail_l_lasercylinder1_lod2.ply"}
								}
								{bone "lasercylinder1_l"
									{parameters "CommonMesh;"}
									{Position 0.261009	-0.272776	-0.0384697}
									{visibility 0}
									{LODView
										{VolumeView "lasercylinder1_l.ply"}
										{VolumeView "lasercylinder1_l_lod1.ply"}
										{VolumeView "lasercylinder1_l_lod2.ply"}
									}
								}
							}
						}
						{bone "upgrade_left_liner"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-0.00449121	0.0309849	0.00286025
							}
							{bone "fx_laser_set_l_liner"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.000622869	1.37385	0.36789
								}
							}
							{bone "liner_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	-1	0
									0	0	1
									-1.58869	2.30099	0.191704
								}
								{bone "liner_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.47097	1.97766	-0.0758429
									}
									{VolumeView "liner_l_ui.ply"}
									{bone "liner_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00161475	0.00718617	-0.00274801
										}
										{VolumeView "liner_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "liner_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	0	-1
									0	1	0
									1	0	0
									-0.00796568	0.269214	-0.022884
								}
								{visibility 0}
								{LODView
									{VolumeView "liner_l.ply"}
									{VolumeView "liner_l_lod1.ply"}
									{VolumeView "liner_l_lod2.ply"}
								}
							}
						}
						{bone "upgrade_left_lasercylinder3"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								0.000678182	0.153623	-3.9041e-05
							}
							{bone "fx_laser_set_l_lasercylinder3"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									0.00381732	0.754426	0.324019
								}
							}
							{bone "lasercylinder3_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	-1	0
									0	0	1
									-1.66555	2.05565	0.368709
								}
								{bone "lasercylinder3_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.54213	2.07333	-0.0795118
									}
									{VolumeView "lasercylinder3_l_ui.ply"}
									{bone "lasercylinder3_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169283	0.00753379	-0.00288105
										}
										{VolumeView "lasercylinder3_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "laser_rail_l_lasercylinder3"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.0304737	-0.0559611	0.0503861
								}
								{visibility 0}
								{LODView
									{VolumeView "laser_rail_l_lasercylinder3.ply"}
									{VolumeView "laser_rail_l_lasercylinder3_lod1.ply"}
									{VolumeView "laser_rail_l_lasercylinder3_lod2.ply"}
								}
								{bone "lasercylinder3_l"
									{parameters "CommonMesh;"}
									{Position 0.252432	-0.273107	-0.0292597}
									{visibility 0}
									{LODView
										{VolumeView "lasercylinder3_l.ply"}
										{VolumeView "lasercylinder3_l_lod1.ply"}
										{VolumeView "lasercylinder3_l_lod2.ply"}
									}
								}
							}
						}
						{bone "upgrade_left_lasercylinder4"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								0.000299931	0.14823	-0.0011473
							}
							{bone "fx_laser_set_l_lasercylinder4"
								{parameters "Voxels=0;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									0.00381732	0.863987	0.324019
								}
							}
							{bone "lasercylinder4_l_ui_bone"
								{parameters "Voxels=0;"}
								{Matrix34
									1	0	0
									0	-1	0
									0	0	1
									-1.66555	2.05565	0.368709
								}
								{bone "lasercylinder4_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.54213	2.07333	-0.0795118
									}
									{VolumeView "lasercylinder4_l_ui.ply"}
									{bone "lasercylinder4_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0	1	0
											1	0	0
											0.00169283	0.00753379	-0.00288105
										}
										{VolumeView "lasercylinder4_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "laser_rail_l_lasercylinder4"
								{parameters "CommonMesh;"}
								{Matrix34
									0	1	0
									0	0	-1
									-1	0	0
									-0.0312266	-0.0559616	0.0517287
								}
								{visibility 0}
								{LODView
									{VolumeView "laser_rail_l_lasercylinder4.ply"}
									{VolumeView "laser_rail_l_lasercylinder4_lod1.ply"}
									{VolumeView "laser_rail_l_lasercylinder4_lod2.ply"}
								}
								{bone "lasercylinder4_l"
									{parameters "CommonMesh;"}
									{Position 0.282068	-0.270219	-0.0339978}
									{visibility 0}
									{LODView
										{VolumeView "lasercylinder4_l.ply"}
										{VolumeView "lasercylinder4_l_lod1.ply"}
										{VolumeView "lasercylinder4_l_lod2.ply"}
									}
								}
							}
						}
						{bone "upgrade_left_peq10"
							{parameters "Voxels=0;"}
							{Position 0.00529599	-0.193738	-0.0228993}
							{bone "fx_laser_set_l_peq10"
								{Matrix34
									-0.000180077	1	0
									0.00018032	0	-1
									-1	-0.000180098	-0.00018032
									-0.198756	1.0307	0.411119
								}
							}
							{bone "an_peq10_l"
								{parameters "CommonMesh;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									-0.0054127	-0.228237	0.114058
								}
								{visibility 0}
								{LODView
									{VolumeView "an_peq10_l.ply"}
									{VolumeView "an_peq10_l_lod1.ply"}
									{VolumeView "an_peq10_l_lod2.ply"}
								}
								{bone "caps_front_l"
									{parameters "CommonMesh;"}
									{Matrix34
										-0.087157	0.996195	-5.83522e-05
										0.996195	0.0871569	-5.77847e-05
										-5.2479e-05	-6.31664e-05	-1
										0.305355	1.04526	-0.00471866
									}
									{VolumeView "caps_front_l.ply"}
								}
							}
							{bone "peq10_l_ui_bone"
								{parameters "Voxels=0;"}
								{Position -1.24997	-2.03898	0.525431}
								{bone "peq10_l_ui"
									{parameters "CommonMesh;"}
									{Matrix34
										0	0	1
										0	1	0
										-1	0	0
										1.24403	2.09843	-0.0804731
									}
									{VolumeView "peq10_l_ui.ply"}
									{bone "peq10_l_light_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0.00571888	0.999984	0
											1	0	0
											0.00171238	-0.00224924	-0.0128715
										}
										{VolumeView "peq10_l_light_on_ui.ply"}
									}
									{bone "peq10_l_laser_on_ui"
										{parameters "CommonMesh;"}
										{Matrix34
											0	0	-1
											0.00571888	0.999984	0
											1	0	0
											0.00169981	-0.012907	-0.0128739
										}
										{VolumeView "peq10_l_laser_on_ui.ply"}
									}
								}
							}
							{bone "fx_light_set_l_peq10"
								{Matrix34
									-0.000180077	1	0
									0.00018032	0	-1
									-1	-0.000180098	-0.00018032
									0.212956	1.0307	0.434841
								}
							}
						}