			{bone "upgrade_left_flashlight_sf"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.72688	-0.366423	1.68081
				}
				{bone "fx_light_set_l_flashlight_sf"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00437379	1.17743	0.529101
					}
				}
				{bone "flashlight_sf_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	1	0
						0	0	1
						-1.45763	-1.56612	0.611862
					}
					{bone "flashlight_sf_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.43113	1.92409	-0.0737888
						}
						{VolumeView "flashlight_sf_l_ui.ply"}
						{bone "flashlight_sf_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00157106	0.00699139	-0.00267375
							}
							{VolumeView "flashlight_sf_l_light_on_ui.ply"}
						}
					}
				}
				{bone "flashlight_sf_l"
					{parameters "ID=body;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	-1
						0.00048542	0	-7.97212e-05
					}
					{LODView
						{VolumeView "flashlight_sf_l.ply"}
						{VolumeView "flashlight_sf_l_lod1.ply"}
						{VolumeView "flashlight_sf_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_laser1mw"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.25027	-0.373063	1.67994
				}
				{bone "fx_laser_set_l_laser1mw"
					{Matrix34
						0.0003164	1	0
						-1	0.00031496	-0.00031137
						-0.000311379	0	1
						0.00246739	0.571835	0.769714
					}
				}
				{bone "laser1mw_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	1	0
						0	0	1
						-1.25954	-1.41146	0.431901
					}
					{bone "laser1mw_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.17809	1.98721	-0.0762078
						}
						{VolumeView "laser1mw_l_ui.ply"}
						{bone "laser1mw_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161976	0.0878763	-0.172851
							}
							{VolumeView "laser1mw_l_light_on_ui.ply"}
						}
						{bone "laser1mw_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161815	-0.12981	-0.172851
							}
							{VolumeView "laser1mw_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_l_laser1mw"
					{Matrix34
						0.0003164	1	0
						-1	0.00031496	-0.00031137
						-0.000311379	0	1
						0.0020597	1.36021	0.392719
					}
				}
				{bone "laser_1mw_l"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						1	0	0
						0	0	-1
						0.00417376	0.062006	0.12489
					}
					{LODView
						{VolumeView "laser_1mw_l.ply"}
						{VolumeView "laser_1mw_l_lod1.ply"}
						{VolumeView "laser_1mw_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_laser5mw"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.13784	-0.373399	1.67471
				}
				{bone "fx_laser_set_l_laser5mw"
					{Matrix34
						0.0003164	1	0
						-1	0.00031496	-0.00031137
						-0.000311379	0	1
						-0.0807569	1.00156	0.22223
					}
				}
				{bone "laser5mw_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	1	0
						0	0	1
						-1.21813	-1.52855	0.371755
					}
					{bone "laser5mw_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.17809	1.98721	-0.0762078
						}
						{VolumeView "laser5mw_l_ui.ply"}
						{bone "laser5mw_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161976	0.0878763	-0.172851
							}
							{VolumeView "laser5mw_l_light_on_ui.ply"}
						}
						{bone "laser5mw_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161815	-0.12981	-0.172851
							}
							{VolumeView "laser5mw_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_l_laser5mw"
					{Matrix34
						0.0003164	1	0
						-1	0.00031496	-0.00031137
						-0.000311379	0	1
						0.0233157	1.02274	0.372442
					}
				}
				{bone "laser5mw_l"
					{parameters "ID=body;"}
					{Matrix34
						0	1	-0.000678396
						1	0	0
						0	-0.000678405	-1
						0.00064826	0.286786	0.120229
					}
					{LODView
						{VolumeView "laser5mw_l.ply"}
						{VolumeView "laser5mw_l_lod1.ply"}
						{VolumeView "laser5mw_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_lasercylinder1"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.63917	-0.369775	1.67627
				}
				{bone "fx_laser_set_l_lasercylinder1"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.0100236	1.11765	0.304968
					}
				}
				{bone "lasercylinder1_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	-1	0
						0	0	1
						-1.59637	1.97026	0.353394
					}
					{bone "lasercylinder1_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "lasercylinder1_l_ui.ply"}
						{bone "lasercylinder1_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "lasercylinder1_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser_rail_l_lasercylinder1"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0292078	-0.0536366	0.0460587
					}
					{LODView
						{VolumeView "laser_rail_l_lasercylinder1.ply"}
						{VolumeView "laser_rail_l_lasercylinder1_lod1.ply"}
						{VolumeView "laser_rail_l_lasercylinder1_lod2.ply"}
					}
					{bone "lasercylinder1_l"
						{parameters "ID=body;"}
						{Position 0.250168	-0.261446	-0.0368719}
						{LODView
							{VolumeView "lasercylinder1_l.ply"}
							{VolumeView "lasercylinder1_l_lod1.ply"}
							{VolumeView "lasercylinder1_l_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_left_lasercylinder3"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.62099	-0.370071	1.67249
				}
				{bone "fx_laser_set_l_lasercylinder3"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00365865	0.72309	0.310561
					}
				}
				{bone "lasercylinder3_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	-1	0
						0	0	1
						-1.59637	1.97026	0.353394
					}
					{bone "lasercylinder3_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762093
						}
						{VolumeView "lasercylinder3_l_ui.ply"}
						{bone "lasercylinder3_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "lasercylinder3_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser_rail_l_lasercylinder3"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0292078	-0.0536375	0.0482933
					}
					{LODView
						{VolumeView "laser_rail_l_lasercylinder3.ply"}
						{VolumeView "laser_rail_l_lasercylinder3_lod1.ply"}
						{VolumeView "laser_rail_l_lasercylinder3_lod2.ply"}
					}
					{bone "lasercylinder3_l"
						{parameters "ID=body;"}
						{Position 0.241947	-0.261764	-0.0280443}
						{LODView
							{VolumeView "lasercylinder3_l.ply"}
							{VolumeView "lasercylinder3_l_lod1.ply"}
							{VolumeView "lasercylinder3_l_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_left_lasercylinder4"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.6158	-0.369119	1.67286
				}
				{bone "fx_laser_set_l_lasercylinder4"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00365865	0.828101	0.310561
					}
				}
				{bone "lasercylinder4_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	-1	0
						0	0	1
						-1.59637	1.97026	0.353394
					}
					{bone "lasercylinder4_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762093
						}
						{VolumeView "lasercylinder4_l_ui.ply"}
						{bone "lasercylinder4_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276124
							}
							{VolumeView "lasercylinder4_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser_rail_l_lasercylinder4"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0299295	-0.0536375	0.0495802
					}
					{LODView
						{VolumeView "laser_rail_l_lasercylinder4.ply"}
						{VolumeView "laser_rail_l_lasercylinder4_lod1.ply"}
						{VolumeView "laser_rail_l_lasercylinder4_lod2.ply"}
					}
					{bone "lasercylinder4_l"
						{parameters "ID=body;"}
						{Position 0.270352	-0.258995	-0.0325856}
						{LODView
							{VolumeView "lasercylinder4_l.ply"}
							{VolumeView "lasercylinder4_l_lod1.ply"}
							{VolumeView "lasercylinder4_l_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_left_liner"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.50344	-0.372413	1.67745
				}
				{bone "fx_laser_set_l_liner"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.000597	1.31678	0.352609
					}
				}
				{bone "liner_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						0.999943	-0.00634422	0.00855165
						-0.00639386	-0.999963	0.00579048
						-0.00851458	0.00584485	0.999947
						-1.35329	2.05296	0.217554
					}
					{bone "liner_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.40987	1.89551	-0.0726927
						}
						{VolumeView "liner_l_ui.ply"}
						{bone "liner_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00154769	0.00688648	-0.00263393
							}
							{VolumeView "liner_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "liner_l"
					{parameters "ID=body;"}
					{Matrix34
						0	0	-1
						0	1	0
						1	0	0
						-0.00763476	0.258032	-0.0219335
					}
					{LODView
						{VolumeView "liner_l.ply"}
						{VolumeView "liner_l_lod1.ply"}
						{VolumeView "liner_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_peq10"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.28805	-0.347723	1.66807
				}
				{bone "fx_laser_set_l_peq10"
					{Matrix34
						-0.000180089	1	0
						0.00018032	0	-1
						-1	-0.000180104	-0.00018032
						-0.1905	0.98789	0.394042
					}
				}
				{bone "an_peq10_l"
					{parameters "ID=body;"}
					{Matrix34
						0	0	1
						0	1	0
						-1	0	0
						-0.00518787	-0.218758	0.109321
					}
					{LODView
						{VolumeView "an_peq10_l.ply"}
						{VolumeView "an_peq10_l_lod1.ply"}
						{VolumeView "an_peq10_l_lod2.ply"}
					}
					{bone "caps_front_l"
						{parameters "ID=body;"}
						{Matrix34
							-0.087157	0.996195	-5.83522e-05
							0.996195	0.0871569	-5.77847e-05
							-5.2479e-05	-6.31664e-05	-1
							0.292672	1.00185	-0.00452268
						}
						{VolumeView "caps_front_l.ply"}
					}
				}
				{bone "peq10_l_ui_bone"
					{parameters "Voxels=0;"}
					{Position -1.19805	-1.95429	0.503607}
					{bone "peq10_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.19236	2.01127	-0.0771306
						}
						{VolumeView "peq10_l_ui.ply"}
						{bone "peq10_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0.00571888	0.999984	0
								1	0	0
								0.00164127	-0.00215626	-0.0123369
							}
							{VolumeView "peq10_l_light_on_ui.ply"}
						}
						{bone "peq10_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0.00571888	0.999984	0
								1	0	0
								0.00162923	-0.0123711	-0.0123392
							}
							{VolumeView "peq10_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_l_peq10"
					{Matrix34
						-0.000180089	1	0
						0.00018032	0	-1
						-1	-0.000180104	-0.00018032
						0.204111	0.98789	0.41678
					}
				}
			}
			{bone "upgrade_left_peq15"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.52824	-0.374675	1.70578
				}
				{bone "fx_light_set_l_peq15"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.37315	1.24864	0.264878
					}
				}
				{bone "fx_laser_set_l_peq15"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.328325	1.00628	0.237176
					}
				}
				{bone "caps_light_l"
					{parameters "ID=body;"}
					{Matrix34
						0	0.984808	0.173648
						0	0.173648	-0.984808
						-1	0	0
						-0.319889	0.886099	0.316916
					}
					{VolumeView "caps_light_l.ply"}
				}
				{bone "caps_laser_l"
					{parameters "ID=body;"}
					{Matrix34
						0	0	1
						-1	0	0
						0	-1	0
						0.296953	0.761898	0.316286
					}
					{VolumeView "caps_laser_l.ply"}
				}
				{bone "peq15_l_ui_bone"
					{parameters "Voxels=0;"}
					{Position -1.32405	-1.38751	0.344844}
					{bone "peq15_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.20749	1.87818	-0.0720267
						}
						{VolumeView "peq15_l_ui.ply"}
						{bone "peq15_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00153196	0.0067749	-0.00389135
							}
							{VolumeView "peq15_l_light_on_ui.ply"}
						}
						{bone "peq15_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00152028	0.00651836	-0.00389135
							}
							{VolumeView "peq15_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "peq15_l"
					{parameters "ID=body;"}
					{Position 8.61883e-05	-0.0283937	-0.0280394}
					{LODView
						{VolumeView "peq15_l.ply"}
						{VolumeView "peq15_l_lod1.ply"}
						{VolumeView "peq15_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_tactical_laser"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.69284	-0.376915	1.6782
				}
				{bone "fx_laser_set_l_tactical_laser"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.159248	0.113134	0.32853
					}
				}
				{bone "tactical_laser_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	1	0
						0	0	1
						-1.53178	-2.27558	0.552352
					}
					{bone "tactical_laser_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "tactical_laser_l_ui.ply"}
						{bone "tactical_laser_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "tactical_laser_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "tactical_laser_l"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						1	0	0
						0	0	-1
						-0.00161111	-0.286011	0.127223
					}
					{LODView
						{VolumeView "tactical_laser_l.ply"}
						{VolumeView "tactical_laser_l_lod1.ply"}
						{VolumeView "tactical_laser_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_tactical_laser2"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.68984	-0.369887	1.67699
				}
				{bone "fx_laser_set_l_tactical_laser2"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.298229	0.751892	0.133945
					}
				}
				{bone "tactical_laser2_l_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						1	0	0
						0	1	0
						0	0	1
						-1.34432	-2.04248	0.0766612
					}
					{bone "tactical_laser2_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762093
						}
						{VolumeView "tactical_laser2_l_ui.ply"}
						{bone "tactical_laser2_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "tactical_laser2_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "tactical_laser2_l"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						-1	0	0
						0	0	1
						0.0191545	-0.736454	0.102905
					}
					{LODView
						{VolumeView "tactical_laser2_l.ply"}
						{VolumeView "tactical_laser2_l_lod1.ply"}
						{VolumeView "tactical_laser2_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_left_zenitco"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	-1
					1	0	0
					0	-1	0
					5.23191	-0.35359	1.68251
				}
				{bone "fx_laser_set_l_zenitco"
					{Matrix34
						-0.000180078	1	0
						0.00018032	0	-1
						-1	-0.000180105	-0.00018032
						-0.241006	0.910452	0.238825
					}
				}
				{bone "zenitco_l_ui_bone"
					{parameters "Voxels=0;"}
					{Position -1.07091	-1.62892	0.262536}
					{bone "zenitco_l_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							0.99384	1.67641	-0.064289
						}
						{VolumeView "zenitco_l_ui.ply"}
						{bone "zenitco_l_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00136644	0.0741329	-0.145817
							}
							{VolumeView "zenitco_l_light_on_ui.ply"}
						}
						{bone "zenitco_l_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00136507	-0.109508	-0.145817
							}
							{VolumeView "zenitco_l_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_l_zenitco"
					{Matrix34
						-0.000180078	1	0
						0.00018032	0	-1
						-1	-0.000180105	-0.00018032
						0.00203431	0.896186	0.591979
					}
				}
				{bone "zenitco_l"
					{parameters "ID=body;"}
					{Matrix34
						0	0	-1
						0	1	0
						1	0	0
						-0.0269066	0.20205	0.46454
					}
					{LODView
						{VolumeView "zenitco_l.ply"}
						{VolumeView "zenitco_l_lod1.ply"}
						{VolumeView "zenitco_l_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_flashlight_sf"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.72133	0.364046	1.66611
				}
				{bone "fx_light_set_r_flashlight_sf"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.0043726	1.17743	0.5291
					}
				}
				{bone "flashlight_sf_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.5012	2.05194	0.246306
					}
					{bone "flashlight_sf_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.43112	1.72594	-0.0737882
						}
						{VolumeView "flashlight_sf_r_ui.ply"}
						{bone "flashlight_sf_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00157094	0.00699139	-0.00267375
							}
							{VolumeView "flashlight_sf_r_light_on_ui.ply"}
						}
					}
				}
				{bone "flashlight_sf_r"
					{parameters "ID=body;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	-1
						0	0	-0.000485688
					}
					{LODView
						{VolumeView "flashlight_sf_r.ply"}
						{VolumeView "flashlight_sf_r_lod1.ply"}
						{VolumeView "flashlight_sf_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_laser1mw"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.20463	0.367741	1.66376
				}
				{bone "fx_laser_set_r_laser1mw"
					{Matrix34
						0	1	0
						-1	0	0
						0	0	1
						0.00256991	0.59566	0.801785
					}
				}
				{bone "laser1mw_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.34217	2.3067	0.413673
					}
					{bone "laser1mw_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.22718	2.07001	-0.0793831
						}
						{VolumeView "laser1mw_r_ui.ply"}
						{bone "laser1mw_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00168729	0.0915384	-0.180053
							}
							{VolumeView "laser1mw_r_light_on_ui.ply"}
						}
						{bone "laser1mw_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00168562	-0.135218	-0.180053
							}
							{VolumeView "laser1mw_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_r_laser1mw"
					{Matrix34
						0.000315676	1	0
						-1	0.00031568	-0.000311375
						-0.000311375	0	1
						0.00214458	1.41688	0.409082
					}
				}
				{bone "laser_1mw_r"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						1	0	0
						0	0	-1
						0.00434756	0.0645895	0.130094
					}
					{LODView
						{VolumeView "laser_1mw_r.ply"}
						{VolumeView "laser_1mw_r_lod1.ply"}
						{VolumeView "laser_1mw_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_laser5mw"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.13162	0.385496	1.64231
				}
				{bone "fx_light_set_r_laser5mw"
					{Matrix34
						0.000315677	1	0
						-1	0.00031568	-0.000311375
						-0.000311374	0	1
						0.0233151	1.02274	0.372442
					}
				}
				{bone "fx_laser_set_r_laser5mw"
					{Matrix34
						0.000315677	1	0
						-1	0.00031568	-0.000311375
						-0.000311374	0	1
						-0.0807576	1.00156	0.22223
					}
				}
				{bone "laser5mw_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.17584	2.40252	0.413049
					}
					{bone "laser5mw_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.17809	1.98721	-0.0762079
						}
						{VolumeView "laser5mw_r_ui.ply"}
						{bone "laser5mw_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161976	0.0878763	-0.172851
							}
							{VolumeView "laser5mw_r_light_on_ui.ply"}
						}
						{bone "laser5mw_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00161815	-0.12981	-0.172851
							}
							{VolumeView "laser5mw_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser5mw_r"
					{parameters "ID=body;"}
					{Matrix34
						0	1	-0.000678404
						1	0	0
						0	-0.000678396	-1
						0.0305917	0.286787	0.116053
					}
					{LODView
						{VolumeView "laser5mw_r.ply"}
						{VolumeView "laser5mw_r_lod1.ply"}
						{VolumeView "laser5mw_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_lasercylinder1"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.63487	0.367803	1.66797
				}
				{bone "fx_laser_set_r_lasercylinder1"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00847685	1.11602	0.307988
					}
				}
				{bone "lasercylinder1_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	1
						1.61232	-2.07954	0.382686
					}
					{bone "lasercylinder1_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "lasercylinder1_r_ui.ply"}
						{bone "lasercylinder1_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "lasercylinder1_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser_rail_r_lasercylinder1"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0284421	-0.0536375	0.0466311
					}
					{LODView
						{VolumeView "laser_rail_r_lasercylinder1.ply"}
						{VolumeView "laser_rail_r_lasercylinder1_lod1.ply"}
						{VolumeView "laser_rail_r_lasercylinder1_lod2.ply"}
					}
					{bone "lasercylinder1_r"
						{parameters "ID=body;"}
						{Position 0.250168	-0.261446	-0.0368718}
						{LODView
							{VolumeView "lasercylinder1_r.ply"}
							{VolumeView "lasercylinder1_r_lod1.ply"}
							{VolumeView "lasercylinder1_r_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_right_lasercylinder3"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.63252	0.363119	1.66657
				}
				{bone "fx_laser_set_r_lasercylinder3"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00253391	0.729432	0.311328
					}
				}
				{bone "lasercylinder3_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	1
						1.61232	-2.07954	0.382686
					}
					{bone "lasercylinder3_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "lasercylinder3_r_ui.ply"}
						{bone "lasercylinder3_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "lasercylinder3_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "laser_rail_r_lasercylinder3"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0281116	-0.0536375	0.0501712
					}
					{LODView
						{VolumeView "laser_rail_r_lasercylinder3.ply"}
						{VolumeView "laser_rail_r_lasercylinder3_lod1.ply"}
						{VolumeView "laser_rail_r_lasercylinder3_lod2.ply"}
					}
					{bone "lasercylinder3_r"
						{parameters "ID=body;"}
						{Position 0.241947	-0.261763	-0.0280442}
						{LODView
							{VolumeView "lasercylinder3_r.ply"}
							{VolumeView "lasercylinder3_r_lod1.ply"}
							{VolumeView "lasercylinder3_r_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_right_lasercylinder4"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.6272	0.366642	1.66763
				}
				{bone "lasercylinder4_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	1
						1.61232	-2.07954	0.382686
					}
					{bone "lasercylinder4_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "lasercylinder4_r_ui.ply"}
						{bone "lasercylinder4_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.0016225	0.00722122	-0.00276136
							}
							{VolumeView "lasercylinder4_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_laser_set_r_lasercylinder4"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.00253403	0.834443	0.311328
					}
				}
				{bone "laser_rail_r_lasercylinder4"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0276874	-0.0536366	0.0481603
					}
					{LODView
						{VolumeView "laser_rail_r_lasercylinder4.ply"}
						{VolumeView "laser_rail_r_lasercylinder4_lod1.ply"}
						{VolumeView "laser_rail_r_lasercylinder4_lod2.ply"}
					}
					{bone "lasercylinder4_r"
						{parameters "ID=body;"}
						{Position 0.270354	-0.267118	-0.0250309}
						{LODView
							{VolumeView "lasercylinder4_r.ply"}
							{VolumeView "lasercylinder4_r_lod1.ply"}
							{VolumeView "lasercylinder4_r_lod2.ply"}
						}
					}
				}
			}
			{bone "upgrade_right_liner"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.51084	0.370521	1.67151
				}
				{bone "fx_laser_set_r_liner"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.0131749	1.32232	0.355102
					}
				}
				{bone "liner_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	1	0
						0	0	1
						1.54783	-2.05824	0.547827
					}
					{bone "liner_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.41895	1.90772	-0.0731609
						}
						{VolumeView "liner_r_ui.ply"}
						{bone "liner_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00155765	0.00693226	-0.00265098
							}
							{VolumeView "liner_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "liner_r"
					{parameters "ID=body;"}
					{Matrix34
						0	0	-1
						0	1	0
						1	0	0
						-0.00768411	0.259694	-0.0220747
					}
					{LODView
						{VolumeView "liner_r.ply"}
						{VolumeView "liner_r_lod1.ply"}
						{VolumeView "liner_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_peq10"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.40076	0.36562	1.66708
				}
				{bone "an_peq10_r"
					{parameters "ID=body;"}
					{Matrix34
						0	0	1
						0	1	0
						-1	0	0
						0.0047884	-0.204135	0.0813742
					}
					{LODView
						{VolumeView "an_peq10_r.ply"}
						{VolumeView "an_peq10_r_lod1.ply"}
						{VolumeView "an_peq10_r_lod2.ply"}
					}
					{bone "caps_front_r"
						{parameters "ID=body;"}
						{Matrix34
							0.0871559	0.996195	0
							-0.996195	0.0871559	0
							0	0	1
							0.27289	0.934131	-0.00422156
						}
						{VolumeView "caps_front_r.ply"}
					}
				}
				{bone "fx_laser_set_r_peq10"
					{Matrix34
						0.000315678	1	0
						-1	0.000315684	-0.000311375
						-0.000311374	0	1
						-0.177624	0.921118	0.367409
					}
				}
				{bone "peq10_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.11889	1.67564	0.376042
					}
					{bone "peq10_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.11177	1.87533	-0.0719173
						}
						{VolumeView "peq10_r_ui.ply"}
						{bone "peq10_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00152856	0.0829287	-0.163119
							}
							{VolumeView "peq10_r_light_on_ui.ply"}
						}
						{bone "peq10_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00152701	-0.122501	-0.163119
							}
							{VolumeView "peq10_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_r_peq10"
					{Matrix34
						0.000315678	1	0
						-1	0.000315684	-0.000311375
						-0.000311374	0	1
						0.184977	0.921117	0.367408
					}
				}
			}
			{bone "upgrade_right_peq15"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.64926	0.373191	1.62817
				}
				{bone "fx_light_set_r_peq15"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.388003	1.29834	0.275421
					}
				}
				{bone "fx_laser_set_r_peq15"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						0.341393	1.04633	0.246616
					}
				}
				{bone "caps_light_r"
					{parameters "ID=body;"}
					{Matrix34
						0	0.984808	0.173648
						0	0.173648	-0.984808
						-1	0	0
						-0.332621	0.921368	0.32953
					}
					{VolumeView "caps_light_r.ply"}
				}
				{bone "caps_laser_r"
					{parameters "ID=body;"}
					{Matrix34
						0	0	1
						-1	0	0
						0	-1	0
						0.308772	0.792223	0.328875
					}
					{VolumeView "caps_laser_r.ply"}
				}
				{bone "peq15_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.32759	1.83171	0.412333
					}
					{bone "peq15_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.25555	1.95294	-0.0748936
						}
						{VolumeView "peq15_r_ui.ply"}
						{bone "peq15_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00159293	0.00704479	-0.0040462
							}
							{VolumeView "peq15_r_light_on_ui.ply"}
						}
						{bone "peq15_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00158083	0.00677776	-0.0040462
							}
							{VolumeView "peq15_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "peq15_r"
					{parameters "ID=body;"}
					{Position 0.00922179	-0.0184126	-0.0291555}
					{LODView
						{VolumeView "peq15_r.ply"}
						{VolumeView "peq15_r_lod1.ply"}
						{VolumeView "peq15_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_tactical_laser"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.69678	0.367382	1.66476
				}
				{bone "fx_laser_set_r_tactical_laser"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.159248	0.113134	0.32853
					}
				}
				{bone "tactical_laser_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.58006	1.79569	0.658123
					}
					{bone "tactical_laser_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "tactical_laser_r_ui.ply"}
						{bone "tactical_laser_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "tactical_laser_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "tactical_laser_r"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						1	0	0
						0	0	-1
						-0.00161111	-0.286011	0.127223
					}
					{LODView
						{VolumeView "tactical_laser_r.ply"}
						{VolumeView "tactical_laser_r_lod1.ply"}
						{VolumeView "tactical_laser_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_tactical_laser2"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.74954	0.369106	1.66745
				}
				{bone "fx_laser_set_r_tactical_laser2"
					{parameters "Voxels=0;"}
					{Matrix34
						0	1	0
						0	0	-1
						-1	0	0
						-0.298229	0.751893	0.133945
					}
				}
				{bone "tactical_laser2_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.58006	2.03831	0.292362
					}
					{bone "tactical_laser2_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							1.47807	1.98721	-0.0762092
						}
						{VolumeView "tactical_laser2_r_ui.ply"}
						{bone "tactical_laser2_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00162256	0.00722122	-0.00276136
							}
							{VolumeView "tactical_laser2_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "tactical_laser2_r"
					{parameters "ID=body;"}
					{Matrix34
						0	1	0
						-1	0	0
						0	0	1
						0.0191545	-0.736454	0.102905
					}
					{LODView
						{VolumeView "tactical_laser2_r.ply"}
						{VolumeView "tactical_laser2_r_lod1.ply"}
						{VolumeView "tactical_laser2_r_lod2.ply"}
					}
				}
			}
			{bone "upgrade_right_zenitco"
				{parameters "Voxels=0;"}
				{Matrix34
					0	0	1
					1	0	0
					0	1	0
					5.27139	0.348725	1.66488
				}
				{bone "fx_laser_set_r_zenitco"
					{Matrix34
						-0.000180085	1	0
						0.00018032	0	-1
						-1	-0.000180103	-0.00018032
						-0.241006	0.904937	0.238825
					}
				}
				{bone "zenitco_r_ui_bone"
					{parameters "Voxels=0;"}
					{Matrix34
						-1	0	0
						0	-1	0
						0	0	1
						1.06687	1.69119	0.630669
					}
					{bone "zenitco_r_ui"
						{parameters "ID=body;"}
						{Matrix34
							0	0	1
							0	1	0
							-1	0	0
							0.99384	1.67641	-0.064289
						}
						{VolumeView "zenitco_r_ui.ply"}
						{bone "zenitco_r_light_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00136644	0.0741329	-0.145817
							}
							{VolumeView "zenitco_r_light_on_ui.ply"}
						}
						{bone "zenitco_r_laser_on_ui"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								0.00136507	-0.109508	-0.145817
							}
							{VolumeView "zenitco_r_laser_on_ui.ply"}
						}
					}
				}
				{bone "fx_light_set_r_zenitco"
					{Matrix34
						-0.000180085	1	0
						0.00018032	0	-1
						-1	-0.000180103	-0.00018032
						0.00203443	0.861387	0.591979
					}
				}
				{bone "zenitco_r"
					{parameters "ID=body;"}
					{Matrix34
						0	0	-1
						0	1	0
						1	0	0
						-0.0269066	0.20205	0.46454
					}
					{LODView
						{VolumeView "zenitco_r.ply"}
						{VolumeView "zenitco_r_lod1.ply"}
						{VolumeView "zenitco_r_lod2.ply"}
					}
				}
			}
