{bone "upgrade_right_lasercylinder4"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0151405	0.15879	0.0570495
	}
	{bone "lasercylinder4_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	1
			1.61491	-2.08288	0.383299
		}
		{bone "lasercylinder4_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.48044	1.99039	-0.0763314
			}
			{VolumeView "lasercylinder4_r_ui.ply"}
			{bone "lasercylinder4_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162518	0.00723267	-0.00276566
				}
				{VolumeView "lasercylinder4_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_laser_set_r_lasercylinder4"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00253797	0.83578	0.311827
		}
	}
	{bone "laser_rail_r_lasercylinder4"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0277319	-0.0537224	0.0482374
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_r_lasercylinder4.ply"}
			{VolumeView "laser_rail_r_lasercylinder4_lod1.ply"}
			{VolumeView "laser_rail_r_lasercylinder4_lod2.ply"}
		}
		{bone "lasercylinder4_r"
			{parameters "ID=body;"}
			{Position 0.270787	-0.267546	-0.025071}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder4_r.ply"}
				{VolumeView "lasercylinder4_r_lod1.ply"}
				{VolumeView "lasercylinder4_r_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_right_lasercylinder3"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0140823	0.164117	0.060578
	}
	{bone "fx_laser_set_r_lasercylinder3"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00253808	0.730601	0.311827
		}
	}
	{bone "lasercylinder3_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	1
			1.61491	-2.08288	0.383299
		}
		{bone "lasercylinder3_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.48044	1.99039	-0.0763314
			}
			{VolumeView "lasercylinder3_r_ui.ply"}
			{bone "lasercylinder3_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162518	0.00723267	-0.00276566
				}
				{VolumeView "lasercylinder3_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser_rail_r_lasercylinder3"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0281566	-0.0537238	0.0502515
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_r_lasercylinder3.ply"}
			{VolumeView "laser_rail_r_lasercylinder3_lod1.ply"}
			{VolumeView "laser_rail_r_lasercylinder3_lod2.ply"}
		}
		{bone "lasercylinder3_r"
			{parameters "ID=body;"}
			{Position 0.242335	-0.262183	-0.0280893}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder3_r.ply"}
				{VolumeView "lasercylinder3_r_lod1.ply"}
				{VolumeView "lasercylinder3_r_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_right_lasercylinder1"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0154868	0.166475	0.0558867
	}
	{bone "fx_laser_set_r_lasercylinder1"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00849032	1.11781	0.308482
		}
	}
	{bone "lasercylinder1_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	1
			1.61491	-2.08288	0.383299
		}
		{bone "lasercylinder1_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.48044	1.99039	-0.0763313
			}
			{VolumeView "lasercylinder1_r_ui.ply"}
			{bone "lasercylinder1_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162512	0.00723267	-0.00276577
				}
				{VolumeView "lasercylinder1_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser_rail_r_lasercylinder1"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.0284877	-0.0537233	0.0467058
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_rail_r_lasercylinder1.ply"}
			{VolumeView "laser_rail_r_lasercylinder1_lod1.ply"}
			{VolumeView "laser_rail_r_lasercylinder1_lod2.ply"}
		}
		{bone "lasercylinder1_r"
			{parameters "ID=body;"}
			{Position 0.250568	-0.261865	-0.036931}
			{visibility 0}
			{LODView
				{VolumeView "lasercylinder1_r.ply"}
				{VolumeView "lasercylinder1_r_lod1.ply"}
				{VolumeView "lasercylinder1_r_lod2.ply"}
			}
		}
	}
}
{bone "upgrade_right_liner"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0190336	0.0422421	0.0531643
	}
	{bone "fx_laser_set_r_liner"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.013196	1.32444	0.355671
		}
	}
	{bone "liner_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	1
			1.55031	-2.06154	0.548705
		}
		{bone "liner_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.42122	1.91078	-0.0732782
			}
			{VolumeView "liner_r_ui.ply"}
			{bone "liner_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00156021	0.00694323	-0.00265515
				}
				{VolumeView "liner_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "liner_r"
		{parameters "ID=body;"}
		{Matrix34
			0	0	-1
			0	1	0
			1	0	0
			-0.00769639	0.26011	-0.0221101
		}
		{visibility 0}
		{LODView
			{VolumeView "liner_r.ply"}
			{VolumeView "liner_r_lod1.ply"}
			{VolumeView "liner_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_zenitco"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0123904	-0.197585	0.0749955
	}
	{bone "fx_laser_set_r_zenitco"
		{Matrix34
			-0.000180068	1	0
			0.00018032	0	-1
			-1	-0.000180104	-0.00018032
			-0.241393	0.906387	0.239207
		}
	}
	{bone "zenitco_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.06858	1.69389	0.631679
		}
		{bone "zenitco_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				0.995432	1.6791	-0.064392
			}
			{VolumeView "zenitco_r_ui.ply"}
			{bone "zenitco_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00136852	0.0742517	-0.146051
				}
				{VolumeView "zenitco_r_light_on_ui.ply"}
			}
			{bone "zenitco_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00136721	-0.109684	-0.146051
				}
				{VolumeView "zenitco_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_r_zenitco"
		{Matrix34
			-0.000180068	1	0
			0.00018032	0	-1
			-1	-0.000180104	-0.00018032
			0.00203741	0.862767	0.592928
		}
	}
	{bone "zenitco_r"
		{parameters "ID=body;"}
		{Matrix34
			0	0	-1
			0	1	0
			1	0	0
			-0.0269499	0.202374	0.465285
		}
		{visibility 0}
		{LODView
			{VolumeView "zenitco_r.ply"}
			{VolumeView "zenitco_r_lod1.ply"}
			{VolumeView "zenitco_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_tactical_laser2"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0149647	0.281324	0.054581
	}
	{bone "fx_laser_set_r_tactical_laser2"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.298707	0.753098	0.13416
		}
	}
	{bone "tactical_laser2_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.58259	2.04157	0.29283
		}
		{bone "tactical_laser2_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.48044	1.99039	-0.0763314
			}
			{VolumeView "tactical_laser2_r_ui.ply"}
			{bone "tactical_laser2_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162518	0.00723267	-0.00276589
				}
				{VolumeView "tactical_laser2_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "tactical_laser2_r"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			-1	0	0
			0	0	1
			0.0191853	-0.737634	0.10307
		}
		{visibility 0}
		{LODView
			{VolumeView "tactical_laser2_r.ply"}
			{VolumeView "tactical_laser2_r_lod1.ply"}
			{VolumeView "tactical_laser2_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_tactical_laser"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0122696	0.22848	0.0563077
	}
	{bone "fx_laser_set_r_tactical_laser"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.159504	0.113316	0.329056
		}
	}
	{bone "tactical_laser_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.58259	1.79857	0.659178
		}
		{bone "tactical_laser_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.48044	1.99039	-0.0763313
			}
			{VolumeView "tactical_laser_r_ui.ply"}
			{bone "tactical_laser_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162518	0.00723267	-0.00276589
				}
				{VolumeView "tactical_laser_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "tactical_laser_r"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			1	0	0
			0	0	-1
			-0.00161374	-0.286469	0.127427
		}
		{visibility 0}
		{LODView
			{VolumeView "tactical_laser_r.ply"}
			{VolumeView "tactical_laser_r_lod1.ply"}
			{VolumeView "tactical_laser_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_laser5mw"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0.0102155	-0.337581	0.0381659
	}
	{bone "fx_light_set_r_laser5mw"
		{Matrix34
			0.000315675	1	0
			-1	0.000315683	-0.000311375
			-0.000311374	0	1
			0.0233524	1.02438	0.373039
		}
	}
	{bone "fx_laser_set_r_laser5mw"
		{Matrix34
			0.000315675	1	0
			-1	0.000315683	-0.000311375
			-0.000311374	0	1
			-0.080887	1.00316	0.222586
		}
	}
	{bone "laser5mw_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.17772	2.40637	0.413711
		}
		{bone "laser5mw_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.17998	1.99039	-0.0763301
			}
			{VolumeView "laser5mw_r_ui.ply"}
			{bone "laser5mw_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162238	0.088017	-0.173128
				}
				{VolumeView "laser5mw_r_light_on_ui.ply"}
			}
			{bone "laser5mw_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00162077	-0.130018	-0.173128
				}
				{VolumeView "laser5mw_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "laser5mw_r"
		{parameters "ID=body;"}
		{Matrix34
			0	1	-0.000678403
			1	0	0
			0	-0.000678397	-1
			0.0306407	0.287246	0.116239
		}
		{visibility 0}
		{LODView
			{VolumeView "laser5mw_r.ply"}
			{VolumeView "laser5mw_r_lod1.ply"}
			{VolumeView "laser5mw_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_laser1mw"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0112698	-0.264463	0.0559497
	}
	{bone "fx_laser_set_r_laser1mw"
		{Matrix34
			0	1	0
			-1	0	0
			0	0	1
			0.00257397	0.596615	0.80307
		}
	}
	{bone "laser1mw_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.34432	2.3104	0.414336
		}
		{bone "laser1mw_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.22915	2.07332	-0.0795103
			}
			{VolumeView "laser1mw_r_ui.ply"}
			{bone "laser1mw_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00169003	0.0916843	-0.180341
				}
				{VolumeView "laser1mw_r_light_on_ui.ply"}
			}
			{bone "laser1mw_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.0016883	-0.135436	-0.180341
				}
				{VolumeView "laser1mw_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_r_laser1mw"
		{Matrix34
			0.00031568	1	0
			-1	0.000315682	-0.000311374
			-0.000311375	0	1
			0.00214803	1.41916	0.409737
		}
	}
	{bone "laser_1mw_r"
		{parameters "ID=body;"}
		{Matrix34
			0	1	0
			1	0	0
			0	0	-1
			0.00435472	0.0646925	0.130302
		}
		{visibility 0}
		{LODView
			{VolumeView "laser_1mw_r.ply"}
			{VolumeView "laser_1mw_r_lod1.ply"}
			{VolumeView "laser_1mw_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_peq15"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		0.02438	0.180885	0.0504902
	}
	{bone "fx_light_set_r_peq15"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			-0.388624	1.30043	0.275862
		}
	}
	{bone "fx_laser_set_r_peq15"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.34194	1.04801	0.247011
		}
	}
	{bone "caps_light_r"
		{parameters "ID=body;"}
		{Matrix34
			0	0.984808	0.173648
			0	0.173648	-0.984808
			-1	0	0
			-0.333154	0.922845	0.330058
		}
		{VolumeView "caps_light_r.ply"}
	}
	{bone "caps_laser_r"
		{parameters "ID=body;"}
		{Matrix34
			0	0	1
			-1	0	0
			0	-1	0
			0.309267	0.793494	0.329402
		}
		{VolumeView "caps_laser_r.ply"}
	}
	{bone "peq15_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.32972	1.83464	0.412994
		}
		{bone "peq15_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.25756	1.95607	-0.0750136
			}
			{VolumeView "peq15_r_ui.ply"}
			{bone "peq15_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00159544	0.00705624	-0.00405264
				}
				{VolumeView "peq15_r_light_on_ui.ply"}
			}
			{bone "peq15_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00158328	0.00678873	-0.00405264
				}
				{VolumeView "peq15_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "peq15_r"
		{parameters "ID=body;"}
		{Position 0.00923657	-0.0184426	-0.0292022}
		{visibility 0}
		{LODView
			{VolumeView "peq15_r.ply"}
			{VolumeView "peq15_r_lod1.ply"}
			{VolumeView "peq15_r_lod2.ply"}
		}
	}
}
{bone "upgrade_right_peq10"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0145955	-0.0680165	0.0580729
	}
	{bone "an_peq10_r"
		{parameters "ID=body;"}
		{Matrix34
			0	0	1
			0	1	0
			-1	0	0
			0.00479615	-0.204462	0.0815046
		}
		{visibility 0}
		{LODView
			{VolumeView "an_peq10_r.ply"}
			{VolumeView "an_peq10_r_lod1.ply"}
			{VolumeView "an_peq10_r_lod2.ply"}
		}
		{bone "caps_front_r"
			{parameters "ID=body;"}
			{Matrix34
				0.0871559	0.996195	0
				-0.996195	0.0871559	0
				0	0	1
				0.273328	0.935628	-0.00422835
			}
			{visibility 0}
			{VolumeView "caps_front_r.ply"}
		}
	}
	{bone "fx_laser_set_r_peq10"
		{Matrix34
			0.000315679	1	0
			-1	0.00031568	-0.000311375
			-0.000311374	0	1
			-0.177909	0.922594	0.367998
		}
	}
	{bone "peq10_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.12068	1.67833	0.376645
		}
		{bone "peq10_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.11355	1.87833	-0.0720325
			}
			{VolumeView "peq10_r_ui.ply"}
			{bone "peq10_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00153106	0.0830622	-0.16338
				}
				{VolumeView "peq10_r_light_on_ui.ply"}
			}
			{bone "peq10_r_laser_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00152951	-0.122697	-0.163381
				}
				{VolumeView "peq10_r_laser_on_ui.ply"}
			}
		}
	}
	{bone "fx_light_set_r_peq10"
		{Matrix34
			0.000315679	1	0
			-1	0.00031568	-0.000311375
			-0.000311374	0	1
			0.185274	0.922593	0.367997
		}
	}
}
{bone "upgrade_right_flashlight_sf"
	{parameters "Voxels=0;"}
	{Matrix34
		-1	0	0
		0	1	0
		0	0	-1
		-0.0136235	0.253076	0.0596491
	}
	{bone "fx_light_set_r_flashlight_sf"
		{parameters "Voxels=0;"}
		{Matrix34
			0	1	0
			0	0	-1
			-1	0	0
			0.00437963	1.17932	0.529948
		}
	}
	{bone "flashlight_sf_r_ui_bone"
		{parameters "Voxels=0;"}
		{Matrix34
			-1	0	0
			0	-1	0
			0	0	1
			1.50361	2.05523	0.2467
		}
		{bone "flashlight_sf_r_ui"
			{parameters "ID=body;"}
			{Matrix34
				0	0	1
				0	1	0
				-1	0	0
				1.43342	1.7287	-0.0739065
			}
			{VolumeView "flashlight_sf_r_ui.ply"}
			{bone "flashlight_sf_r_light_on_ui"
				{parameters "ID=body;"}
				{Matrix34
					0	0	-1
					0	1	0
					1	0	0
					0.00157356	0.00700283	-0.00267792
				}
				{VolumeView "flashlight_sf_r_light_on_ui.ply"}
			}
		}
	}
	{bone "flashlight_sf_r"
		{parameters "ID=body;"}
		{Matrix34
			-1	0	0
			0	1	0
			0	0	-1
			0	0	-0.000486493
		}
		{visibility 0}
		{LODView
			{VolumeView "flashlight_sf_r.ply"}
			{VolumeView "flashlight_sf_r_lod1.ply"}
			{VolumeView "flashlight_sf_r_lod2.ply"}
		}
	}
}
