					{bone "upgrade_left_peq15"
						{parameters "Voxels=0;"}
						{Position -0.0343056	-0.0746727	0.0148627}
						{bone "peq15_l"
							{parameters "ID=body;"}
							{Position 8.61883e-05	-0.028439	-0.0280843}
							{visibility 0}
							{LODView
								{VolumeView "peq15_l.ply"}
								{VolumeView "peq15_l_lod1.ply"}
								{VolumeView "peq15_l_lod2.ply"}
							}
						}
						{bone "fx_light_set_l_peq15"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.373749	1.25065	0.265302
							}
						}
						{bone "fx_laser_set_l_peq15"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.328851	1.0079	0.237556
							}
						}
						{bone "caps_light_l"
							{parameters "ID=body;"}
							{Matrix34
								0	0.984808	0.173648
								0	0.173648	-0.984808
								-1	0	0
								-0.320401	0.887519	0.317423
							}
							{VolumeView "caps_light_l.ply"}
						}
						{bone "caps_laser_l"
							{parameters "ID=body;"}
							{Matrix34
								0	0	1
								-1	0	0
								0	-1	0
								0.297429	0.763119	0.316793
							}
							{VolumeView "caps_laser_l.ply"}
						}
						{bone "peq15_l_ui_bone"
							{parameters "Voxels=0;"}
							{Position -1.32617	-1.38974	0.345396}
							{bone "peq15_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.20943	1.88119	-0.0721421
								}
								{VolumeView "peq15_l_ui.ply"}
								{bone "peq15_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.0015344	0.00678587	-0.00389755
									}
									{VolumeView "peq15_l_light_on_ui.ply"}
								}
								{bone "peq15_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00152272	0.00652885	-0.00389755
									}
									{VolumeView "peq15_l_laser_on_ui.ply"}
								}
							}
						}
					}
					{bone "upgrade_left_lasercylinder3"
						{parameters "Voxels=0;"}
						{Position -0.00487411	0.144008	0.0194377}
						{bone "fx_laser_set_l_lasercylinder3"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00349903	0.691543	0.297012
							}
						}
						{bone "lasercylinder3_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	-1	0
								0	0	1
								-1.52672	1.88431	0.337976
							}
							{bone "lasercylinder3_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728844
								}
								{VolumeView "lasercylinder3_l_ui.ply"}
								{bone "lasercylinder3_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155181	0.00690603	-0.00264096
									}
									{VolumeView "lasercylinder3_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser_rail_l_lasercylinder3"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0279337	-0.0512972	0.0461863
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_l_lasercylinder3.ply"}
								{VolumeView "laser_rail_l_lasercylinder3_lod1.ply"}
								{VolumeView "laser_rail_l_lasercylinder3_lod2.ply"}
							}
							{bone "lasercylinder3_l"
								{parameters "ID=body;"}
								{Position 0.231391	-0.250343	-0.0268209}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder3_l.ply"}
									{VolumeView "lasercylinder3_l_lod1.ply"}
									{VolumeView "lasercylinder3_l_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_left_lasercylinder4"
						{parameters "Voxels=0;"}
						{Position -0.0038656	0.144008	0.0201558}
						{bone "fx_laser_set_l_lasercylinder4"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00349915	0.791973	0.297012
							}
						}
						{bone "lasercylinder4_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	-1	0
								0	0	1
								-1.52672	1.88431	0.337976
							}
							{bone "lasercylinder4_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728844
								}
								{VolumeView "lasercylinder4_l_ui.ply"}
								{bone "lasercylinder4_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155181	0.00690603	-0.00264096
									}
									{VolumeView "lasercylinder4_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser_rail_l_lasercylinder4"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0286239	-0.0512977	0.047417
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_l_lasercylinder4.ply"}
								{VolumeView "laser_rail_l_lasercylinder4_lod1.ply"}
								{VolumeView "laser_rail_l_lasercylinder4_lod2.ply"}
							}
							{bone "lasercylinder4_l"
								{parameters "ID=body;"}
								{Position 0.258557	-0.247696	-0.0311641}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder4_l.ply"}
									{VolumeView "lasercylinder4_l_lod1.ply"}
									{VolumeView "lasercylinder4_l_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_left_liner"
						{parameters "Voxels=0;"}
						{Position -0.000852704	0.144008	0.0248265}
						{bone "fx_laser_set_l_liner"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.000587106	1.29499	0.346774
							}
						}
						{bone "liner_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	-1	0
								0	0	1
								-1.49751	2.16892	0.180701
							}
							{bone "liner_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.38654	1.86414	-0.0714898
								}
								{VolumeView "liner_l_ui.ply"}
								{bone "liner_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00152206	0.00677395	-0.00259042
									}
									{VolumeView "liner_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "liner_l"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								-0.00750852	0.253762	-0.0215705
							}
							{visibility 0}
							{LODView
								{VolumeView "liner_l.ply"}
								{VolumeView "liner_l_lod1.ply"}
								{VolumeView "liner_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_lasercylinder1"
						{parameters "Voxels=0;"}
						{Position -0.00328135	0.143367	0.0214638}
						{bone "fx_laser_set_l_lasercylinder1"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00958622	1.06889	0.291663
							}
						}
						{bone "lasercylinder1_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	-1	0
								0	0	1
								-1.52672	1.88431	0.337976
							}
							{bone "lasercylinder1_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728844
								}
								{VolumeView "lasercylinder1_l_ui.ply"}
								{bone "lasercylinder1_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155181	0.00690603	-0.00264096
									}
									{VolumeView "lasercylinder1_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser_rail_l_lasercylinder1"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0279337	-0.0512967	0.0440492
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_l_lasercylinder1.ply"}
								{VolumeView "laser_rail_l_lasercylinder1_lod1.ply"}
								{VolumeView "laser_rail_l_lasercylinder1_lod2.ply"}
							}
							{bone "lasercylinder1_l"
								{parameters "ID=body;"}
								{Position 0.239253	-0.25004	-0.0352633}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder1_l.ply"}
									{VolumeView "lasercylinder1_l_lod1.ply"}
									{VolumeView "lasercylinder1_l_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_left_tactical_laser2"
						{parameters "Voxels=0;"}
						{Position -0.00775373	0.143062	0.0224381}
						{bone "fx_laser_set_l_tactical_laser2"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.285218	0.71909	0.128101
							}
						}
						{bone "tactical_laser2_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-1.28567	-1.95337	0.0733166
							}
							{bone "tactical_laser2_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728844
								}
								{VolumeView "tactical_laser2_l_ui.ply"}
								{bone "tactical_laser2_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155178	0.00690603	-0.0026409
									}
									{VolumeView "tactical_laser2_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "tactical_laser2_l"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								-1	0	0
								0	0	1
								0.0183189	-0.704324	0.0984159
							}
							{visibility 0}
							{LODView
								{VolumeView "tactical_laser2_l.ply"}
								{VolumeView "tactical_laser2_l_lod1.ply"}
								{VolumeView "tactical_laser2_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_tactical_laser"
						{parameters "Voxels=0;"}
						{Position -0.00381064	0.143165	0.0208714}
						{bone "fx_laser_set_l_tactical_laser"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.152301	0.108199	0.314197
							}
						}
						{bone "tactical_laser_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-1.46495	-2.1763	0.528254
							}
							{bone "tactical_laser_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728843
								}
								{VolumeView "tactical_laser_l_ui.ply"}
								{bone "tactical_laser_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155175	0.00690603	-0.00264096
									}
									{VolumeView "tactical_laser_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "tactical_laser_l"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								1	0	0
								0	0	-1
								-0.0015409	-0.273533	0.121673
							}
							{visibility 0}
							{LODView
								{VolumeView "tactical_laser_l.ply"}
								{VolumeView "tactical_laser_l_lod1.ply"}
								{VolumeView "tactical_laser_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_zenitco"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.0119123	-0.246371	0.00650546
						}
						{bone "fx_laser_set_l_zenitco"
							{Matrix34
								-0.000180086	1	0
								0.00018032	0	-1
								-1	-0.000180095	-0.00018032
								-0.240631	0.909032	0.238452
							}
						}
						{bone "zenitco_l_ui_bone"
							{parameters "Voxels=0;"}
							{Position -1.06924	-1.62638	0.262127}
							{bone "zenitco_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									0.992291	1.6738	-0.0641887
								}
								{VolumeView "zenitco_l_ui.ply"}
								{bone "zenitco_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00136429	0.0740166	-0.14559
									}
									{VolumeView "zenitco_l_light_on_ui.ply"}
								}
								{bone "zenitco_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00136298	-0.109337	-0.14559
									}
									{VolumeView "zenitco_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_l_zenitco"
							{Matrix34
								-0.000180086	1	0
								0.00018032	0	-1
								-1	-0.000180095	-0.00018032
								0.00203109	0.894789	0.591056
							}
						}
						{bone "zenitco_l"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								-0.0268645	0.201735	0.463816
							}
							{visibility 0}
							{LODView
								{VolumeView "zenitco_l.ply"}
								{VolumeView "zenitco_l_lod1.ply"}
								{VolumeView "zenitco_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_laser5mw"
						{parameters "Voxels=0;"}
						{Position -0.00109065	-0.246129	0.0257645}
						{bone "fx_laser_set_l_laser5mw"
							{Matrix34
								0.00031568	1	0
								-1	0.000315683	-0.000311374
								-0.000311375	0	1
								-0.0772345	0.95786	0.212535
							}
						}
						{bone "laser5mw_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-1.16498	-1.46186	0.355537
							}
							{bone "laser5mw_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.1267	1.90051	-0.0728831
								}
								{VolumeView "laser5mw_l_ui.ply"}
								{bone "laser5mw_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00154912	0.0840425	-0.16531
									}
									{VolumeView "laser5mw_l_light_on_ui.ply"}
								}
								{bone "laser5mw_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00154757	-0.124147	-0.16531
									}
									{VolumeView "laser5mw_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_l_laser5mw"
							{Matrix34
								0.00031568	1	0
								-1	0.000315683	-0.000311374
								-0.000311375	0	1
								0.0222977	0.978122	0.356193
							}
						}
						{bone "laser5mw_l"
							{parameters "ID=body;"}
							{Matrix34
								0	1	-0.0006784
								1	0	0
								0	-0.0006784	-1
								0.000619769	0.274274	0.114983
							}
							{visibility 0}
							{LODView
								{VolumeView "laser5mw_l.ply"}
								{VolumeView "laser5mw_l_lod1.ply"}
								{VolumeView "laser5mw_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_laser1mw"
						{parameters "Voxels=0;"}
						{Position -0.00485337	-0.245705	0.0278979}
						{bone "fx_laser_set_l_laser1mw"
							{Matrix34
								0.00031568	1	0
								-1	0.000315684	0
								0	0	1
								0.00235939	0.546887	0.736134
							}
						}
						{bone "laser1mw_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-1.20459	-1.34988	0.413058
							}
							{bone "laser1mw_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.1267	1.90051	-0.0728831
								}
								{VolumeView "laser1mw_l_ui.ply"}
								{bone "laser1mw_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00154912	0.0840425	-0.16531
									}
									{VolumeView "laser1mw_l_light_on_ui.ply"}
								}
								{bone "laser1mw_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00154752	-0.124147	-0.16531
									}
									{VolumeView "laser1mw_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_l_laser1mw"
							{Matrix34
								0	1	0
								-1	0	0
								0	0	1
								0.00196886	1.30087	0.375586
							}
						}
						{bone "laser_1mw_l"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								1	0	0
								0	0	-1
								0.0039916	0.0593009	0.119441
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_1mw_l.ply"}
								{VolumeView "laser_1mw_l_lod1.ply"}
								{VolumeView "laser_1mw_l_lod2.ply"}
							}
						}
					}
					{bone "upgrade_left_flashlight_sf"
						{parameters "Voxels=0;"}
						{Position -0.00317097	0.174281	0.0177113}
						{bone "flashlight_sf_l"
							{parameters "ID=body;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	-1
								0.00047946	0	-7.87377e-05
							}
							{visibility 0}
							{LODView
								{VolumeView "flashlight_sf_l.ply"}
								{VolumeView "flashlight_sf_l_lod1.ply"}
								{VolumeView "flashlight_sf_l_lod2.ply"}
							}
						}
						{bone "fx_light_set_l_flashlight_sf"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00432014	1.163	0.522616
							}
						}
						{bone "flashlight_sf_l_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								1	0	0
								0	1	0
								0	0	1
								-1.43976	-1.54693	0.604362
							}
							{bone "flashlight_sf_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.41359	1.90051	-0.0728844
								}
								{VolumeView "flashlight_sf_l_ui.ply"}
								{bone "flashlight_sf_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00155181	0.00690603	-0.00264096
									}
									{VolumeView "flashlight_sf_l_light_on_ui.ply"}
								}
							}
						}
					}
					{bone "upgrade_left_peq10"
						{parameters "Voxels=0;"}
						{Position 0	-0.171692	0}
						{bone "fx_laser_set_l_peq10"
							{Matrix34
								-0.000180076	1	0
								0.00018032	0	-1
								-1	-0.0001801	-0.00018032
								-0.18001	0.933488	0.372343
							}
						}
						{bone "an_peq10_l"
							{parameters "ID=body;"}
							{Matrix34
								0	0	1
								0	1	0
								-1	0	0
								-0.00490212	-0.206711	0.103301
							}
							{visibility 0}
							{LODView
								{VolumeView "an_peq10_l.ply"}
								{VolumeView "an_peq10_l_lod1.ply"}
								{VolumeView "an_peq10_l_lod2.ply"}
							}
							{bone "caps_front_l"
								{parameters "ID=body;"}
								{Matrix34
									-0.0871569	0.996195	-5.83522e-05
									0.996194	0.087157	-5.77847e-05
									-5.2479e-05	-6.31665e-05	-1
									0.276555	0.946677	-0.00427365
								}
								{VolumeView "caps_front_l.ply"}
							}
						}
						{bone "peq10_l_ui_bone"
							{parameters "Voxels=0;"}
							{Position -1.13208	-1.84667	0.475874}
							{bone "peq10_l_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.1267	1.90051	-0.0728831
								}
								{VolumeView "peq10_l_ui.ply"}
								{bone "peq10_l_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0.00571888	0.999984	0
										1	0	0
										0.00155085	-0.00203705	-0.0116575
									}
									{VolumeView "peq10_l_light_on_ui.ply"}
								}
								{bone "peq10_l_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0.00571888	0.999984	0
										1	0	0
										0.00153953	-0.0116897	-0.0116597
									}
									{VolumeView "peq10_l_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_l_peq10"
							{Matrix34
								-0.000180076	1	0
								0.00018032	0	-1
								-1	-0.0001801	-0.00018032
								0.192871	0.933488	0.393828
							}
						}
					}