					{bone "upgrade_right_zenitco"
						{parameters "Voxels=0;"}
						{Position -0.00825894	-0.201512	-0.01486}
						{bone "fx_laser_set_r_zenitco"
							{Matrix34
								-0.000180075	1	0
								0.00018032	0	-1
								-1	-0.00018011	-0.00018032
								-0.241393	0.906387	0.239207
							}
						}
						{bone "zenitco_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.06858	1.69389	0.63168
							}
							{bone "zenitco_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									0.995432	1.6791	-0.064392
								}
								{VolumeView "zenitco_r_ui.ply"}
								{bone "zenitco_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00136864	0.0742512	-0.146051
									}
									{VolumeView "zenitco_r_light_on_ui.ply"}
								}
								{bone "zenitco_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00136727	-0.109684	-0.146051
									}
									{VolumeView "zenitco_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_r_zenitco"
							{Matrix34
								-0.000180075	1	0
								0.00018032	0	-1
								-1	-0.00018011	-0.00018032
								0.00203753	0.862767	0.592928
							}
						}
						{bone "zenitco_r"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								-0.0269498	0.202374	0.465285
							}
							{visibility 0}
							{LODView
								{VolumeView "zenitco_r.ply"}
								{VolumeView "zenitco_r_lod1.ply"}
								{VolumeView "zenitco_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_tactical_laser2"
						{parameters "Voxels=0;"}
						{Position -0.00561047	0.277398	-0.00370884}
						{bone "fx_laser_set_r_tactical_laser2"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.298707	0.753098	0.13416
							}
						}
						{bone "tactical_laser2_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.58259	2.04158	0.29283
							}
							{bone "tactical_laser2_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.48044	1.99039	-0.0763314
								}
								{VolumeView "tactical_laser2_r_ui.ply"}
								{bone "tactical_laser2_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162518	0.00723267	-0.00276577
									}
									{VolumeView "tactical_laser2_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "tactical_laser2_r"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								-1	0	0
								0	0	1
								0.0191853	-0.737635	0.10307
							}
							{visibility 0}
							{LODView
								{VolumeView "tactical_laser2_r.ply"}
								{VolumeView "tactical_laser2_r_lod1.ply"}
								{VolumeView "tactical_laser2_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_tactical_laser"
						{parameters "Voxels=0;"}
						{Position -0.00549674	0.224554	-0.00559953}
						{bone "fx_laser_set_r_tactical_laser"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.159504	0.113316	0.329056
							}
						}
						{bone "tactical_laser_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.58259	1.79857	0.659178
							}
							{bone "tactical_laser_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.48044	1.99039	-0.0763314
								}
								{VolumeView "tactical_laser_r_ui.ply"}
								{bone "tactical_laser_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162518	0.00723267	-0.00276577
									}
									{VolumeView "tactical_laser_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "tactical_laser_r"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								1	0	0
								0	0	-1
								-0.00161374	-0.286469	0.127427
							}
							{visibility 0}
							{LODView
								{VolumeView "tactical_laser_r.ply"}
								{VolumeView "tactical_laser_r_lod1.ply"}
								{VolumeView "tactical_laser_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_peq15"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.0449299	0.17696	-0.00110066
						}
						{bone "fx_light_set_r_peq15"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.388625	1.30043	0.275862
							}
						}
						{bone "fx_laser_set_r_peq15"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.34194	1.04801	0.247011
							}
						}
						{bone "caps_light_r"
							{parameters "ID=body;"}
							{Matrix34
								0	0.984808	0.173648
								0	0.173648	-0.984808
								-1	0	0
								-0.333154	0.922844	0.330058
							}
							{VolumeView "caps_light_r.ply"}
						}
						{bone "caps_laser_r"
							{parameters "ID=body;"}
							{Matrix34
								0	0	1
								-1	0	0
								0	-1	0
								0.309267	0.793493	0.329402
							}
							{VolumeView "caps_laser_r.ply"}
						}
						{bone "peq15_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.32972	1.83464	0.412993
							}
							{bone "peq15_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.25756	1.95607	-0.0750135
								}
								{VolumeView "peq15_r_ui.ply"}
								{bone "peq15_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00159544	0.00705624	-0.00405276
									}
									{VolumeView "peq15_r_light_on_ui.ply"}
								}
								{bone "peq15_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00158328	0.00678873	-0.00405276
									}
									{VolumeView "peq15_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "peq15_r"
							{parameters "ID=body;"}
							{Position 0.00923645	-0.0184426	-0.0292022}
							{visibility 0}
							{LODView
								{VolumeView "peq15_r.ply"}
								{VolumeView "peq15_r_lod1.ply"}
								{VolumeView "peq15_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_peq10"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.0045433	-0.0719433	-0.00484598
						}
						{bone "an_peq10_r"
							{parameters "ID=body;"}
							{Matrix34
								0	0	1
								0	1	0
								-1	0	0
								0.00479615	-0.204462	0.0815046
							}
							{visibility 0}
							{LODView
								{VolumeView "an_peq10_r.ply"}
								{VolumeView "an_peq10_r_lod1.ply"}
								{VolumeView "an_peq10_r_lod2.ply"}
							}
							{bone "caps_front_r"
								{parameters "ID=body;"}
								{Matrix34
									0.0871559	0.996195	0
									-0.996195	0.0871559	0
									0	0	1
									0.273328	0.935628	-0.00422835
								}
								{VolumeView "caps_front_r.ply"}
							}
						}
						{bone "fx_laser_set_r_peq10"
							{Matrix34
								0.000315676	1	0
								-1	0.000315679	-0.000311375
								-0.000311375	0	1
								-0.177909	0.922594	0.367998
							}
						}
						{bone "peq10_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.12068	1.67833	0.376645
							}
							{bone "peq10_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.11355	1.87833	-0.0720326
								}
								{VolumeView "peq10_r_ui.ply"}
								{bone "peq10_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.001531	0.0830617	-0.163381
									}
									{VolumeView "peq10_r_light_on_ui.ply"}
								}
								{bone "peq10_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00152946	-0.122698	-0.163381
									}
									{VolumeView "peq10_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_r_peq10"
							{Matrix34
								0.000315676	1	0
								-1	0.000315679	-0.000311375
								-0.000311375	0	1
								0.185274	0.922593	0.367997
							}
						}
					}
					{bone "upgrade_right_liner"
						{parameters "Voxels=0;"}
						{Position -0.000106215	0.0383153	0.00103363}
						{bone "fx_laser_set_r_liner"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0131959	1.32444	0.355671
							}
						}
						{bone "liner_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	1
								1.55031	-2.06154	0.548705
							}
							{bone "liner_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.42122	1.91078	-0.0732782
								}
								{VolumeView "liner_r_ui.ply"}
								{bone "liner_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00156015	0.00694323	-0.00265503
									}
									{VolumeView "liner_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "liner_r"
							{parameters "ID=body;"}
							{Matrix34
								0	0	-1
								0	1	0
								1	0	0
								-0.00769627	0.26011	-0.0221101
							}
							{visibility 0}
							{LODView
								{VolumeView "liner_r.ply"}
								{VolumeView "liner_r_lod1.ply"}
								{VolumeView "liner_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_lasercylinder4"
						{parameters "Voxels=0;"}
						{Position -0.00399899	0.154864	-9.91225e-05}
						{bone "lasercylinder4_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	1
								1.6149	-2.08288	0.383299
							}
							{bone "lasercylinder4_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.48044	1.99039	-0.0763313
								}
								{VolumeView "lasercylinder4_r_ui.ply"}
								{bone "lasercylinder4_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162518	0.00723267	-0.00276577
									}
									{VolumeView "lasercylinder4_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_laser_set_r_lasercylinder4"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00253797	0.83578	0.311827
							}
						}
						{bone "laser_rail_r_lasercylinder4"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0277319	-0.0537224	0.0482374
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_r_lasercylinder4.ply"}
								{VolumeView "laser_rail_r_lasercylinder4_lod1.ply"}
								{VolumeView "laser_rail_r_lasercylinder4_lod2.ply"}
							}
							{bone "lasercylinder4_r"
								{parameters "ID=body;"}
								{Position 0.270787	-0.267546	-0.025071}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder4_r.ply"}
									{VolumeView "lasercylinder4_r_lod1.ply"}
									{VolumeView "lasercylinder4_r_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_right_lasercylinder3"
						{parameters "Voxels=0;"}
						{Position -0.00505733	0.160191	-0.00362489}
						{bone "fx_laser_set_r_lasercylinder3"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00253797	0.730601	0.311827
							}
						}
						{bone "lasercylinder3_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	1
								1.61491	-2.08288	0.383299
							}
							{bone "lasercylinder3_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.48044	1.99039	-0.0763313
								}
								{VolumeView "lasercylinder3_r_ui.ply"}
								{bone "lasercylinder3_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162512	0.00723267	-0.00276577
									}
									{VolumeView "lasercylinder3_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser_rail_r_lasercylinder3"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0281566	-0.0537238	0.0502516
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_r_lasercylinder3.ply"}
								{VolumeView "laser_rail_r_lasercylinder3_lod1.ply"}
								{VolumeView "laser_rail_r_lasercylinder3_lod2.ply"}
							}
							{bone "lasercylinder3_r"
								{parameters "ID=body;"}
								{Position 0.242334	-0.262183	-0.0280893}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder3_r.ply"}
									{VolumeView "lasercylinder3_r_lod1.ply"}
									{VolumeView "lasercylinder3_r_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_right_lasercylinder1"
						{parameters "Voxels=0;"}
						{Position -0.00503409	0.162549	-3.43919e-05}
						{bone "fx_laser_set_r_lasercylinder1"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00849032	1.11781	0.308482
							}
						}
						{bone "lasercylinder1_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	1
								1.61491	-2.08288	0.383299
							}
							{bone "lasercylinder1_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.48044	1.99039	-0.0763313
								}
								{VolumeView "lasercylinder1_r_ui.ply"}
								{bone "lasercylinder1_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162512	0.00723267	-0.00276577
									}
									{VolumeView "lasercylinder1_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser_rail_r_lasercylinder1"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								-0.0284877	-0.0537233	0.0467058
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_rail_r_lasercylinder1.ply"}
								{VolumeView "laser_rail_r_lasercylinder1_lod1.ply"}
								{VolumeView "laser_rail_r_lasercylinder1_lod2.ply"}
							}
							{bone "lasercylinder1_r"
								{parameters "ID=body;"}
								{Position 0.250568	-0.261865	-0.0369309}
								{visibility 0}
								{LODView
									{VolumeView "lasercylinder1_r.ply"}
									{VolumeView "lasercylinder1_r_lod1.ply"}
									{VolumeView "lasercylinder1_r_lod2.ply"}
								}
							}
						}
					}
					{bone "upgrade_right_laser5mw"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.0364326	-0.341507	0.00660637
						}
						{bone "fx_light_set_r_laser5mw"
							{Matrix34
								0.000315678	1	0
								-1	0.000315683	-0.000311375
								-0.000311374	0	1
								0.0233523	1.02438	0.373039
							}
						}
						{bone "fx_laser_set_r_laser5mw"
							{Matrix34
								0.000315678	1	0
								-1	0.000315683	-0.000311375
								-0.000311374	0	1
								-0.0808871	1.00316	0.222586
							}
						}
						{bone "laser5mw_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.17772	2.40637	0.413711
							}
							{bone "laser5mw_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.17998	1.99039	-0.07633
								}
								{VolumeView "laser5mw_r_ui.ply"}
								{bone "laser5mw_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162238	0.0880175	-0.173128
									}
									{VolumeView "laser5mw_r_light_on_ui.ply"}
								}
								{bone "laser5mw_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00162071	-0.130018	-0.173128
									}
									{VolumeView "laser5mw_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "laser5mw_r"
							{parameters "ID=body;"}
							{Matrix34
								0	1	-0.000678402
								1	0	0
								0	-0.000678398	-1
								0.0306407	0.287245	0.116239
							}
							{visibility 0}
							{LODView
								{VolumeView "laser5mw_r.ply"}
								{VolumeView "laser5mw_r_lod1.ply"}
								{VolumeView "laser5mw_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_laser1mw"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.00223827	-0.26839	-0.000373989
						}
						{bone "fx_laser_set_r_laser1mw"
							{Matrix34
								0	1	0
								-1	0	0
								0	0	1
								0.00234687	0.543984	0.732227
							}
						}
						{bone "laser1mw_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.22573	2.10659	0.377785
							}
							{bone "laser1mw_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.12072	1.89042	-0.0724963
								}
								{VolumeView "laser1mw_r_ui.ply"}
								{bone "laser1mw_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.0015409	0.0835962	-0.164433
									}
									{VolumeView "laser1mw_r_light_on_ui.ply"}
								}
								{bone "laser1mw_r_laser_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.00153929	-0.123488	-0.164433
									}
									{VolumeView "laser1mw_r_laser_on_ui.ply"}
								}
							}
						}
						{bone "fx_light_set_r_laser1mw"
							{Matrix34
								0.000315676	1	0
								-1	0.000315682	-0.000311373
								-0.000311376	0	1
								0.00195837	1.29396	0.373592
							}
						}
						{bone "laser_1mw_r"
							{parameters "ID=body;"}
							{Matrix34
								0	1	0
								1	0	0
								0	0	-1
								0.0039705	0.0589857	0.118808
							}
							{visibility 0}
							{LODView
								{VolumeView "laser_1mw_r.ply"}
								{VolumeView "laser_1mw_r_lod1.ply"}
								{VolumeView "laser_1mw_r_lod2.ply"}
							}
						}
					}
					{bone "upgrade_right_flashlight_sf"
						{parameters "Voxels=0;"}
						{Matrix34
							1	0	0
							0	1	0
							0	0	1
							-0.00151622	0.249151	-0.00554857
						}
						{bone "fx_light_set_r_flashlight_sf"
							{parameters "Voxels=0;"}
							{Matrix34
								0	1	0
								0	0	-1
								-1	0	0
								0.00437951	1.17932	0.529948
							}
						}
						{bone "flashlight_sf_r_ui_bone"
							{parameters "Voxels=0;"}
							{Matrix34
								-1	0	0
								0	-1	0
								0	0	1
								1.50361	2.05523	0.2467
							}
							{bone "flashlight_sf_r_ui"
								{parameters "ID=body;"}
								{Matrix34
									0	0	1
									0	1	0
									-1	0	0
									1.43342	1.7287	-0.0739065
								}
								{VolumeView "flashlight_sf_r_ui.ply"}
								{bone "flashlight_sf_r_light_on_ui"
									{parameters "ID=body;"}
									{Matrix34
										0	0	-1
										0	1	0
										1	0	0
										0.0015735	0.00700283	-0.00267792
									}
									{VolumeView "flashlight_sf_r_light_on_ui.ply"}
								}
							}
						}
						{bone "flashlight_sf_r"
							{parameters "ID=body;"}
							{Matrix34
								-1	0	0
								0	1	0
								0	0	-1
								0	0	-0.000486463
							}
							{visibility 0}
							{LODView
								{VolumeView "flashlight_sf_r.ply"}
								{VolumeView "flashlight_sf_r_lod1.ply"}
								{VolumeView "flashlight_sf_r_lod2.ply"}
							}
						}
					}