	{on "armed_weapon"
		{if effector "stuff weapon pistol"
			{with_effector
				{delay 2
					{ani_play "armed" 0.3}
					{start_sound "weapon/armed/pistol_series/"}
				}
			}
		else effector "stuff weapon g36_series"
			{with_effector
				{delay 2.7
					{ani_play "armed" 1}
					{start_sound "weapon/armed/g36_series/"}
				}
			}
		else effector "stuff weapon sig_series"
			{with_effector
				{delay 2.5
					{ani_play "armed" 1}
					{start_sound "weapon/armed/sig_series/"}
				}
			}
		else effector "stuff weapon pp_series"
			{with_effector
				{delay 2.4
					{ani_play "armed" 1}
					{start_sound "weapon/armed/pp_series/"}
				}
			}
		else effector "stuff weapon mp7_series"
			{with_effector
				{delay 2.4
					{ani_play "armed" 1}
					{start_sound "weapon/armed/mp7_series/"}
				}
			}
		else effector "stuff weapon mp5_series"
			{with_effector
				{delay 2.4
					{ani_play "armed" 1}
					{start_sound "weapon/armed/mp5_series/"}
				}
			}
		else effector "stuff weapon ump_series"
			{with_effector
				{delay 2.4
					{ani_play "armed" 1}
					{start_sound "weapon/armed/ump_series/"}
				}
			}
		else effector "stuff weapon aug_series"
			{with_effector
				{delay 2.9
					{ani_play "armed" 1}
					{start_sound "weapon/armed/aug_series/"}
				}
			}
		else effector "stuff weapon ak_series"
			{with_effector
				{delay 2.9
					{ani_play "armed" 1}
					{start_sound "weapon/armed/ak_series/"}
				}
			}
		else effector "stuff weapon galil_series"
			{with_effector
				{delay 2.9
					{ani_play "armed" 1}
					{start_sound "weapon/armed/galil_series/"}
				}
			}
		else effector "stuff weapon m4a1_series"
			{with_effector
				{delay 2.9
					{ani_play "armed" 1}
					{start_sound "weapon/armed/m4a1_series/"}
				}
			}
		else effector "stuff weapon smg_series"
			{with_effector
				{delay 3.2
					{ani_play "armed" 1}
					{start_sound "weapon/armed/smg_series/"}
				}
			}
		else effector "stuff weapon aa12_series"
			{with_effector
				{delay 2.8
					{ani_play "armed" 1}
					{start_sound "weapon/armed/smg_series/"}
				}
			}
		else effector "stuff weapon mg_series"
			{with_effector
				{delay 3.6
					{ani_play "armed" 1}
					{start_sound "weapon/armed/mg_series/"}
				}
			}
		else effector "stuff weapon rpd_series"
			{with_effector
				{delay 6.2
					{ani_play "armed" 0.5}
					{start_sound "weapon/armed/rpd_series/"}
				}
			}
		else effector "stuff weapon mg36_series"
			{with_effector
				{delay 3.6
					{ani_play "armed" 1}
					{start_sound "weapon/armed/mg36_series/"}
				}
			}
		else effector "stuff weapon sniper_series"
			{with_effector
				{delay 3.6
					{ani_play "armed" 1}
					{start_sound "weapon/armed/snrifle_series/"}
				}
			}
		else effector "stuff weapon"
			{with_effector
				;{ani_play "armed" 1}
			}
		}
	}
