{if tagged "1_casing"
	{tags remove "1_casing"}
	{tags add "empty"}	
	{call "casing_clear"}
	{call "clear_shell"}
else tagged "2_casing"
	{tags remove "2_casing"}
	{tags add "1_casing"}
	{call "clear_shell"}
else tagged "3_casing"
	{tags remove "3_casing"}
	{tags add "2_casing"}
	{call "clear_shell"}
else tagged "4_casing"
	{tags remove "4_casing"}
	{tags add "3_casing"}
	{call "clear_shell"}
else tagged "5_casing"
	{tags remove "5_casing"}
	{tags add "4_casing"}
	{call "clear_shell"}
else tagged "6_casing"
	{tags remove "6_casing"}
	{tags add "5_casing"}
	{call "clear_shell"}
else tagged "7_casing"
	{tags remove "7_casing"}
	{tags add "6_casing"}
	{call "clear_shell"}
else tagged "8_casing"
	{tags remove "8_casing"}
	{tags add "7_casing"}
	{call "clear_shell"}
else tagged "9_casing"
	{tags remove "9_casing"}
	{tags add "8_casing"}
	{call "clear_shell"}
else tagged "10_casing"
	{tags remove "10_casing"}
	{tags add "9_casing"}
	{call "clear_shell"}
else tagged "11_casing"
	{tags remove "11_casing"}
	{tags add "10_casing"}
	{call "clear_shell"}
else tagged "12_casing"
	{tags remove "12_casing"}
	{tags add "11_casing"}
	{call "clear_shell"}
else tagged "13_casing"
	{tags remove "13_casing"}
	{tags add "12_casing"}
	{call "clear_shell"}
else tagged "14_casing"
	{tags remove "14_casing"}
	{tags add "13_casing"}
	{call "clear_shell"}
else tagged "15_casing"
	{tags remove "15_casing"}
	{tags add "14_casing"}
	{call "clear_shell"}
else tagged "16_casing"
	{tags remove "16_casing"}
	{tags add "15_casing"}
	{call "clear_shell"}
else tagged "17_casing"
	{tags remove "17_casing"}
	{tags add "16_casing"}
	{call "clear_shell"}
else tagged "18_casing"
	{tags remove "18_casing"}
	{tags add "17_casing"}
	{call "clear_shell"}
else tagged "19_casing"
	{tags remove "19_casing"}
	{tags add "18_casing"}
	{call "clear_shell"}
else tagged "20_casing"
	{tags remove "20_casing"}
	{tags add "19_casing"}
	{call "clear_shell"}
}