(define "cut_subpieces_wood"
	("cut_subpiece_wood" args 00)("cut_subpiece_wood" args 01)
	("cut_subpiece_wood" args 02)("cut_subpiece_wood" args 03)
	("cut_subpiece_wood" args 04)("cut_subpiece_wood" args 05)
	("cut_subpiece_wood" args 06)("cut_subpiece_wood" args 07)
	("cut_subpiece_wood" args 08)("cut_subpiece_wood" args 09)
	("cut_subpiece_wood" args 10)("cut_subpiece_wood" args 11)
	("cut_subpiece_wood" args 12)("cut_subpiece_wood" args 13)
	("cut_subpiece_wood" args 14)("cut_subpiece_wood" args 15)
	("cut_subpiece_wood" args 16)("cut_subpiece_wood" args 17)
	("cut_subpiece_wood" args 18)("cut_subpiece_wood" args 19)
	("cut_subpiece_wood" args 20)("cut_subpiece_wood" args 21)
	("cut_subpiece_wood" args 22)("cut_subpiece_wood" args 23)
	("cut_subpiece_wood" args 24)("cut_subpiece_wood" args 25)
	("cut_subpiece_wood" args 26)("cut_subpiece_wood" args 27)
	("cut_subpiece_wood" args 28)("cut_subpiece_wood" args 29)
	("cut_subpiece_wood" args 30)("cut_subpiece_wood" args 31)
	("cut_subpiece_wood" args 32)("cut_subpiece_wood" args 33)
	("cut_subpiece_wood" args 34)("cut_subpiece_wood" args 35)
	("cut_subpiece_wood" args 36)("cut_subpiece_wood" args 37)
	("cut_subpiece_wood" args 38)("cut_subpiece_wood" args 39)
	("cut_subpiece_wood" args 40)("cut_subpiece_wood" args 41)
	("cut_subpiece_wood" args 42)("cut_subpiece_wood" args 43)
	("cut_subpiece_wood" args 44)("cut_subpiece_wood" args 45)
	("cut_subpiece_wood" args 46)("cut_subpiece_wood" args 47)
	("cut_subpiece_wood" args 48)("cut_subpiece_wood" args 49)
	("cut_subpiece_wood" args 50)("cut_subpiece_wood" args 51)
	("cut_subpiece_wood" args 52)("cut_subpiece_wood" args 53)
	("cut_subpiece_wood" args 54)("cut_subpiece_wood" args 55)
	("cut_subpiece_wood" args 56)("cut_subpiece_wood" args 57)
	("cut_subpiece_wood" args 58)("cut_subpiece_wood" args 59)
	("cut_subpiece_wood" args 60)("cut_subpiece_wood" args 61)
	("cut_subpiece_wood" args 62)("cut_subpiece_wood" args 63)
	("cut_subpiece_wood" args 64)("cut_subpiece_wood" args 65)
	("cut_subpiece_wood" args 66)("cut_subpiece_wood" args 67)
	("cut_subpiece_wood" args 68)("cut_subpiece_wood" args 69)
	("cut_subpiece_wood" args 70)("cut_subpiece_wood" args 71)
	("cut_subpiece_wood" args 72)("cut_subpiece_wood" args 73)
	("cut_subpiece_wood" args 74)("cut_subpiece_wood" args 75)
	("cut_subpiece_wood" args 76)("cut_subpiece_wood" args 77)
	("cut_subpiece_wood" args 78)("cut_subpiece_wood" args 79)
	("cut_subpiece_wood" args 80)("cut_subpiece_wood" args 81)
	("cut_subpiece_wood" args 82)("cut_subpiece_wood" args 83)
	("cut_subpiece_wood" args 84)("cut_subpiece_wood" args 85)
	("cut_subpiece_wood" args 86)("cut_subpiece_wood" args 87)
	("cut_subpiece_wood" args 88)("cut_subpiece_wood" args 89)
	("cut_subpiece_wood" args 90)("cut_subpiece_wood" args 91)
	("cut_subpiece_wood" args 92)("cut_subpiece_wood" args 93)
	("cut_subpiece_wood" args 94)("cut_subpiece_wood" args 95)
	("cut_subpiece_wood" args 96)("cut_subpiece_wood" args 97)
	("cut_subpiece_wood" args 98)("cut_subpiece_wood" args 99)
	("cut_subpiece_wood" args 100)("cut_subpiece_wood" args 101)
	("cut_subpiece_wood" args 102)("cut_subpiece_wood" args 103)
	("cut_subpiece_wood" args 104)("cut_subpiece_wood" args 105)
	("cut_subpiece_wood" args 106)("cut_subpiece_wood" args 107)
	("cut_subpiece_wood" args 108)("cut_subpiece_wood" args 109)
	("cut_subpiece_wood" args 110)("cut_subpiece_wood" args 111)
	("cut_subpiece_wood" args 112)("cut_subpiece_wood" args 113)
	("cut_subpiece_wood" args 114)("cut_subpiece_wood" args 115)
	("cut_subpiece_wood" args 116)("cut_subpiece_wood" args 117)
	("cut_subpiece_wood" args 118)("cut_subpiece_wood" args 119)
	("cut_subpiece_wood" args 120)("cut_subpiece_wood" args 121)
	("cut_subpiece_wood" args 122)("cut_subpiece_wood" args 123)
	("cut_subpiece_wood" args 124)("cut_subpiece_wood" args 125)
	("cut_subpiece_wood" args 126)("cut_subpiece_wood" args 127)
	("cut_subpiece_wood" args 128)("cut_subpiece_wood" args 129)
	("cut_subpiece_wood" args 130)("cut_subpiece_wood" args 131)
	("cut_subpiece_wood" args 132)("cut_subpiece_wood" args 133)
	("cut_subpiece_wood" args 134)("cut_subpiece_wood" args 135)
	("cut_subpiece_wood" args 136)("cut_subpiece_wood" args 137)
	("cut_subpiece_wood" args 138)("cut_subpiece_wood" args 139)
	("cut_subpiece_wood" args 140)("cut_subpiece_wood" args 141)
	("cut_subpiece_wood" args 142)("cut_subpiece_wood" args 143)
	("cut_subpiece_wood" args 144)("cut_subpiece_wood" args 145)
	("cut_subpiece_wood" args 146)("cut_subpiece_wood" args 147)
	("cut_subpiece_wood" args 148)("cut_subpiece_wood" args 149)
	("cut_subpiece_wood" args 150)("cut_subpiece_wood" args 151)
	("cut_subpiece_wood" args 152)("cut_subpiece_wood" args 153)
	("cut_subpiece_wood" args 154)("cut_subpiece_wood" args 155)
	("cut_subpiece_wood" args 156)("cut_subpiece_wood" args 157)
	("cut_subpiece_wood" args 158)("cut_subpiece_wood" args 159)
	("cut_subpiece_wood" args 160)("cut_subpiece_wood" args 161)
	("cut_subpiece_wood" args 162)("cut_subpiece_wood" args 163)
	("cut_subpiece_wood" args 164)("cut_subpiece_wood" args 165)
	("cut_subpiece_wood" args 166)("cut_subpiece_wood" args 167)
	("cut_subpiece_wood" args 168)("cut_subpiece_wood" args 169)
	("cut_subpiece_wood" args 170)("cut_subpiece_wood" args 171)
	("cut_subpiece_wood" args 172)("cut_subpiece_wood" args 173)
	("cut_subpiece_wood" args 174)("cut_subpiece_wood" args 175)
	("cut_subpiece_wood" args 176)("cut_subpiece_wood" args 177)
	("cut_subpiece_wood" args 178)("cut_subpiece_wood" args 179)
	("cut_subpiece_wood" args 180)("cut_subpiece_wood" args 181)
	("cut_subpiece_wood" args 182)("cut_subpiece_wood" args 183)
	("cut_subpiece_wood" args 184)("cut_subpiece_wood" args 185)
	("cut_subpiece_wood" args 186)("cut_subpiece_wood" args 187)
	("cut_subpiece_wood" args 188)("cut_subpiece_wood" args 189)
	("cut_subpiece_wood" args 190)("cut_subpiece_wood" args 191)
	("cut_subpiece_wood" args 192)("cut_subpiece_wood" args 193)
	("cut_subpiece_wood" args 194)("cut_subpiece_wood" args 195)
	("cut_subpiece_wood" args 196)("cut_subpiece_wood" args 197)
	("cut_subpiece_wood" args 198)("cut_subpiece_wood" args 199)
	("cut_subpiece_wood" args 200)("cut_subpiece_wood" args 201)
	("cut_subpiece_wood" args 202)("cut_subpiece_wood" args 203)
	("cut_subpiece_wood" args 204)("cut_subpiece_wood" args 205)
	("cut_subpiece_wood" args 206)("cut_subpiece_wood" args 207)
	("cut_subpiece_wood" args 208)("cut_subpiece_wood" args 209)
)





{"crushed_steel"
	{on ground_hit
		{if volume "tear" 
			{volumes disable contact }
			{delay 0.01
				{volumes enable contact }
			}
			{if contact_velocity 20
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 0.1}
				}
			else contact_velocity 5
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.1}
					}
				}
			}	
		}	
		{if volume "part" 
			{volumes disable contact }
			{delay 0.01
				{volumes enable contact }
			}
			{if contact_velocity 20
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 0.1}
				}
			else contact_velocity 5
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.1}
					}
				}
			}	
		}
		{if volume "end_crush" 
			{delete}
		}	
	}
	{on contact
		{if volume "end_crush" 
			{delete}
		}	
		{if volume "tear" 
			{if contact_velocity 20
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 0.1}
				}
			else contact_velocity 5
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.1}
					}
				}
			}	
		}	
		{if volume "part" 
			{if contact_velocity 20
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 0.1}
				}
			else contact_velocity 5
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.1}
					}
				}
			}	
		}	
	}	
	{on blast
		{if volume "end_crush" 
			{delete}
		}	
		{if volume "tear" 
			{tear "piece_medium_steel_crushed" bone from_volume
				{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
			}
		}	
		{if volume "part" 
			{tear "piece_medium_steel_crushed" bone from_volume
				{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
			}
		}	
		{if volume "armor_tear" 
			{tear "piece_medium_steel_crushed" bone from_volume
				{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
			}
		}	
	}	
	{on pierce
		{if volume "armor_tear" 
			{tear "piece_medium_steel_crushed" bone from_volume
				{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
			}
		}	
		{if volume "tear" 
			{if stuff "bullet big"
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
				}
			else stuff "shell"
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 1 dir 10 cx 5 cy 5 }
				}
			else stuff "bullet"
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.5 dir 1.5 cx 1 cy 1 rnd_dir 3 no_position}
					}
				}
			}	
		}	
		{if volume "wood" 
			{if stuff "bullet big"
				{tear "piece_small_wood" bone from_volume
					{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
				}
			else stuff "shell"
				{tear "piece_small_wood" bone from_volume
					{impulse up 1 dir 10 cx 5 cy 5 }
				}
			else stuff "bullet"
				{if rand 0.5
					{tear "piece_small_wood" bone from_volume
						{impulse up 0.5 dir 1.5 cx 1 cy 1 rnd_dir 3 no_position}
					}
				}
			}	
		}	
		{if volume "part" 
			{if stuff "bullet big"
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 2 1 dir 3 1 cx 2 1 cy 2 1 rnd_dir 3 no_position}
				}
			else stuff "shell"
				{tear "piece_medium_steel_crushed" bone from_volume
					{impulse up 1 dir 10 cx 5 cy 5 }
				}
			else stuff "bullet"
				{if rand 0.5
					{tear "piece_medium_steel_crushed" bone from_volume
						{impulse up 0.5 dir 1.5 cx 1 cy 1 rnd_dir 3 no_position}
					}
				}
			}	
		}	
	}	
}	
{"small_wood_destroy"
	{on spawn
		{spawn "wood_destroy_small"} {delete}
		;{tear "piece_small_wood" bone from_volume
		;	{impulse up 0}
		;}	
	}
}

{"small_wood_crushed"
	{inflammation_time 10}
	{on "burn_volume"
		{if not "burned"
			{set "burned" 1}
			{burn volume fx "smoke_wood_small_fire" time 14 fake even_law}	
			{fire volume "wood" radius 0.1 heating 2  time 60 follow}
			{tex_morph "burned" 1}
		}
	}
	{on spawn
		{volumes disable contact blast}
		{delay 0.5
			{volumes enable contact blast}
		}
	}
	{on ground_hit
		{volumes disable contact }
		{delay 0.1
			{volumes enable contact }
		}
		(define "cut_subpiece_wood"
			{if contact_velocity 5
				{tear "piece_small_wood" bone "wood_plank_down_%0" 
					{impulse up 2 1 cx  1 0.5}
				}
			else contact_velocity 1
				{tear "piece_small_wood" bone "wood_plank_down_%0" 
					{impulse up 0.5 cx 0.2}
				}
			}
		)
		("cut_subpieces_wood")
	}	
	; {on contact
		; {volumes disable contact }
		; {delay 0.1
			; {volumes enable contact }
		; }
		; (define "cut_subpiece_wood"
			; {if rand 0.6
				; {tear "piece_small_wood" bone "wood_plank_down_%0" 
					; {impulse dir 2 1}
				; }
			; else rand 0.2
				; {tear "piece_medium_wood_destroy" bone from_volume
				; }
			; }
		; )
		; ("cut_subpieces_wood")
	; }	
	{on pierce
		(define "cut_subpiece_wood"
			{if rand 0.6
				{tear "piece_small_wood" bone "wood_plank_down_%0" 
					{impulse up 2 1 dir 2 1 cx 2 1}
				}
			else rand 0.2
				{tear "piece_medium_wood_destroy" bone from_volume
				}
			}
		)
		("cut_subpieces_wood")
	}	
}	
;-----end particle
{"crusher_wood"
	{inflammation_time 3}
	{on "burn"
		{if not burned
			{call "burn_volume"}
		}
	}
	{on "match"
		{if rand 0.1
			{if not "burned"
				{set "burned" 1}
				{call "_burns"}
			}
		}
	}
	{on "burn_volume"
		{if not "burned"
			{set "burned" 1}
			{call "_burns"}
		}
	}
	{on "_burns"
		{start_sound "fire/small"}
		{fire radius 0.3 time 40 heating 3}
		{burn volume fx "smoke_dead_norm" time 37 fake even_law}
		{fire volume "part" radius 0.9 heating 1  time 15 follow}
		{burn volume fx "smoke_camp_storeable" time 54 fake even_law}
		{delay 8 2 "burn_die1"
			{tex_morph "d" 5}
			{call "_burn_crash"}
			{delay 6 "_burn_crash_end"
				{call "_burn_crash_end"}
			}
			{delay 12 3 "burn_die2"
				{call "_burn_crash"}
				{delay 16 2 "burn_die3"
					{tex_morph "b" 12}
					{call "_burn_crash"}
				}
			}
		}
	}
	{on "_burn_crash"
		{start_sound "crush/small/wood/"}
		(define "_burn_crash"
			{if rand %1
				{tear "piece_small_wood" bone %0
					{impulse up 0.3 dir 0.3}
				}
			}
		)	
		("_burn_crash" args "plank00"			0.7)
		("_burn_crash" args "plank01"			0.4)
		("_burn_crash" args "plank02"			0.4)
		("_burn_crash" args "plank03"			0.4)
		("_burn_crash" args "plank04"			0.4)
		("_burn_crash" args "plank05"			0.4)
		("_burn_crash" args "plank06"			0.4)
		("_burn_crash" args "plank07"			0.4)
		("_burn_crash" args "wood01"			0.4)
		("_burn_crash" args "railing"			0.2)
		("_burn_crash" args "railing00"			0.2)
		("_burn_crash" args "railing01"			0.2)
		("_burn_crash" args "railing02"			0.2)
	}
	{on "_burn_crash_end"
		{delay 18
			{start_sound "crush/small/wood/"}
			(define "_burn_crash"
				{if rand %1
					{tear "piece_small_wood" bone %0
						{impulse up 0.3 dir 0.3}
					}
				}
			)	
			("_burn_crash" args "plank00"			0.7)
			("_burn_crash" args "plank01"			0.7)
			("_burn_crash" args "plank02"			0.7)
			("_burn_crash" args "plank03"			0.7)
			("_burn_crash" args "plank04"			0.7)
			("_burn_crash" args "plank05"			0.7)
			("_burn_crash" args "plank06"			0.7)
			("_burn_crash" args "plank07"			0.7)
			("_burn_crash" args "wood01"			0.7)
		}
	}
	{on break_armor
	}
	{on contact
		{if effector "fraction" 
			{if contact_velocity 2
				{start_sound "crush/small/wood/"}
				{impulse up 2 1 dir 2 1}
				(define "cut_part"
					{if rand %2
						{if volume %1
							{tear "piece_small_wood" bone %0
								{impulse up 8 1 dir 2 1}
							}
						else volume "body"
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				)	
				("cut_part" args "wood01"		"wood01"			0.7)
				("cut_part" args "plank00"		"plank00"			0.7)
				("cut_part" args "plank01"		"plank01"			0.7)
				("cut_part" args "plank02"		"plank02"			0.7)
				("cut_part" args "plank03"		"plank03"			0.7)
				("cut_part" args "plank04"		"plank04"			0.7)
				("cut_part" args "plank05"		"plank05"			0.7)
				("cut_part" args "plank06"		"plank06"			0.7)
				("cut_part" args "plank07"		"plank07"			0.7)
			}
		else effector "vehicle" 
			{if contact_velocity 2
				(define "cut_part"
					{if rand %2
						{if volume %1
							{tear "piece_small_wood" bone %0
								{impulse up 4 1 dir 2 1}
							}
						}
					}
				)	
				("cut_part" args "wood01"		"wood01"			0.7)
				("cut_part" args "plank00"		"plank00"			0.7)
				("cut_part" args "plank01"		"plank01"			0.7)
				("cut_part" args "plank02"		"plank02"			0.7)
				("cut_part" args "plank03"		"plank03"			0.7)
				("cut_part" args "plank04"		"plank04"			0.7)
				("cut_part" args "plank05"		"plank05"			0.7)
				("cut_part" args "plank06"		"plank06"			0.7)
				("cut_part" args "plank07"		"plank07"			0.7)
			}
		}
	}
	{on blast_hit overload sync 
		{start_sound "crush/small/wood/"}
		{if stuff "grenade fg"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 5 2 dir 5 2 cx 5 2 cy 5 2 rnd_dir 10 no_position}
						}
					else volume "body"
						{set "end_stage" 1}
						{call "end_stage"}

					}
				}
			)	
			("cut_part" args "wood01"		"wood01"			0.8)
			("cut_part" args "plank00"		"plank00"			0.8)
			("cut_part" args "plank01"		"plank01"			0.8)
			("cut_part" args "plank02"		"plank02"			0.8)
			("cut_part" args "plank03"		"plank03"			0.8)
			("cut_part" args "plank04"		"plank04"			0.8)
			("cut_part" args "plank05"		"plank05"			0.8)
			("cut_part" args "plank06"		"plank06"			0.8)
			("cut_part" args "plank07"		"plank07"			0.8)
		else min_energy 2
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 5 2 dir 5 2 cx 5 2 cy 5 2 rnd_dir 10 no_position}
				}
			)
			("cut_part" args "wood01"		"wood01" )
			("cut_part" args "plank00"		"plank00" )
			("cut_part" args "plank01"		"plank01" )
			("cut_part" args "plank02"		"plank02" )
			("cut_part" args "plank03"		"plank03" )
			("cut_part" args "plank04"		"plank04" )
			("cut_part" args "plank05"		"plank05" )
			("cut_part" args "plank06"		"plank06" )
			("cut_part" args "plank07"		"plank07" )
		else min_energy 1
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 6 4 dir 4 1}
						}
					else volume "body"
						{set "end_stage" 1}
						{call "end_stage"}

					}
				}
			)	
			("cut_part" args "wood01"		"wood01"			0.8)
			("cut_part" args "plank00"		"plank00"			0.8)
			("cut_part" args "plank01"		"plank01"			0.8)
			("cut_part" args "plank02"		"plank02"			0.8)
			("cut_part" args "plank03"		"plank03"			0.8)
			("cut_part" args "plank04"		"plank04"			0.8)
			("cut_part" args "plank05"		"plank05"			0.8)
			("cut_part" args "plank06"		"plank06"			0.8)
			("cut_part" args "plank07"		"plank07"			0.8)
		}
	}
	{on ground_hit
		{if min_speed 40
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 5 2 dir 5 2 cx 5 2 cy 5 2 rnd_dir 10 no_position}
				}
			)
			("cut_part" args "wood01"		"wood01" )
			("cut_part" args "piece01"		"piece01" )
			("cut_part" args "plank00"		"plank00" )
			("cut_part" args "plank01"		"plank01" )
			("cut_part" args "plank02"		"plank02" )
			("cut_part" args "plank03"		"plank03" )
			("cut_part" args "plank04"		"plank04" )
			("cut_part" args "plank05"		"plank05" )
			("cut_part" args "plank06"		"plank06" )
			("cut_part" args "plank07"		"plank07" )
			("cut_part" args "railing"		"railing" )
			("cut_part" args "railing00"	"railing00" )
			("cut_part" args "railing01"	"railing01" )
			("cut_part" args "railing02"	"railing02" )
		}
	}
	{on bullet_hit	
		{if stuff "grenade fg"
			{start_sound "crush/small/wood/"}
			{bullet_detonate}
		}
	}
	{on pierce
		{if stuff "fg"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{spawn "wood_crush_small" %0}
						{tear "piece_small_wood" bone %0
							{impulse up 12 1 dir 18 1}
						}
					else volume "body"
						{if rand 0.7
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				}
			)	
			("cut_part" args "wood01"			"wood01"			0.8)
			("cut_part" args "plank00"			"plank00"			0.8)
			("cut_part" args "plank01"			"plank01"			0.8)
			("cut_part" args "plank02"			"plank02"			0.8)
			("cut_part" args "plank03"			"plank03"			0.8)
			("cut_part" args "plank04"			"plank04"			0.8)
			("cut_part" args "plank05"			"plank05"			0.8)
			("cut_part" args "plank06"			"plank06"			0.8)
			("cut_part" args "plank07"			"plank07"			0.8)
			("cut_part" args "railing"			"railing"			0.01)
			("cut_part" args "railing01"		"railing01"			0.01)
			("cut_part" args "railing02"		"railing02"			0.01)
		else stuff "zenite"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 5 2 dir 4 2}
						}
					else volume "body"
						{if rand 0.7
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				}
			)	
			("cut_part" args "wood01"			"wood01"			0.8)
			("cut_part" args "plank00"			"plank00"			0.8)
			("cut_part" args "plank01"			"plank01"			0.8)
			("cut_part" args "plank02"			"plank02"			0.8)
			("cut_part" args "plank03"			"plank03"			0.8)
			("cut_part" args "plank04"			"plank04"			0.8)
			("cut_part" args "plank05"			"plank05"			0.8)
			("cut_part" args "plank06"			"plank06"			0.8)
			("cut_part" args "plank07"			"plank07"			0.8)
			("cut_part" args "railing"			"railing"			0.01)
			("cut_part" args "railing01"		"railing01"			0.01)
			("cut_part" args "railing02"		"railing02"			0.01)
		else stuff "bullet"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 2 1 dir 2 1}
						}
					else volume "body"
						{if rand 0.2
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				}
			)	
			("cut_part" args "wood01"			"wood01"			0.3)
			("cut_part" args "plank00"			"plank00"			0.3)
			("cut_part" args "plank01"			"plank01"			0.3)
			("cut_part" args "plank02"			"plank02"			0.3)
			("cut_part" args "plank03"			"plank03"			0.3)
			("cut_part" args "plank04"			"plank04"			0.3)
			("cut_part" args "plank05"			"plank05"			0.3)
			("cut_part" args "plank06"			"plank06"			0.3)
			("cut_part" args "plank07"			"plank07"			0.3)
			("cut_part" args "railing"			"railing"			0.01)
			("cut_part" args "railing01"		"railing01"			0.01)
			("cut_part" args "railing02"		"railing02"			0.01)
		}
	}
	{on "end_stage"
		{if "end_stage"
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 0.8 dir 0.3 0.1}
				}
			)
			("cut_part" args "wood01"		"wood01" )
			("cut_part" args "plank00"		"plank00" )
			("cut_part" args "plank01"		"plank01" )
			("cut_part" args "plank02"		"plank02" )
			("cut_part" args "plank03"		"plank03" )
			("cut_part" args "plank04"		"plank04" )
			("cut_part" args "plank05"		"plank05" )
			("cut_part" args "plank06"		"plank06" )
			("cut_part" args "plank07"		"plank07" )
		}
	}
	{on break
		{if component "body"
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 8.2 dir 0.3 0.1}
				}
			)
			("cut_part" args "wood01"		"wood01" )
			("cut_part" args "plank00"		"plank00" )
			("cut_part" args "plank01"		"plank01" )
			("cut_part" args "plank02"		"plank02" )
			("cut_part" args "plank03"		"plank03" )
			("cut_part" args "plank04"		"plank04" )
			("cut_part" args "plank05"		"plank05" )
			("cut_part" args "plank06"		"plank06" )
			("cut_part" args "plank07"		"plank07" )

		}
	}
}


{"crusher_wood_tagged"
	{inflammation_time 3}
	{on "burn"
		{if not burned
			{call "burn_volume"}
		}
	}
	{on "burn_volume"
		{if not "burned"
			{set "burned" 1}
			{call "_burns"}
		}
	}
	{on "_burns"
		{start_sound "fire/small"}
		{fire radius 0.3 time 40 heating 3}
		{burn volume fx "smoke_dead_norm" time 37 fake even_law}
		{burn volume fx "smoke_camp_storeable" time 54 fake even_law}
		{delay 8 2 "burn_die1"
			{tex_morph "d" 5}
			{call "_burn_crash"}
			{delay 6 "_burn_crash_end"
				{call "_burn_crash_end"}
			}
			{delay 12 3 "burn_die2"
				{call "_burn_crash"}
				{delay 16 2 "burn_die3"
					{tex_morph "b" 12}
					{call "_burn_crash"}
				}
			}
		}
	}
	{on "_burn_crash"
		{start_sound "crush/small/wood/"}
		(define "_burn_crash"
			{if rand %1
				{tear "piece_small_wood" bone %0
					{impulse up 0.3 dir 0.3}
				}
			}
		)	
		("_burn_crash" args "wood00"					0.4)
		("_burn_crash" args "wood01"					0.4)
		("_burn_crash" args "wood02"					0.4)
		("_burn_crash" args "wood03"					0.4)
		("_burn_crash" args "wood04"					0.4)
		("_burn_crash" args "wood05"					0.4)
		("_burn_crash" args "wood06"					0.4)
		("_burn_crash" args "wood07"					0.4)
		("_burn_crash" args "wood08"					0.4)
		("_burn_crash" args "wood09"					0.4)
		("_burn_crash" args "wood10"					0.4)
		("_burn_crash" args "wood11"					0.4)
		("_burn_crash" args "wood12"					0.4)
		("_burn_crash" args "wood13"					0.4)
		("_burn_crash" args "wood14"					0.4)
		("_burn_crash" args "wood15"					0.4)
		("_burn_crash" args "wood16"					0.4)
		("_burn_crash" args "wood17"					0.4)
		("_burn_crash" args "wood18"					0.4)
		("_burn_crash" args "wood19"					0.4)
		("_burn_crash" args "wood20"					0.4)
		("_burn_crash" args "rack00"					0.4)
		("_burn_crash" args "rack01"					0.4)
		("_burn_crash" args "piece00"					0.4)
		("_burn_crash" args "piece01"					0.4)
	}
	{on "_burn_crash_end"
		{delay 18
		{start_sound "crush/small/wood/"}
		(define "_burn_crash"
			{if rand %1
				{tear "piece_small_wood" bone %0
					{impulse up 0.3 dir 0.3}
				}
			}
		)	
		("_burn_crash" args "wood00"					0.7)
		("_burn_crash" args "wood01"					0.7)
		("_burn_crash" args "wood02"					0.7)
		("_burn_crash" args "wood03"					0.7)
		("_burn_crash" args "wood04"					0.7)
		("_burn_crash" args "wood05"					0.7)
		("_burn_crash" args "wood06"					0.7)
		("_burn_crash" args "wood07"					0.7)
		("_burn_crash" args "wood08"					0.7)
		("_burn_crash" args "wood09"					0.7)
		("_burn_crash" args "wood10"					0.7)
		("_burn_crash" args "wood11"					0.7)
		("_burn_crash" args "wood12"					0.7)
		("_burn_crash" args "wood13"					0.7)
		("_burn_crash" args "wood14"					0.7)
		("_burn_crash" args "wood15"					0.7)
		("_burn_crash" args "wood16"					0.7)
		("_burn_crash" args "wood17"					0.7)
		("_burn_crash" args "wood18"					0.7)
		("_burn_crash" args "wood19"					0.7)
		("_burn_crash" args "wood20"					0.7)
		("_burn_crash" args "rack00"					0.7)
		("_burn_crash" args "rack01"					0.7)
		("_burn_crash" args "piece00"					0.7)
		("_burn_crash" args "piece01"					0.7)
	}
	}
	{on contact
		{if effector "fraction" 
			{start_sound "crush/small/wood/"}
			{impulse up 2 1 dir 2 1}
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 4 dir 2 1}
						}
					}
				}
			)	
			("cut_part" args "wood00"			"wood00"			0.7)
			("cut_part" args "wood01"			"wood01"			0.7)
			("cut_part" args "wood02"			"wood02"			0.7)
			("cut_part" args "wood03"			"wood03"			0.7)
			("cut_part" args "wood04"			"wood04"			0.7)
			("cut_part" args "wood05"			"wood05"			0.7)
			("cut_part" args "wood06"			"wood06"			0.7)
			("cut_part" args "wood07"			"wood07"			0.7)
			("cut_part" args "wood08"			"wood08"			0.7)
			("cut_part" args "wood09"			"wood09"			0.7)
			("cut_part" args "wood10"			"wood10"			0.7)
			("cut_part" args "wood11"			"wood11"			0.7)
			("cut_part" args "wood12"			"wood12"			0.7)
			("cut_part" args "wood13"			"wood13"			0.7)
			("cut_part" args "wood14"			"wood14"			0.7)
			("cut_part" args "wood15"			"wood15"			0.7)
			("cut_part" args "wood16"			"wood16"			0.7)
			("cut_part" args "wood17"			"wood17"			0.7)
			("cut_part" args "wood18"			"wood18"			0.7)
			("cut_part" args "wood19"			"wood19"			0.7)
			("cut_part" args "wood20"			"wood20"			0.7)
			("cut_part" args "rack00"			"rack00"			0.7)
			("cut_part" args "rack01"			"rack01"			0.7)
			("cut_part" args "piece00"			"piece00"			0.7)
			("cut_part" args "piece01"			"piece01"			0.7)
		}
		{if min_speed 15
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 1 dir 1}
						}
					}
				}
			)	
			("cut_part" args "wood00"			"wood00"			0.7)
			("cut_part" args "wood01"			"wood01"			0.7)
			("cut_part" args "wood02"			"wood02"			0.7)
			("cut_part" args "wood03"			"wood03"			0.7)
			("cut_part" args "wood04"			"wood04"			0.7)
			("cut_part" args "wood05"			"wood05"			0.7)
			("cut_part" args "wood06"			"wood06"			0.7)
			("cut_part" args "wood07"			"wood07"			0.7)
			("cut_part" args "wood08"			"wood08"			0.7)
			("cut_part" args "wood09"			"wood09"			0.7)
			("cut_part" args "wood10"			"wood10"			0.7)
			("cut_part" args "wood11"			"wood11"			0.7)
			("cut_part" args "wood12"			"wood12"			0.7)
			("cut_part" args "wood13"			"wood13"			0.7)
			("cut_part" args "wood14"			"wood14"			0.7)
			("cut_part" args "wood15"			"wood15"			0.7)
			("cut_part" args "wood16"			"wood16"			0.7)
			("cut_part" args "wood17"			"wood17"			0.7)
			("cut_part" args "wood18"			"wood18"			0.7)
			("cut_part" args "wood19"			"wood19"			0.7)
			("cut_part" args "wood20"			"wood20"			0.7)
			("cut_part" args "rack00"			"rack00"			0.7)
			("cut_part" args "rack01"			"rack01"			0.7)
			("cut_part" args "piece00"			"piece00"			0.7)
			("cut_part" args "piece01"			"piece01"			0.7)
		}
	}
	{on ground_hit
		{if min_speed 80
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 0 dir 0 }
				}
			)
				("cut_part" args "wood00"			"wood00"		)
				("cut_part" args "wood01"			"wood01"		)
				("cut_part" args "wood02"			"wood02"		)
				("cut_part" args "wood03"			"wood03"		)
				("cut_part" args "wood04"			"wood04"		)
				("cut_part" args "wood05"			"wood05"		)
				("cut_part" args "wood06"			"wood06"	)
				("cut_part" args "wood07"			"wood07"		)
				("cut_part" args "wood08"			"wood08"		)
				("cut_part" args "wood09"			"wood09"			)
				("cut_part" args "wood10"			"wood10"		)
				("cut_part" args "wood11"			"wood11"		)
				("cut_part" args "wood12"			"wood12"			)
				("cut_part" args "wood13"			"wood13"			)
				("cut_part" args "wood14"			"wood14"			)
				("cut_part" args "wood15"			"wood15"			)
				("cut_part" args "wood16"			"wood16"			)
				("cut_part" args "wood17"			"wood17"			)
				("cut_part" args "wood18"			"wood18"			)
				("cut_part" args "wood19"			"wood19"			)
				("cut_part" args "wood20"			"wood20"			)
				("cut_part" args "railing00"			"railing00"			)
				("cut_part" args "railing01"			"railing01"			)
				("cut_part" args "railing02"			"railing02"			)
				("cut_part" args "rack00"			"rack00"			 )
				("cut_part" args "rack01"			"rack01"			 )
				("cut_part" args "piece00"			"piece00"			)
				("cut_part" args "piece01"			"piece01"			 )
		}
	}
	{on blast_hit
		{if min_energy 10
			(define "cut_part"
				{tear "piece_small_wood" bone %0
					{impulse up 5 2 dir 5 2 cx 5 2 cy 5 2 rnd_dir 10 no_position}
				}
			)
			("cut_part" args "wood00"			"wood00" )
			("cut_part" args "wood01"			"wood01" )
			("cut_part" args "wood02"			"wood02" )
			("cut_part" args "wood03"			"wood03" )
			("cut_part" args "wood04"			"wood04" )
			("cut_part" args "wood05"			"wood05" )
			("cut_part" args "wood06"			"wood06" )
			("cut_part" args "wood07"			"wood07" )
			("cut_part" args "wood08"			"wood08" )
			("cut_part" args "wood09"			"wood09" )
			("cut_part" args "wood10"			"wood10" )
			("cut_part" args "wood11"			"wood11" )
			("cut_part" args "wood12"			"wood12" )
			("cut_part" args "wood13"			"wood13" )
			("cut_part" args "wood14"			"wood14" )
			("cut_part" args "wood15"			"wood15" )
			("cut_part" args "wood16"			"wood16" )
			("cut_part" args "wood17"			"wood17" )
			("cut_part" args "wood18"			"wood18" )
			("cut_part" args "wood19"			"wood19" )
			("cut_part" args "wood20"			"wood20" )
			("cut_part" args "rack00"			"rack00" )
			("cut_part" args "rack01"			"rack01" )
			("cut_part" args "piece00"			"piece00" )
			("cut_part" args "piece01"			"piece01" )
		else min_energy 4
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 6 4 dir 4 1}
						}
					else volume "body"
						{set "end_stage" 1}
						{call "end_stage"}

					}
				}
			)	
			("cut_part" args "wood00"			"wood00"			0.7)
			("cut_part" args "wood01"			"wood01"			0.7)
			("cut_part" args "wood02"			"wood02"			0.7)
			("cut_part" args "wood03"			"wood03"			0.7)
			("cut_part" args "wood04"			"wood04"			0.7)
			("cut_part" args "wood05"			"wood05"			0.7)
			("cut_part" args "wood06"			"wood06"			0.7)
			("cut_part" args "wood07"			"wood07"			0.7)
			("cut_part" args "wood08"			"wood08"			0.7)
			("cut_part" args "wood09"			"wood09"			0.7)
			("cut_part" args "wood10"			"wood10"			0.7)
			("cut_part" args "wood11"			"wood11"			0.7)
			("cut_part" args "wood12"			"wood12"			0.7)
			("cut_part" args "wood13"			"wood13"			0.7)
			("cut_part" args "wood14"			"wood14"			0.7)
			("cut_part" args "wood15"			"wood15"			0.7)
			("cut_part" args "wood16"			"wood16"			0.7)
			("cut_part" args "wood17"			"wood17"			0.7)
			("cut_part" args "wood18"			"wood18"			0.7)
			("cut_part" args "wood19"			"wood19"			0.7)
			("cut_part" args "wood20"			"wood20"			0.7)
			("cut_part" args "rack00"			"rack00"			0.7)
			("cut_part" args "rack01"			"rack01"			0.7)
			("cut_part" args "piece00"			"piece00"			0.7)
			("cut_part" args "piece01"			"piece01"			0.7)
		}
	}
	{on pierce
		{if stuff "bullet"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_small_wood" bone %0
							{impulse up 1 0.5 dir 1 0.5}
						}
					else volume "body"
						{if rand 0.2
							{set "end_stage" 1}
							{call "end_stage"}		
						}
					}
				}
			)	
			("cut_part" args "wood00"			"wood00"			0.3)
			("cut_part" args "wood01"			"wood01"			0.3)
			("cut_part" args "wood02"			"wood02"			0.3)
			("cut_part" args "wood03"			"wood03"			0.3)
			("cut_part" args "wood04"			"wood04"			0.3)
			("cut_part" args "wood05"			"wood05"			0.3)
			("cut_part" args "wood06"			"wood06"			0.3)
			("cut_part" args "wood07"			"wood07"			0.3)
			("cut_part" args "wood08"			"wood08"			0.3)
			("cut_part" args "wood09"			"wood09"			0.3)
			("cut_part" args "wood10"			"wood10"			0.3)
			("cut_part" args "wood11"			"wood11"			0.3)
			("cut_part" args "wood12"			"wood12"			0.3)
			("cut_part" args "wood13"			"wood13"			0.3)
			("cut_part" args "wood14"			"wood14"			0.3)
			("cut_part" args "wood15"			"wood15"			0.3)
			("cut_part" args "wood16"			"wood16"			0.3)
			("cut_part" args "wood17"			"wood17"			0.3)
			("cut_part" args "wood18"			"wood18"			0.3)
			("cut_part" args "wood19"			"wood19"			0.3)
			("cut_part" args "wood20"			"wood20"			0.3)
			("cut_part" args "rack00"			"rack00"			0.2)
			("cut_part" args "rack01"			"rack01"			0.2)
			("cut_part" args "piece00"			"piece00"			0.7)
			("cut_part" args "piece01"			"piece01"			0.7)
		}
	}
	{on "end_stage"
		{if "end_stage"
			{if rand 0.1
				(define "cut_part"
					{tear "piece_small_wood" bone %0
						{impulse up 0.2 dir 0.3 0.1}
					}
				)
				("cut_part" args "wood00"			"wood00"		)
				("cut_part" args "wood01"			"wood01"		)
				("cut_part" args "wood02"			"wood02"		)
				("cut_part" args "wood03"			"wood03"		)
				("cut_part" args "wood04"			"wood04"		)
				("cut_part" args "wood05"			"wood05"		)
				("cut_part" args "wood06"			"wood06"	)
				("cut_part" args "wood07"			"wood07"		)
				("cut_part" args "wood08"			"wood08"		)
				("cut_part" args "wood09"			"wood09"			)
				("cut_part" args "wood10"			"wood10"		)
				("cut_part" args "wood11"			"wood11"		)
				("cut_part" args "wood12"			"wood12"			)
				("cut_part" args "wood13"			"wood13"			)
				("cut_part" args "wood14"			"wood14"			)
				("cut_part" args "wood15"			"wood15"			)
				("cut_part" args "wood16"			"wood16"			)
				("cut_part" args "wood17"			"wood17"			)
				("cut_part" args "wood18"			"wood18"			)
				("cut_part" args "wood19"			"wood19"			)
				("cut_part" args "wood20"			"wood20"			)
				("cut_part" args "railing00"			"railing00"			)
				("cut_part" args "railing01"			"railing01"			)
				("cut_part" args "railing02"			"railing02"			)
				("cut_part" args "rack00"			"rack00"			 )
				("cut_part" args "rack01"			"rack01"			 )
				("cut_part" args "piece00"			"piece00"			 )
				("cut_part" args "piece01"			"piece01"			 )
			}
		}
	}
}

{"metals_build_all"
	{on pierce sync
		{if volume "glass"
			{volume disable bullet contact blast}
			{spawn "glass_hit_small" volume x}
			{delay_ex 0.1 uniq
				{bone cut}
			}
		}
		{ani_play "hit" 1}
		{if stuff "shell"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{ani_play %0 1}
						{delay 0.1
							{tear "piece_small_steel" bone %0
								{spawn "metal_hit_sl" %0}
								{impulse up 2 0.5 dir 2 0.5}
							}
						}
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "volts"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "wire"
						{spawn "metal_hit_wire" }
					else volume "frame"
						{if rand 0.0001
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				}
			)	
			("cut_part" args "wire"			"wire"			0.9)
			("cut_part" args "plank00"		"plank00"			0.9)
			("cut_part" args "plank01"		"plank01"			0.9)
			("cut_part" args "plank02"		"plank02"			0.9)
			("cut_part" args "plank03"		"plank03"			0.9)
			("cut_part" args "plank04"		"plank04"			0.9)
			("cut_part" args "plank05"		"plank05"			0.9)
			("cut_part" args "plank06"		"plank06"			0.9)
			("cut_part" args "plank07"		"plank07"			0.9)
			("cut_part" args "steel00"		"steel00"			0.9)
			("cut_part" args "steel01"		"steel01"			0.9)
			("cut_part" args "steel02"		"steel02"			0.9)
			("cut_part" args "steel03"		"steel03"			0.9)
			("cut_part" args "steel04"		"steel04"			0.9)
			("cut_part" args "steel05"		"steel05"			0.9)
			("cut_part" args "steel06"		"steel06"			0.9)
			("cut_part" args "steel07"		"steel07"			0.9)
			("cut_part" args "steel08"		"steel08"			0.9)
			("cut_part" args "steel09"		"steel09"			0.9)
			("cut_part" args "steel10"		"steel10"			0.9)
			("cut_part" args "steel11"		"steel11"			0.9)
			("cut_part" args "steel12"		"steel12"			0.9)
			("cut_part" args "steel13"		"steel13"			0.9)
			("cut_part" args "steel14"		"steel14"			0.9)
			("cut_part" args "steel15"		"steel15"			0.9)
			("cut_part" args "steel16"		"steel16"			0.9)
			("cut_part" args "steel17"		"steel17"			0.9)
			("cut_part" args "steel18"		"steel18"			0.9)
			("cut_part" args "steel19"		"steel19"			0.9)
			("cut_part" args "steel20"		"steel20"			0.9)
			("cut_part" args "steel21"		"steel21"			0.9)
			("cut_part" args "steel22"		"steel22"			0.9)
			("cut_part" args "steel23"		"steel23"			0.9)
			("cut_part" args "steel24"		"steel24"			0.9)
			("cut_part" args "steel25"		"steel25"			0.9)
			("cut_part" args "steel26"		"steel26"			0.9)
			("cut_part" args "steel27"		"steel27"			0.9)
			("cut_part" args "steel28"		"steel28"			0.9)
			("cut_part" args "steel29"		"steel29"			0.9)
			("cut_part" args "steel30"		"steel30"			0.9)
			("cut_part" args "steel31"		"steel31"			0.9)
			("cut_part" args "steel32"		"steel32"			0.9)
			("cut_part" args "steel33"		"steel33"			0.9)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.9)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.9)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.9)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.9)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.9)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.9)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.9)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.9)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.9)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.9)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.9)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.9)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.9)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.9)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.9)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.9)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.9)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.9)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.9)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.9)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.9)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.9)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.9)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.9)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.9)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.9)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.9)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.9)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.9)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.9)
			("cut_part" args "wood00"		"wood00"			0.9)
			("cut_part" args "wood01"		"wood01"			0.9)
			("cut_part" args "wood02"		"wood02"			0.9)
			("cut_part" args "wood03"		"wood03"			0.9)
			("cut_part" args "wood04"		"wood04"			0.9)
			("cut_part" args "wood05"		"wood05"			0.9)
			("cut_part" args "wood06"		"wood06"			0.9)
			("cut_part" args "wood07"		"wood07"			0.9)
			("cut_part" args "wood08"		"wood08"			0.9)
			("cut_part" args "wood09"		"wood09"			0.9)
			("cut_part" args "wood10"		"wood10"			0.9)
			("cut_part" args "wood11"		"wood11"			0.9)
			("cut_part" args "wood12"		"wood12"			0.9)
			("cut_part" args "wood13"		"wood13"			0.9)
			("cut_part" args "wood14"		"wood14"			0.9)
			("cut_part" args "wood15"		"wood15"			0.9)
			("cut_part" args "wood16"		"wood16"			0.9)
			("cut_part" args "wood17"		"wood17"			0.9)
			("cut_part" args "wood18"		"wood18"			0.9)
			("cut_part" args "wood19"		"wood19"			0.9)
		else stuff "zenite"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{ani_play %0 1}
						{delay 0.1
							{tear "piece_small_steel" bone %0
								{spawn "metal_hit_sl" %0}
								{impulse up 2 0.5 dir 2 0.5}
							}
						}
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "volts"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "wire"
						{spawn "metal_hit_wire" }
					else volume "frame"
						{if rand 0.0001
							{set "end_stage" 1}
							{call "end_stage"}
						}
					}
				}
			)	
			("cut_part" args "wire"			"wire"			0.9)
			("cut_part" args "plank00"		"plank00"			0.9)
			("cut_part" args "plank01"		"plank01"			0.9)
			("cut_part" args "plank02"		"plank02"			0.9)
			("cut_part" args "plank03"		"plank03"			0.9)
			("cut_part" args "plank04"		"plank04"			0.9)
			("cut_part" args "plank05"		"plank05"			0.9)
			("cut_part" args "plank06"		"plank06"			0.9)
			("cut_part" args "plank07"		"plank07"			0.9)
			("cut_part" args "steel00"		"steel00"			0.9)
			("cut_part" args "steel01"		"steel01"			0.9)
			("cut_part" args "steel02"		"steel02"			0.9)
			("cut_part" args "steel03"		"steel03"			0.9)
			("cut_part" args "steel04"		"steel04"			0.9)
			("cut_part" args "steel05"		"steel05"			0.9)
			("cut_part" args "steel06"		"steel06"			0.9)
			("cut_part" args "steel07"		"steel07"			0.9)
			("cut_part" args "steel08"		"steel08"			0.9)
			("cut_part" args "steel09"		"steel09"			0.9)
			("cut_part" args "steel10"		"steel10"			0.9)
			("cut_part" args "steel11"		"steel11"			0.9)
			("cut_part" args "steel12"		"steel12"			0.9)
			("cut_part" args "steel13"		"steel13"			0.9)
			("cut_part" args "steel14"		"steel14"			0.9)
			("cut_part" args "steel15"		"steel15"			0.9)
			("cut_part" args "steel16"		"steel16"			0.9)
			("cut_part" args "steel17"		"steel17"			0.9)
			("cut_part" args "steel18"		"steel18"			0.9)
			("cut_part" args "steel19"		"steel19"			0.9)
			("cut_part" args "steel20"		"steel20"			0.9)
			("cut_part" args "steel21"		"steel21"			0.9)
			("cut_part" args "steel22"		"steel22"			0.9)
			("cut_part" args "steel23"		"steel23"			0.9)
			("cut_part" args "steel24"		"steel24"			0.9)
			("cut_part" args "steel25"		"steel25"			0.9)
			("cut_part" args "steel26"		"steel26"			0.9)
			("cut_part" args "steel27"		"steel27"			0.9)
			("cut_part" args "steel28"		"steel28"			0.9)
			("cut_part" args "steel29"		"steel29"			0.9)
			("cut_part" args "steel30"		"steel30"			0.9)
			("cut_part" args "steel31"		"steel31"			0.9)
			("cut_part" args "steel32"		"steel32"			0.9)
			("cut_part" args "steel33"		"steel33"			0.9)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.9)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.9)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.9)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.9)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.9)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.9)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.9)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.9)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.9)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.9)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.9)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.9)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.9)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.9)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.9)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.9)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.9)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.9)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.9)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.9)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.9)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.9)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.9)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.9)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.9)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.9)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.9)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.9)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.9)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.9)
			("cut_part" args "wood00"		"wood00"			0.9)
			("cut_part" args "wood01"		"wood01"			0.9)
			("cut_part" args "wood02"		"wood02"			0.9)
			("cut_part" args "wood03"		"wood03"			0.9)
			("cut_part" args "wood04"		"wood04"			0.9)
			("cut_part" args "wood05"		"wood05"			0.9)
			("cut_part" args "wood06"		"wood06"			0.9)
			("cut_part" args "wood07"		"wood07"			0.9)
			("cut_part" args "wood08"		"wood08"			0.9)
			("cut_part" args "wood09"		"wood09"			0.9)
			("cut_part" args "wood10"		"wood10"			0.9)
			("cut_part" args "wood11"		"wood11"			0.9)
			("cut_part" args "wood12"		"wood12"			0.9)
			("cut_part" args "wood13"		"wood13"			0.9)
			("cut_part" args "wood14"		"wood14"			0.9)
			("cut_part" args "wood15"		"wood15"			0.9)
			("cut_part" args "wood16"		"wood16"			0.9)
			("cut_part" args "wood17"		"wood17"			0.9)
			("cut_part" args "wood18"		"wood18"			0.9)
			("cut_part" args "wood19"		"wood19"			0.9)
		else stuff "fx_40"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{ani_play %0 1}
						{delay 0.1
							{tear "piece_small_steel" bone %0
								{spawn "metal_crush" %0}
								{impulse up 3 0.5 dir 2 0.5}
							}
						}
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "wire"
						{set_skeleton "_x" sync}
						{spawn "metal_hit_wire" }
					else volume "frame"
						{set_skeleton "_x" sync}
						{set "end_stage" 1}
						{call "end_stage"}		
					}
				}
			)	
			("cut_part" args "wire"			"wire"				0.9)
			("cut_part" args "plank00"		"plank00"			0.9)
			("cut_part" args "plank01"		"plank01"			0.9)
			("cut_part" args "plank02"		"plank02"			0.9)
			("cut_part" args "plank03"		"plank03"			0.9)
			("cut_part" args "plank04"		"plank04"			0.9)
			("cut_part" args "plank05"		"plank05"			0.9)
			("cut_part" args "plank06"		"plank06"			0.9)
			("cut_part" args "plank07"		"plank07"			0.9)
			("cut_part" args "steel00"		"steel00"			0.9)
			("cut_part" args "steel01"		"steel01"			0.9)
			("cut_part" args "steel02"		"steel02"			0.9)
			("cut_part" args "steel03"		"steel03"			0.9)
			("cut_part" args "steel04"		"steel04"			0.9)
			("cut_part" args "steel05"		"steel05"			0.9)
			("cut_part" args "steel06"		"steel06"			0.9)
			("cut_part" args "steel07"		"steel07"			0.9)
			("cut_part" args "steel08"		"steel08"			0.9)
			("cut_part" args "steel09"		"steel09"			0.9)
			("cut_part" args "steel10"		"steel10"			0.9)
			("cut_part" args "steel11"		"steel11"			0.9)
			("cut_part" args "steel12"		"steel12"			0.9)
			("cut_part" args "steel13"		"steel13"			0.9)
			("cut_part" args "steel14"		"steel14"			0.9)
			("cut_part" args "steel15"		"steel15"			0.9)
			("cut_part" args "steel16"		"steel16"			0.9)
			("cut_part" args "steel17"		"steel17"			0.9)
			("cut_part" args "steel18"		"steel18"			0.9)
			("cut_part" args "steel19"		"steel19"			0.9)
			("cut_part" args "steel20"		"steel20"			0.9)
			("cut_part" args "steel21"		"steel21"			0.9)
			("cut_part" args "steel22"		"steel22"			0.9)
			("cut_part" args "steel23"		"steel23"			0.9)
			("cut_part" args "steel24"		"steel24"			0.9)
			("cut_part" args "steel25"		"steel25"			0.9)
			("cut_part" args "steel26"		"steel26"			0.9)
			("cut_part" args "steel27"		"steel27"			0.9)
			("cut_part" args "steel28"		"steel28"			0.9)
			("cut_part" args "steel29"		"steel29"			0.9)
			("cut_part" args "steel30"		"steel30"			0.9)
			("cut_part" args "steel31"		"steel31"			0.9)
			("cut_part" args "steel32"		"steel32"			0.9)
			("cut_part" args "steel33"		"steel33"			0.9)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.9)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.9)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.9)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.9)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.9)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.9)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.9)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.9)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.9)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.9)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.9)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.9)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.9)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.9)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.9)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.9)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.9)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.9)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.9)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.9)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.9)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.9)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.9)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.9)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.9)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.9)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.9)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.9)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.9)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.9)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.9)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.9)
			("cut_part" args "wood00"		"wood00"			0.9)
			("cut_part" args "wood01"		"wood01"			0.9)
			("cut_part" args "wood02"		"wood02"			0.9)
			("cut_part" args "wood03"		"wood03"			0.9)
			("cut_part" args "wood04"		"wood04"			0.9)
			("cut_part" args "wood05"		"wood05"			0.9)
			("cut_part" args "wood06"		"wood06"			0.9)
			("cut_part" args "wood07"		"wood07"			0.9)
			("cut_part" args "wood08"		"wood08"			0.9)
			("cut_part" args "wood09"		"wood09"			0.9)
			("cut_part" args "wood10"		"wood10"			0.9)
			("cut_part" args "wood11"		"wood11"			0.9)
			("cut_part" args "wood12"		"wood12"			0.9)
			("cut_part" args "wood13"		"wood13"			0.9)
			("cut_part" args "wood14"		"wood14"			0.9)
			("cut_part" args "wood15"		"wood15"			0.9)
			("cut_part" args "wood16"		"wood16"			0.9)
			("cut_part" args "wood17"		"wood17"			0.9)
			("cut_part" args "wood18"		"wood18"			0.9)
			("cut_part" args "wood19"		"wood19"			0.9)
		else stuff "bullet"
			(define "cut_part"
				{if volume %1
					{ani_play %1 }
					{if rand %2
						{spawn "metal_hit_wire" %0}
						{tear "piece_small_steel" bone %0 
							{impulse up 2 1 dir 1.5 1}
						}
					else volume "wire"
						{spawn "metal_hit_wire" }
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "frame"
						{set "end_stage" 1}
						{call "end_stage"}		
					}
				}
			)	
			("cut_part" args "wire"			"wire"				0.5  wire)
			("cut_part" args "plank00"		"plank00"			0.05 plank00)
			("cut_part" args "plank01"		"plank01"			0.05 plank01)
			("cut_part" args "plank02"		"plank02"			0.05 plank02)
			("cut_part" args "plank03"		"plank03"			0.05 plank03)
			("cut_part" args "plank04"		"plank04"			0.05 plank04)
			("cut_part" args "plank05"		"plank05"			0.05 plank05)
			("cut_part" args "plank06"		"plank06"			0.05 plank06)
			("cut_part" args "plank07"		"plank07"			0.05 plank06)
			("cut_part" args "steel00"		"steel00"			0.3 steel00)
			("cut_part" args "steel01"		"steel01"			0.3 steel01)
			("cut_part" args "steel02"		"steel02"			0.3 steel02)
			("cut_part" args "steel03"		"steel03"			0.3 steel03)
			("cut_part" args "steel04"		"steel04"			0.3 steel04)
			("cut_part" args "steel05"		"steel05"			0.3 steel05)
			("cut_part" args "steel06"		"steel06"			0.3 steel06)
			("cut_part" args "steel07"		"steel07"			0.3 steel07)
			("cut_part" args "steel08"		"steel08"			0.3 steel08)
			("cut_part" args "steel09"		"steel09"			0.05 steel09)
			("cut_part" args "steel10"		"steel10"			0.3 steel10)
			("cut_part" args "steel11"		"steel11"			0.05 steel11)
			("cut_part" args "steel12"		"steel12"			0.3  steel12)
			("cut_part" args "steel13"		"steel13"			0.3 steel13)
			("cut_part" args "steel14"		"steel14"			0.3 steel14)
			("cut_part" args "steel15"		"steel15"			0.3 steel15)
			("cut_part" args "steel16"		"steel16"			0.3 steel16)
			("cut_part" args "steel17"		"steel17"			0.3 steel17)
			("cut_part" args "steel18"		"steel18"			0.3 steel18)
			("cut_part" args "steel19"		"steel19"			0.3 steel19)
			("cut_part" args "steel20"		"steel20"			0.3 steel20)
			("cut_part" args "steel21"		"steel21"			0.3 steel21)
			("cut_part" args "steel22"		"steel22"			0.3 steel22)
			("cut_part" args "steel23"		"steel23"			0.3 steel23)
			("cut_part" args "steel24"		"steel24"			0.3 steel24)
			("cut_part" args "steel25"		"steel25"			0.3 steel25)
			("cut_part" args "steel26"		"steel26"			0.3 steel26)
			("cut_part" args "steel27"		"steel27"			0.3 steel27)
			("cut_part" args "steel28"		"steel28"			0.3 steel28)
			("cut_part" args "steel29"		"steel29"			0.3 steel29)
			("cut_part" args "steel30"		"steel30"			0.3 steel30)
			("cut_part" args "steel31"		"steel31"			0.3 steel31)
			("cut_part" args "steel32"		"steel32"			0.3 steel32)
			("cut_part" args "steel33"		"steel33"			0.3 steel33)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.1 iron_sheet00)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.1 iron_sheet01)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.1 iron_sheet02)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.1 iron_sheet03)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.1 iron_sheet04)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.1 iron_sheet05)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.1 iron_sheet06)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.1 iron_sheet07)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.1 iron_sheet08)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.1 iron_sheet09)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.1 iron_sheet10)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.1 iron_sheet11)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.1 iron_sheet12)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.1 iron_sheet13)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.1 iron_sheet14)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.1 iron_sheet15)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.1 iron_sheet16)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.1 iron_sheet17)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.1 iron_sheet18)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.1 iron_sheet19)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.1 iron_sheet20)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.1 iron_sheet21)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.1 iron_sheet21a)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.1 iron_sheet22)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.1 iron_sheet22a)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.1 iron_sheet23)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.1 iron_sheet24)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.1 iron_sheet25)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.1 iron_sheet26)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.1 iron_sheet27)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.1 iron_sheet28)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.1 iron_sheet29)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.1 iron_sheet30)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.1 iron_sheet31)
			("cut_part" args "wood00"		"wood00"			0.2 wood00)
			("cut_part" args "wood01"		"wood01"			0.2 wood01)
			("cut_part" args "wood02"		"wood02"			0.2 wood02)
			("cut_part" args "wood03"		"wood03"			0.2 wood03)
			("cut_part" args "wood04"		"wood04"			0.2 wood04)
			("cut_part" args "wood05"		"wood05"			0.2 wood05)
			("cut_part" args "wood06"		"wood06"			0.2 wood06)
			("cut_part" args "wood07"		"wood07"			0.2 wood07)
			("cut_part" args "wood08"		"wood08"			0.2 wood08)
			("cut_part" args "wood09"		"wood09"			0.2 wood09)
			("cut_part" args "wood10"		"wood10"			0.2 wood10)
			("cut_part" args "wood11"		"wood11"			0.2 wood11)
			("cut_part" args "wood12"		"wood12"			0.2 wood12)
			("cut_part" args "wood13"		"wood13"			0.2 wood13)
			("cut_part" args "wood14"		"wood14"			0.2 wood14)
			("cut_part" args "wood15"		"wood15"			0.2 wood15)
			("cut_part" args "wood16"		"wood16"			0.2 wood16)
			("cut_part" args "wood17"		"wood17"			0.2 wood17)
			("cut_part" args "wood18"		"wood18"			0.2 wood18)
			("cut_part" args "wood19"		"wood19"			0.2 wood19)
		}
	}
	{on contact
		{if volume "glass"
			{volume disable bullet contact blast}
			{spawn "glass_hit_small" volume x}
			{delay_ex 0.1 uniq
				{bone cut}
			}
		}
		{ani_play "hit" 1}
		{if effector "fraction" 
			{if contact_velocity 1
				(define "cut_part"
					{if rand %2
						{if volume %1
							{ani_play %0 1}
							{tear "piece_small_steel" bone %0
								{impulse up 5 1 dir 2 1}
							}
						}
					}
				)	
				("cut_part" args "wire"			"wire"					0.1)
				("cut_part" args "plank00"		"plank00"				0.02)
				("cut_part" args "plank01"		"plank01"				0.02)
				("cut_part" args "plank02"		"plank02"				0.02)
				("cut_part" args "plank03"		"plank03"				0.02)
				("cut_part" args "plank04"		"plank04"				0.02)
				("cut_part" args "plank05"		"plank05"				0.02)
				("cut_part" args "plank06"		"plank06"				0.02)
				("cut_part" args "plank07"		"plank07"				0.02)
				("cut_part" args "steel00"		"steel00"				0.04)
				("cut_part" args "steel01"		"steel01"				0.04)
				("cut_part" args "steel02"		"steel02"				0.04)
				("cut_part" args "steel03"		"steel03"				0.04)
				("cut_part" args "steel04"		"steel04"				0.04)
				("cut_part" args "steel05"		"steel05"				0.04)
				("cut_part" args "steel06"		"steel06"				0.04)
				("cut_part" args "steel07"		"steel07"				0.04)
				("cut_part" args "steel08"		"steel08"				0.04)
				("cut_part" args "steel09"		"steel09"				0.04)
				("cut_part" args "steel10"		"steel10"				0.04)
				("cut_part" args "steel11"		"steel11"				0.04)
				("cut_part" args "steel12"		"steel12"				0.04)
				("cut_part" args "steel13"		"steel13"				0.04)
				("cut_part" args "steel14"		"steel14"				0.04)
				("cut_part" args "steel15"		"steel15"				0.04)
				("cut_part" args "steel16"		"steel16"				0.04)
				("cut_part" args "steel17"		"steel17"				0.04)
				("cut_part" args "steel18"		"steel18"				0.04)
				("cut_part" args "steel19"		"steel19"				0.04)
				("cut_part" args "steel20"		"steel20"				0.04)
				("cut_part" args "steel21"		"steel21"				0.04)
				("cut_part" args "steel22"		"steel22"				0.04)
				("cut_part" args "steel23"		"steel23"				0.04)
				("cut_part" args "steel24"		"steel24"				0.04)
				("cut_part" args "steel25"		"steel25"				0.04)
				("cut_part" args "steel26"		"steel26"				0.04)
				("cut_part" args "steel27"		"steel27"				0.04)
				("cut_part" args "steel28"		"steel28"				0.04)
				("cut_part" args "steel29"		"steel29"				0.04)
				("cut_part" args "steel30"		"steel30"				0.04)
				("cut_part" args "steel31"		"steel31"				0.04)
				("cut_part" args "steel32"		"steel32"				0.04)
				("cut_part" args "steel33"		"steel33"				0.04)
				("cut_part" args "iron_sheet00"		"iron_sheet00"				0.04)
				("cut_part" args "iron_sheet01"		"iron_sheet01"				0.04)
				("cut_part" args "iron_sheet02"		"iron_sheet02"				0.04)
				("cut_part" args "iron_sheet03"		"iron_sheet03"				0.04)
				("cut_part" args "iron_sheet04"		"iron_sheet04"				0.04)
				("cut_part" args "iron_sheet05"		"iron_sheet05"				0.04)
				("cut_part" args "iron_sheet06"		"iron_sheet06"				0.04)
				("cut_part" args "iron_sheet07"		"iron_sheet07"				0.04)
				("cut_part" args "iron_sheet08"		"iron_sheet08"				0.04)
				("cut_part" args "iron_sheet09"		"iron_sheet09"				0.04)
				("cut_part" args "iron_sheet10"		"iron_sheet10"				0.04)
				("cut_part" args "iron_sheet11"		"iron_sheet11"				0.04)
				("cut_part" args "iron_sheet12"		"iron_sheet12"				0.04)
				("cut_part" args "iron_sheet13"		"iron_sheet13"				0.04)
				("cut_part" args "iron_sheet14"		"iron_sheet14"				0.04)
				("cut_part" args "iron_sheet15"		"iron_sheet15"				0.04)
				("cut_part" args "iron_sheet16"		"iron_sheet16"				0.04)
				("cut_part" args "iron_sheet17"		"iron_sheet17"				0.04)
				("cut_part" args "iron_sheet18"		"iron_sheet18"				0.04)
				("cut_part" args "iron_sheet19"		"iron_sheet19"				0.04)
				("cut_part" args "iron_sheet20"		"iron_sheet20"				0.04)
				("cut_part" args "iron_sheet21"		"iron_sheet21"				0.04)
				("cut_part" args "iron_sheet21"		"iron_sheet21a"				0.04)
				("cut_part" args "iron_sheet22"		"iron_sheet22"				0.04)
				("cut_part" args "iron_sheet22"		"iron_sheet22a"				0.04)
				("cut_part" args "iron_sheet23"		"iron_sheet23"				0.04)
				("cut_part" args "iron_sheet24"		"iron_sheet24"				0.04)
				("cut_part" args "iron_sheet25"		"iron_sheet25"				0.04)
				("cut_part" args "iron_sheet26"		"iron_sheet26"				0.04)
				("cut_part" args "iron_sheet27"		"iron_sheet27"				0.04)
				("cut_part" args "iron_sheet28"		"iron_sheet28"			0.04)
				("cut_part" args "iron_sheet29"		"iron_sheet29"			0.04)
				("cut_part" args "iron_sheet30"		"iron_sheet30"			0.04)
				("cut_part" args "iron_sheet31"		"iron_sheet31"			0.04)
				("cut_part" args "wood00"		"wood00"				0.07)
				("cut_part" args "wood01"		"wood01"				0.07)
				("cut_part" args "wood02"		"wood02"				0.07)
				("cut_part" args "wood03"		"wood03"				0.07)
				("cut_part" args "wood04"		"wood04"				0.07)
				("cut_part" args "wood05"		"wood05"				0.07)
				("cut_part" args "wood06"		"wood06"				0.07)
				("cut_part" args "wood07"		"wood07"				0.07)
				("cut_part" args "wood08"		"wood08"				0.07)
				("cut_part" args "wood09"		"wood09"				0.07)
				("cut_part" args "wood10"		"wood10"				0.07)
				("cut_part" args "wood11"		"wood11"				0.07)
				("cut_part" args "wood12"		"wood12"				0.07)
				("cut_part" args "wood13"		"wood13"				0.07)
				("cut_part" args "wood14"		"wood14"				0.07)
				("cut_part" args "wood15"		"wood15"				0.07)
				("cut_part" args "wood16"		"wood16"				0.07)
				("cut_part" args "wood17"		"wood17"				0.07)
				("cut_part" args "wood18"		"wood18"				0.07)
				("cut_part" args "wood19"		"wood19"				0.07)
			}	
		else effector "tank" 
				(define "cut_part"
					{if volume %1
						{ani_play %0 1}
						{tear "piece_small_steel" bone %0
							{impulse up 5 1 dir 2 1}
						}
					}
				)	
				("cut_part" args "wire"			"wire"			)
				("cut_part" args "plank00"		"plank00"				)
				("cut_part" args "plank01"		"plank01"				)
				("cut_part" args "plank02"		"plank02"				)
				("cut_part" args "plank03"		"plank03"				)
				("cut_part" args "plank04"		"plank04"				)
				("cut_part" args "plank05"		"plank05"				)
				("cut_part" args "plank06"		"plank06"				)
				("cut_part" args "plank07"		"plank07"				)
				("cut_part" args "steel00"		"steel00"				)
				("cut_part" args "steel01"		"steel01"				)
				("cut_part" args "steel02"		"steel02"				)
				("cut_part" args "steel03"		"steel03"				)
				("cut_part" args "steel04"		"steel04"				)
				("cut_part" args "steel05"		"steel05"				)
				("cut_part" args "steel06"		"steel06"				)
				("cut_part" args "steel07"		"steel07"				)
				("cut_part" args "steel08"		"steel08"				)
				("cut_part" args "steel09"		"steel09"				)
				("cut_part" args "steel10"		"steel10"				)
				("cut_part" args "steel11"		"steel11"				)
				("cut_part" args "steel12"		"steel12"				)
				("cut_part" args "steel13"		"steel13"				)
				("cut_part" args "steel14"		"steel14"				)
				("cut_part" args "steel15"		"steel15"				)
				("cut_part" args "steel16"		"steel16"				)
				("cut_part" args "steel17"		"steel17"				)
				("cut_part" args "steel18"		"steel18"				)
				("cut_part" args "steel19"		"steel19"				)
				("cut_part" args "steel20"		"steel20"				)
				("cut_part" args "steel21"		"steel21"				)
				("cut_part" args "steel22"		"steel22"				)
				("cut_part" args "steel23"		"steel23"				)
				("cut_part" args "steel24"		"steel24"				)
				("cut_part" args "steel25"		"steel25"				)
				("cut_part" args "steel26"		"steel26"				)
				("cut_part" args "steel27"		"steel27"				)
				("cut_part" args "steel28"		"steel28"				)
				("cut_part" args "steel29"		"steel29"				)
				("cut_part" args "steel30"		"steel30"				)
				("cut_part" args "steel31"		"steel31"				)
				("cut_part" args "steel32"		"steel32"				)
				("cut_part" args "steel33"		"steel33"				)
				("cut_part" args "iron_sheet00"		"iron_sheet00"				)
				("cut_part" args "iron_sheet01"		"iron_sheet01"				)
				("cut_part" args "iron_sheet02"		"iron_sheet02"				)
				("cut_part" args "iron_sheet03"		"iron_sheet03"				)
				("cut_part" args "iron_sheet04"		"iron_sheet04"				)
				("cut_part" args "iron_sheet05"		"iron_sheet05"				)
				("cut_part" args "iron_sheet06"		"iron_sheet06"				)
				("cut_part" args "iron_sheet07"		"iron_sheet07"				)
				("cut_part" args "iron_sheet08"		"iron_sheet08"				)
				("cut_part" args "iron_sheet09"		"iron_sheet09"				)
				("cut_part" args "iron_sheet10"		"iron_sheet10"				)
				("cut_part" args "iron_sheet11"		"iron_sheet11"				)
				("cut_part" args "iron_sheet12"		"iron_sheet12"				)
				("cut_part" args "iron_sheet13"		"iron_sheet13"				)
				("cut_part" args "iron_sheet14"		"iron_sheet14"				)
				("cut_part" args "iron_sheet15"		"iron_sheet15"				)
				("cut_part" args "iron_sheet16"		"iron_sheet16"				)
				("cut_part" args "iron_sheet17"		"iron_sheet17"				)
				("cut_part" args "iron_sheet18"		"iron_sheet18"				)
				("cut_part" args "iron_sheet19"		"iron_sheet19"				)
				("cut_part" args "iron_sheet20"		"iron_sheet20"				)
				("cut_part" args "iron_sheet21"		"iron_sheet21"				)
				("cut_part" args "iron_sheet21"		"iron_sheet21a"				)
				("cut_part" args "iron_sheet22"		"iron_sheet22"				)
				("cut_part" args "iron_sheet22"		"iron_sheet22a"				)
				("cut_part" args "iron_sheet23"		"iron_sheet23"				)
				("cut_part" args "iron_sheet24"		"iron_sheet24"				)
				("cut_part" args "iron_sheet25"		"iron_sheet25"				)
				("cut_part" args "iron_sheet26"		"iron_sheet26"				)
				("cut_part" args "iron_sheet27"		"iron_sheet27"				)
				("cut_part" args "iron_sheet28"		"iron_sheet28"			)
				("cut_part" args "iron_sheet29"		"iron_sheet29"			)
				("cut_part" args "iron_sheet30"		"iron_sheet30"			)
				("cut_part" args "iron_sheet31"		"iron_sheet31"			)
				("cut_part" args "wood00"		"wood00"				)
				("cut_part" args "wood01"		"wood01"				)
				("cut_part" args "wood02"		"wood02"				)
				("cut_part" args "wood03"		"wood03"				)
				("cut_part" args "wood04"		"wood04"				)
				("cut_part" args "wood05"		"wood05"				)
				("cut_part" args "wood06"		"wood06"				)
				("cut_part" args "wood07"		"wood07"				)
				("cut_part" args "wood08"		"wood08"				)
				("cut_part" args "wood09"		"wood09"				)
				("cut_part" args "wood10"		"wood10"				)
				("cut_part" args "wood11"		"wood11"				)
				("cut_part" args "wood12"		"wood12"				)
				("cut_part" args "wood13"		"wood13"				)
				("cut_part" args "wood14"		"wood14"				)
				("cut_part" args "wood15"		"wood15"				)
				("cut_part" args "wood16"		"wood16"				)
				("cut_part" args "wood17"		"wood17"				)
				("cut_part" args "wood18"		"wood18"				)
				("cut_part" args "wood19"		"wood19"				)
		else effector "vehicle" 
			{if contact_velocity 25
				(define "cut_part"
					{if volume %1
						{ani_play %0 1}
						{tear "piece_small_steel" bone %0
							{impulse up 12 1 dir 6 1}
						}
					else volume "wire"
						{spawn "metal_hit_wire" }
					}
				)	
				("cut_part" args "plank00"		"plank00"				)
				("cut_part" args "wire"			"wire"					)
				("cut_part" args "plank01"		"plank01"				)
				("cut_part" args "plank02"		"plank02"				)
				("cut_part" args "plank03"		"plank03"				)
				("cut_part" args "plank04"		"plank04"				)
				("cut_part" args "plank05"		"plank05"				)
				("cut_part" args "plank06"		"plank06"				)
				("cut_part" args "plank07"		"plank07"				)
				("cut_part" args "steel00"		"steel00"				)
				("cut_part" args "steel01"		"steel01"				)
				("cut_part" args "steel02"		"steel02"				)
				("cut_part" args "steel03"		"steel03"				)
				("cut_part" args "steel04"		"steel04"				)
				("cut_part" args "steel05"		"steel05"				)
				("cut_part" args "steel06"		"steel06"				)
				("cut_part" args "steel07"		"steel07"				)
				("cut_part" args "steel08"		"steel08"				)
				("cut_part" args "steel09"		"steel09"				)
				("cut_part" args "steel10"		"steel10"				)
				("cut_part" args "steel11"		"steel11"				)
				("cut_part" args "steel12"		"steel12"				)
				("cut_part" args "steel13"		"steel13"				)
				("cut_part" args "steel14"		"steel14"				)
				("cut_part" args "steel15"		"steel15"				)
				("cut_part" args "steel16"		"steel16"				)
				("cut_part" args "steel17"		"steel17"				)
				("cut_part" args "steel18"		"steel18"				)
				("cut_part" args "steel19"		"steel19"				)
				("cut_part" args "steel20"		"steel20"				)
				("cut_part" args "steel21"		"steel21"				)
				("cut_part" args "steel22"		"steel22"				)
				("cut_part" args "steel23"		"steel23"				)
				("cut_part" args "steel24"		"steel24"				)
				("cut_part" args "steel25"		"steel25"				)
				("cut_part" args "steel26"		"steel26"				)
				("cut_part" args "steel27"		"steel27"				)
				("cut_part" args "steel28"		"steel28"				)
				("cut_part" args "steel29"		"steel29"				)
				("cut_part" args "steel30"		"steel30"				)
				("cut_part" args "steel31"		"steel31"				)
				("cut_part" args "steel32"		"steel32"				)
				("cut_part" args "steel33"		"steel33"				)
				("cut_part" args "iron_sheet00"		"iron_sheet00"				)
				("cut_part" args "iron_sheet01"		"iron_sheet01"				)
				("cut_part" args "iron_sheet02"		"iron_sheet02"				)
				("cut_part" args "iron_sheet03"		"iron_sheet03"				)
				("cut_part" args "iron_sheet04"		"iron_sheet04"				)
				("cut_part" args "iron_sheet05"		"iron_sheet05"				)
				("cut_part" args "iron_sheet06"		"iron_sheet06"				)
				("cut_part" args "iron_sheet07"		"iron_sheet07"				)
				("cut_part" args "iron_sheet08"		"iron_sheet08"				)
				("cut_part" args "iron_sheet09"		"iron_sheet09"				)
				("cut_part" args "iron_sheet10"		"iron_sheet10"				)
				("cut_part" args "iron_sheet11"		"iron_sheet11"				)
				("cut_part" args "iron_sheet12"		"iron_sheet12"				)
				("cut_part" args "iron_sheet13"		"iron_sheet13"				)
				("cut_part" args "iron_sheet14"		"iron_sheet14"				)
				("cut_part" args "iron_sheet15"		"iron_sheet15"				)
				("cut_part" args "iron_sheet16"		"iron_sheet16"				)
				("cut_part" args "iron_sheet17"		"iron_sheet17"				)
				("cut_part" args "iron_sheet18"		"iron_sheet18"				)
				("cut_part" args "iron_sheet19"		"iron_sheet19"				)
				("cut_part" args "iron_sheet20"		"iron_sheet20"				)
				("cut_part" args "iron_sheet21"		"iron_sheet21"				)
				("cut_part" args "iron_sheet21"		"iron_sheet21a"				)
				("cut_part" args "iron_sheet22"		"iron_sheet22"				)
				("cut_part" args "iron_sheet22"		"iron_sheet22a"				)
				("cut_part" args "iron_sheet23"		"iron_sheet23"				)
				("cut_part" args "iron_sheet24"		"iron_sheet24"				)
				("cut_part" args "iron_sheet25"		"iron_sheet25"				)
				("cut_part" args "iron_sheet26"		"iron_sheet26"				)
				("cut_part" args "iron_sheet27"		"iron_sheet27"				)
				("cut_part" args "iron_sheet28"		"iron_sheet28"			)
				("cut_part" args "iron_sheet29"		"iron_sheet29"			)
				("cut_part" args "iron_sheet30"		"iron_sheet30"			)
				("cut_part" args "iron_sheet31"		"iron_sheet31"			)
				("cut_part" args "wood00"		"wood00"				)
				("cut_part" args "wood01"		"wood01"				)
				("cut_part" args "wood02"		"wood02"				)
				("cut_part" args "wood03"		"wood03"				)
				("cut_part" args "wood04"		"wood04"				)
				("cut_part" args "wood05"		"wood05"				)
				("cut_part" args "wood06"		"wood06"				)
				("cut_part" args "wood07"		"wood07"				)
				("cut_part" args "wood08"		"wood08"				)
				("cut_part" args "wood09"		"wood09"				)
				("cut_part" args "wood10"		"wood10"				)
				("cut_part" args "wood11"		"wood11"				)
				("cut_part" args "wood12"		"wood12"				)
				("cut_part" args "wood13"		"wood13"				)
				("cut_part" args "wood14"		"wood14"				)
				("cut_part" args "wood15"		"wood15"				)
				("cut_part" args "wood16"		"wood16"				)
				("cut_part" args "wood17"		"wood17"				)
				("cut_part" args "wood18"		"wood18"				)
				("cut_part" args "wood19"		"wood19"				)
			else contact_velocity 15
				(define "cut_part"
					{if rand %2
						{if volume %1
							{ani_play %0 1}
							{tear "piece_small_steel" bone %0
								{impulse up 2 1 dir 2 1}
							}
						else volume "wire"
							{spawn "metal_hit_wire" %0}
						}
					}
				)	
				("cut_part" args "wire"			"wire"				0.9)
				("cut_part" args "plank00"		"plank00"				0.7)
				("cut_part" args "plank01"		"plank01"				0.7)
				("cut_part" args "plank02"		"plank02"				0.7)
				("cut_part" args "plank03"		"plank03"				0.7)
				("cut_part" args "plank04"		"plank04"				0.7)
				("cut_part" args "plank05"		"plank05"				0.7)
				("cut_part" args "plank06"		"plank06"				0.7)
				("cut_part" args "plank07"		"plank07"				0.7)
				("cut_part" args "steel00"		"steel00"				0.9)
				("cut_part" args "steel01"		"steel01"				0.9)
				("cut_part" args "steel02"		"steel02"				0.9)
				("cut_part" args "steel03"		"steel03"				0.9)
				("cut_part" args "steel04"		"steel04"				0.9)
				("cut_part" args "steel05"		"steel05"				0.9)
				("cut_part" args "steel06"		"steel06"				0.9)
				("cut_part" args "steel07"		"steel07"				0.9)
				("cut_part" args "steel08"		"steel08"				0.9)
				("cut_part" args "steel09"		"steel09"				0.9)
				("cut_part" args "steel10"		"steel10"				0.9)
				("cut_part" args "steel11"		"steel11"				0.9)
				("cut_part" args "steel12"		"steel12"				0.9)
				("cut_part" args "steel13"		"steel13"				0.9)
				("cut_part" args "steel14"		"steel14"				0.9)
				("cut_part" args "steel15"		"steel15"				0.9)
				("cut_part" args "steel16"		"steel16"				0.9)
				("cut_part" args "steel17"		"steel17"				0.9)
				("cut_part" args "steel18"		"steel18"				0.9)
				("cut_part" args "steel19"		"steel19"				0.9)
				("cut_part" args "steel20"		"steel20"				0.9)
				("cut_part" args "steel21"		"steel21"				0.9)
				("cut_part" args "steel22"		"steel22"				0.9)
				("cut_part" args "steel23"		"steel23"				0.9)
				("cut_part" args "steel24"		"steel24"				0.9)
				("cut_part" args "steel25"		"steel25"				0.9)
				("cut_part" args "steel26"		"steel26"				0.9)
				("cut_part" args "steel27"		"steel27"				0.9)
				("cut_part" args "steel28"		"steel28"				0.9)
				("cut_part" args "steel29"		"steel29"				0.9)
				("cut_part" args "steel30"		"steel30"				0.9)
				("cut_part" args "steel31"		"steel31"				0.9)
				("cut_part" args "steel32"		"steel32"				0.9)
				("cut_part" args "steel33"		"steel33"				0.9)
				("cut_part" args "iron_sheet00"		"iron_sheet00"				0.9)
				("cut_part" args "iron_sheet01"		"iron_sheet01"				0.9)
				("cut_part" args "iron_sheet02"		"iron_sheet02"				0.9)
				("cut_part" args "iron_sheet03"		"iron_sheet03"				0.9)
				("cut_part" args "iron_sheet04"		"iron_sheet04"				0.9)
				("cut_part" args "iron_sheet05"		"iron_sheet05"				0.9)
				("cut_part" args "iron_sheet06"		"iron_sheet06"				0.9)
				("cut_part" args "iron_sheet07"		"iron_sheet07"				0.9)
				("cut_part" args "iron_sheet08"		"iron_sheet08"				0.9)
				("cut_part" args "iron_sheet09"		"iron_sheet09"				0.9)
				("cut_part" args "iron_sheet10"		"iron_sheet10"				0.9)
				("cut_part" args "iron_sheet11"		"iron_sheet11"				0.9)
				("cut_part" args "iron_sheet12"		"iron_sheet12"				0.9)
				("cut_part" args "iron_sheet13"		"iron_sheet13"				0.9)
				("cut_part" args "iron_sheet14"		"iron_sheet14"				0.9)
				("cut_part" args "iron_sheet15"		"iron_sheet15"				0.9)
				("cut_part" args "iron_sheet16"		"iron_sheet16"				0.9)
				("cut_part" args "iron_sheet17"		"iron_sheet17"				0.9)
				("cut_part" args "iron_sheet18"		"iron_sheet18"				0.9)
				("cut_part" args "iron_sheet19"		"iron_sheet19"				0.9)
				("cut_part" args "iron_sheet20"		"iron_sheet20"				0.9)
				("cut_part" args "iron_sheet21"		"iron_sheet21"				0.9)
				("cut_part" args "iron_sheet21"		"iron_sheet21a"				0.9)
				("cut_part" args "iron_sheet22"		"iron_sheet22"				0.9)
				("cut_part" args "iron_sheet22"		"iron_sheet22a"				0.9)
				("cut_part" args "iron_sheet23"		"iron_sheet23"				0.9)
				("cut_part" args "iron_sheet24"		"iron_sheet24"				0.9)
				("cut_part" args "iron_sheet25"		"iron_sheet25"				0.9)
				("cut_part" args "iron_sheet26"		"iron_sheet26"				0.9)
				("cut_part" args "iron_sheet27"		"iron_sheet27"				0.9)
				("cut_part" args "iron_sheet28"		"iron_sheet28"			0.9)
				("cut_part" args "iron_sheet29"		"iron_sheet29"			0.9)
				("cut_part" args "iron_sheet30"		"iron_sheet30"			0.9)
				("cut_part" args "iron_sheet31"		"iron_sheet31"			0.9)
				("cut_part" args "wood00"		"wood00"				0.9)
				("cut_part" args "wood01"		"wood01"				0.9)
				("cut_part" args "wood02"		"wood02"				0.9)
				("cut_part" args "wood03"		"wood03"				0.9)
				("cut_part" args "wood04"		"wood04"				0.9)
				("cut_part" args "wood05"		"wood05"				0.9)
				("cut_part" args "wood06"		"wood06"				0.9)
				("cut_part" args "wood07"		"wood07"				0.9)
				("cut_part" args "wood08"		"wood08"				0.9)
				("cut_part" args "wood09"		"wood09"				0.9)
				("cut_part" args "wood10"		"wood10"				0.9)
				("cut_part" args "wood11"		"wood11"				0.9)
				("cut_part" args "wood12"		"wood12"				0.9)
				("cut_part" args "wood13"		"wood13"				0.9)
				("cut_part" args "wood14"		"wood14"				0.9)
				("cut_part" args "wood15"		"wood15"				0.9)
				("cut_part" args "wood16"		"wood16"				0.9)
				("cut_part" args "wood17"		"wood17"				0.9)
				("cut_part" args "wood18"		"wood18"				0.9)
				("cut_part" args "wood19"		"wood19"				0.9)
			else contact_velocity 5
				(define "cut_part"
					{if rand %2
						{if volume %1
							{ani_play %0 1}
							{tear "piece_small_steel" bone %0
								{impulse up 2 1 dir 2 1}
							}
						else volume "wire"
							{spawn "metal_hit_wire" %0}
						}
					}
				)	
				("cut_part" args "wire"			"wire"			0.5)
				("cut_part" args "plank00"		"plank00"				0.3)
				("cut_part" args "plank01"		"plank01"				0.3)
				("cut_part" args "plank02"		"plank02"				0.3)
				("cut_part" args "plank03"		"plank03"				0.3)
				("cut_part" args "plank04"		"plank04"				0.3)
				("cut_part" args "plank05"		"plank05"				0.3)
				("cut_part" args "plank06"		"plank06"				0.3)
				("cut_part" args "plank07"		"plank07"				0.3)
				("cut_part" args "steel00"		"steel00"				0.5)
				("cut_part" args "steel01"		"steel01"				0.5)
				("cut_part" args "steel02"		"steel02"				0.5)
				("cut_part" args "steel03"		"steel03"				0.5)
				("cut_part" args "steel04"		"steel04"				0.5)
				("cut_part" args "steel05"		"steel05"				0.5)
				("cut_part" args "steel06"		"steel06"				0.5)
				("cut_part" args "steel07"		"steel07"				0.5)
				("cut_part" args "steel08"		"steel08"				0.5)
				("cut_part" args "steel09"		"steel09"				0.5)
				("cut_part" args "steel10"		"steel10"				0.5)
				("cut_part" args "steel11"		"steel11"				0.5)
				("cut_part" args "steel12"		"steel12"				0.5)
				("cut_part" args "steel13"		"steel13"				0.5)
				("cut_part" args "steel14"		"steel14"				0.5)
				("cut_part" args "steel15"		"steel15"				0.5)
				("cut_part" args "steel16"		"steel16"				0.5)
				("cut_part" args "steel17"		"steel17"				0.5)
				("cut_part" args "steel18"		"steel18"				0.5)
				("cut_part" args "steel19"		"steel19"				0.5)
				("cut_part" args "steel20"		"steel20"				0.5)
				("cut_part" args "steel21"		"steel21"				0.5)
				("cut_part" args "steel22"		"steel22"				0.5)
				("cut_part" args "steel23"		"steel23"				0.5)
				("cut_part" args "steel24"		"steel24"				0.5)
				("cut_part" args "steel25"		"steel25"				0.5)
				("cut_part" args "steel26"		"steel26"				0.5)
				("cut_part" args "steel27"		"steel27"				0.5)
				("cut_part" args "steel28"		"steel28"				0.5)
				("cut_part" args "steel29"		"steel29"				0.5)
				("cut_part" args "steel30"		"steel30"				0.5)
				("cut_part" args "steel31"		"steel31"				0.5)
				("cut_part" args "steel32"		"steel32"				0.5)
				("cut_part" args "steel33"		"steel33"				0.5)
				("cut_part" args "iron_sheet00"		"iron_sheet00"				0.5)
				("cut_part" args "iron_sheet01"		"iron_sheet01"				0.5)
				("cut_part" args "iron_sheet02"		"iron_sheet02"				0.5)
				("cut_part" args "iron_sheet03"		"iron_sheet03"				0.5)
				("cut_part" args "iron_sheet04"		"iron_sheet04"				0.5)
				("cut_part" args "iron_sheet05"		"iron_sheet05"				0.5)
				("cut_part" args "iron_sheet06"		"iron_sheet06"				0.5)
				("cut_part" args "iron_sheet07"		"iron_sheet07"				0.5)
				("cut_part" args "iron_sheet08"		"iron_sheet08"				0.5)
				("cut_part" args "iron_sheet09"		"iron_sheet09"				0.5)
				("cut_part" args "iron_sheet10"		"iron_sheet10"				0.5)
				("cut_part" args "iron_sheet11"		"iron_sheet11"				0.5)
				("cut_part" args "iron_sheet12"		"iron_sheet12"				0.5)
				("cut_part" args "iron_sheet13"		"iron_sheet13"				0.5)
				("cut_part" args "iron_sheet14"		"iron_sheet14"				0.5)
				("cut_part" args "iron_sheet15"		"iron_sheet15"				0.5)
				("cut_part" args "iron_sheet16"		"iron_sheet16"				0.5)
				("cut_part" args "iron_sheet17"		"iron_sheet17"				0.5)
				("cut_part" args "iron_sheet18"		"iron_sheet18"				0.5)
				("cut_part" args "iron_sheet19"		"iron_sheet19"				0.5)
				("cut_part" args "iron_sheet20"		"iron_sheet20"				0.5)
				("cut_part" args "iron_sheet21"		"iron_sheet21"				0.5)
				("cut_part" args "iron_sheet21"		"iron_sheet21a"				0.5)
				("cut_part" args "iron_sheet22"		"iron_sheet22"				0.5)
				("cut_part" args "iron_sheet22"		"iron_sheet22a"				0.5)
				("cut_part" args "iron_sheet23"		"iron_sheet23"				0.5)
				("cut_part" args "iron_sheet24"		"iron_sheet24"				0.5)
				("cut_part" args "iron_sheet25"		"iron_sheet25"				0.5)
				("cut_part" args "iron_sheet26"		"iron_sheet26"				0.5)
				("cut_part" args "iron_sheet27"		"iron_sheet27"				0.5)
				("cut_part" args "iron_sheet28"		"iron_sheet28"			0.5)
				("cut_part" args "iron_sheet29"		"iron_sheet29"			0.5)
				("cut_part" args "iron_sheet30"		"iron_sheet30"			0.5)
				("cut_part" args "iron_sheet31"		"iron_sheet31"			0.5)
				("cut_part" args "wood00"		"wood00"				0.5)
				("cut_part" args "wood01"		"wood01"				0.5)
				("cut_part" args "wood02"		"wood02"				0.5)
				("cut_part" args "wood03"		"wood03"				0.5)
				("cut_part" args "wood04"		"wood04"				0.5)
				("cut_part" args "wood05"		"wood05"				0.5)
				("cut_part" args "wood06"		"wood06"				0.5)
				("cut_part" args "wood07"		"wood07"				0.5)
				("cut_part" args "wood08"		"wood08"				0.5)
				("cut_part" args "wood09"		"wood09"				0.5)
				("cut_part" args "wood10"		"wood10"				0.5)
				("cut_part" args "wood11"		"wood11"				0.5)
				("cut_part" args "wood12"		"wood12"				0.5)
				("cut_part" args "wood13"		"wood13"				0.5)
				("cut_part" args "wood14"		"wood14"				0.5)
				("cut_part" args "wood15"		"wood15"				0.5)
				("cut_part" args "wood16"		"wood16"				0.5)
				("cut_part" args "wood17"		"wood17"				0.5)
				("cut_part" args "wood18"		"wood18"				0.5)
				("cut_part" args "wood19"		"wood19"				0.5)
			}
		}
	}
	{on blast
		{if volume "glass"
			{volume disable bullet contact blast}
			{spawn "glass_hit_small" volume x}
			{delay_ex 0.1 uniq
				{bone cut}
			}
		else volume "lamp"
			{view stop "lamp_light_spot1"}
			{view hide "lamp_light_spot1"}
			{view stop "lamp_light_spot2"}
			{view hide "lamp_light_spot2"}
		}
		{ani_play "hit" 1}
		{if min_energy 12
			(define "cut_part"
				{ani_play %0 1}
				{delay 0.1
					{tear "piece_small_steel" bone %0
						{spawn "metal_hit_sl" %0}
						{impulse up 3 2 dir 3 1 cx 2 1 cy 2 1 rnd_dir 4 no_position}
					}
				}
			)
			("cut_part" args "wire"			"wire"			)
			("cut_part" args "plank00"		"plank00" )
			("cut_part" args "plank01"		"plank01" )
			("cut_part" args "plank02"		"plank02" )
			("cut_part" args "plank03"		"plank03" )
			("cut_part" args "plank04"		"plank04" )
			("cut_part" args "plank05"		"plank05" )
			("cut_part" args "plank06"		"plank06" )
			("cut_part" args "plank07"		"plank07" )
			("cut_part" args "steel00"		"steel00" )
			("cut_part" args "steel01"		"steel01" )
			("cut_part" args "steel02"		"steel02" )
			("cut_part" args "steel03"		"steel03" )
			("cut_part" args "steel04"		"steel04" )
			("cut_part" args "steel05"		"steel05" )
			("cut_part" args "steel06"		"steel06" )
			("cut_part" args "steel07"		"steel07" )
			("cut_part" args "steel08"		"steel08" )
			("cut_part" args "steel09"		"steel09" )
			("cut_part" args "steel10"		"steel10" )
			("cut_part" args "steel11"		"steel11" )
			("cut_part" args "steel12"		"steel12" )
			("cut_part" args "steel13"		"steel13" )
			("cut_part" args "steel14"		"steel14" )
			("cut_part" args "steel15"		"steel15" )
			("cut_part" args "steel16"		"steel16" )
			("cut_part" args "steel17"		"steel17" )
			("cut_part" args "steel18"		"steel18" )
			("cut_part" args "steel19"		"steel19" )
			("cut_part" args "steel20"		"steel20" )
			("cut_part" args "steel21"		"steel21" )
			("cut_part" args "steel22"		"steel22" )
			("cut_part" args "steel23"		"steel23" )
			("cut_part" args "steel24"		"steel24" )
			("cut_part" args "steel25"		"steel25" )
			("cut_part" args "steel26"		"steel26" )
			("cut_part" args "steel27"		"steel27" )
			("cut_part" args "steel28"		"steel28" )
			("cut_part" args "steel29"		"steel29" )
			("cut_part" args "steel30"		"steel30" )
			("cut_part" args "steel31"		"steel31" )
			("cut_part" args "steel32"		"steel32" )
			("cut_part" args "steel33"		"steel33" )
			("cut_part" args "iron_sheet00"		"iron_sheet00" )
			("cut_part" args "iron_sheet01"		"iron_sheet01" )
			("cut_part" args "iron_sheet02"		"iron_sheet02" )
			("cut_part" args "iron_sheet03"		"iron_sheet03" )
			("cut_part" args "iron_sheet04"		"iron_sheet04" )
			("cut_part" args "iron_sheet05"		"iron_sheet05" )
			("cut_part" args "iron_sheet06"		"iron_sheet06" )
			("cut_part" args "iron_sheet07"		"iron_sheet07" )
			("cut_part" args "iron_sheet08"		"iron_sheet08" )
			("cut_part" args "iron_sheet09"		"iron_sheet09" )
			("cut_part" args "iron_sheet10"		"iron_sheet10" )
			("cut_part" args "iron_sheet11"		"iron_sheet11" )
			("cut_part" args "iron_sheet12"		"iron_sheet12" )
			("cut_part" args "iron_sheet13"		"iron_sheet13" )
			("cut_part" args "iron_sheet14"		"iron_sheet14" )
			("cut_part" args "iron_sheet15"		"iron_sheet15" )
			("cut_part" args "iron_sheet16"		"iron_sheet16" )
			("cut_part" args "iron_sheet17"		"iron_sheet17" )
			("cut_part" args "iron_sheet18"		"iron_sheet18" )
			("cut_part" args "iron_sheet19"		"iron_sheet19" )
			("cut_part" args "iron_sheet20"		"iron_sheet20" )
			("cut_part" args "iron_sheet21"		"iron_sheet21" )
			("cut_part" args "iron_sheet21"		"iron_sheet21a" )
			("cut_part" args "iron_sheet22"		"iron_sheet22" )
			("cut_part" args "iron_sheet22"		"iron_sheet22a" )
			("cut_part" args "iron_sheet23"		"iron_sheet23" )
			("cut_part" args "iron_sheet24"		"iron_sheet24" )
			("cut_part" args "iron_sheet25"		"iron_sheet25" )
			("cut_part" args "iron_sheet26"		"iron_sheet26" )
			("cut_part" args "iron_sheet27"		"iron_sheet27" )
			("cut_part" args "iron_sheet28"		"iron_sheet28" )
			("cut_part" args "iron_sheet29"		"iron_sheet29" )
			("cut_part" args "iron_sheet30"		"iron_sheet30" )
			("cut_part" args "iron_sheet31"		"iron_sheet31" )
		else min_energy 4
			(define "cut_part"
				{if volume %1
					{ani_play %1 1}
					{if rand %2
						{delay 0
							{tear "piece_small_steel" bone %0
								{spawn "metal_hit_sl" %0}
								{impulse up 2 1 dir 2 1 no_position}
							}
						}
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "wire"
						{spawn "metal_hit_wire" %0}
					}
				}
			)	
			("cut_part" args "wire"			"wire"			0.9)
			("cut_part" args "plank00"		"plank00"			0.85)
			("cut_part" args "plank01"		"plank01"			0.85)
			("cut_part" args "plank02"		"plank02"			0.85)
			("cut_part" args "plank03"		"plank03"			0.85)
			("cut_part" args "plank04"		"plank04"			0.85)
			("cut_part" args "plank05"		"plank05"			0.85)
			("cut_part" args "plank06"		"plank06"			0.85)
			("cut_part" args "plank07"		"plank07"			0.85)
			("cut_part" args "steel00"		"steel00"			0.85)
			("cut_part" args "steel01"		"steel01"			0.85)
			("cut_part" args "steel02"		"steel02"			0.85)
			("cut_part" args "steel03"		"steel03"			0.85)
			("cut_part" args "steel04"		"steel04"			0.85)
			("cut_part" args "steel05"		"steel05"			0.85)
			("cut_part" args "steel06"		"steel06"			0.85)
			("cut_part" args "steel07"		"steel07"			0.85)
			("cut_part" args "steel08"		"steel08"			0.85)
			("cut_part" args "steel09"		"steel09"			0.85)
			("cut_part" args "steel10"		"steel10"			0.85)
			("cut_part" args "steel11"		"steel11"			0.85)
			("cut_part" args "steel12"		"steel12"			0.85)
			("cut_part" args "steel13"		"steel13"			0.85)
			("cut_part" args "steel14"		"steel14"			0.85)
			("cut_part" args "steel15"		"steel15"			0.85)
			("cut_part" args "steel16"		"steel16"			0.85)
			("cut_part" args "steel17"		"steel17"			0.85)
			("cut_part" args "steel18"		"steel18"			0.85)
			("cut_part" args "steel19"		"steel19"			0.85)
			("cut_part" args "steel20"		"steel20"			0.85)
			("cut_part" args "steel21"		"steel21"			0.85)
			("cut_part" args "steel22"		"steel22"			0.85)
			("cut_part" args "steel23"		"steel23"			0.85)
			("cut_part" args "steel24"		"steel24"			0.85)
			("cut_part" args "steel25"		"steel25"			0.85)
			("cut_part" args "steel26"		"steel26"			0.85)
			("cut_part" args "steel27"		"steel27"			0.85)
			("cut_part" args "steel28"		"steel28"			0.85)
			("cut_part" args "steel29"		"steel29"			0.85)
			("cut_part" args "steel30"		"steel30"			0.85)
			("cut_part" args "steel31"		"steel31"			0.85)
			("cut_part" args "steel32"		"steel32"			0.85)
			("cut_part" args "steel33"		"steel33"			0.85)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.74)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.74)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.74)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.74)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.74)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.74)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.74)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.74)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.74)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.74)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.74)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.74)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.74)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.74)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.74)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.74)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.74)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.74)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.74)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.74)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.74)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.74)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.74)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.74)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.74)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.74)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.74)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.74)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.74)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.74)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.74)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.74)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.7)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.74)
		else min_energy 1.5
			(define "cut_part"
				{if volume %1
					{ani_play %1 1}
					{if rand %2
						{delay 0.1
							{tear "piece_small_steel" bone %0
								{spawn "metal_hit_sl" %0}
								{impulse up 0.5 0.4 dir 2 1 }
							}
						}
					else volume "lamp"
						{view stop "lamp_light_spot1"}
						{view hide "lamp_light_spot1"}
						{view stop "lamp_light_spot2"}
						{view hide "lamp_light_spot2"}
					else volume "wire"
						{spawn "metal_hit_wire" %0}
					}
				}
			)	
			("cut_part" args "wire"			"wire"			0.2)
			("cut_part" args "plank00"		"plank00"			0.05)
			("cut_part" args "plank01"		"plank01"			0.05)
			("cut_part" args "plank02"		"plank02"			0.05)
			("cut_part" args "plank03"		"plank03"			0.05)
			("cut_part" args "plank04"		"plank04"			0.05)
			("cut_part" args "plank05"		"plank05"			0.05)
			("cut_part" args "plank06"		"plank06"			0.05)
			("cut_part" args "plank07"		"plank07"			0.05)
			("cut_part" args "steel00"		"steel00"			0.2)
			("cut_part" args "steel01"		"steel01"			0.2)
			("cut_part" args "steel02"		"steel02"			0.2)
			("cut_part" args "steel03"		"steel03"			0.2)
			("cut_part" args "steel04"		"steel04"			0.2)
			("cut_part" args "steel05"		"steel05"			0.2)
			("cut_part" args "steel06"		"steel06"			0.2)
			("cut_part" args "steel07"		"steel07"			0.2)
			("cut_part" args "steel08"		"steel08"			0.2)
			("cut_part" args "steel09"		"steel09"			0.2)
			("cut_part" args "steel10"		"steel10"			0.2)
			("cut_part" args "steel11"		"steel11"			0.2)
			("cut_part" args "steel12"		"steel12"			0.2)
			("cut_part" args "steel13"		"steel13"			0.2)
			("cut_part" args "steel14"		"steel14"			0.2)
			("cut_part" args "steel15"		"steel15"			0.2)
			("cut_part" args "steel16"		"steel16"			0.2)
			("cut_part" args "steel17"		"steel17"			0.2)
			("cut_part" args "steel18"		"steel18"			0.2)
			("cut_part" args "steel19"		"steel19"			0.35)
			("cut_part" args "steel20"		"steel20"			0.35)
			("cut_part" args "steel21"		"steel21"			0.35)
			("cut_part" args "steel22"		"steel22"			0.35)
			("cut_part" args "steel23"		"steel23"			0.35)
			("cut_part" args "steel24"		"steel24"			0.35)
			("cut_part" args "steel25"		"steel25"			0.35)
			("cut_part" args "steel26"		"steel26"			0.35)
			("cut_part" args "steel27"		"steel27"			0.35)
			("cut_part" args "steel28"		"steel28"			0.35)
			("cut_part" args "steel29"		"steel29"			0.35)
			("cut_part" args "steel30"		"steel30"			0.35)
			("cut_part" args "steel31"		"steel31"			0.35)
			("cut_part" args "steel32"		"steel32"			0.35)
			("cut_part" args "steel33"		"steel33"			0.35)
			("cut_part" args "iron_sheet00"		"iron_sheet00"			0.3)
			("cut_part" args "iron_sheet01"		"iron_sheet01"			0.3)
			("cut_part" args "iron_sheet02"		"iron_sheet02"			0.3)
			("cut_part" args "iron_sheet03"		"iron_sheet03"			0.3)
			("cut_part" args "iron_sheet04"		"iron_sheet04"			0.3)
			("cut_part" args "iron_sheet05"		"iron_sheet05"			0.3)
			("cut_part" args "iron_sheet06"		"iron_sheet06"			0.3)
			("cut_part" args "iron_sheet07"		"iron_sheet07"			0.3)
			("cut_part" args "iron_sheet08"		"iron_sheet08"			0.3)
			("cut_part" args "iron_sheet09"		"iron_sheet09"			0.3)
			("cut_part" args "iron_sheet10"		"iron_sheet10"			0.3)
			("cut_part" args "iron_sheet11"		"iron_sheet11"			0.3)
			("cut_part" args "iron_sheet12"		"iron_sheet12"			0.3)
			("cut_part" args "iron_sheet13"		"iron_sheet13"			0.3)
			("cut_part" args "iron_sheet14"		"iron_sheet14"			0.3)
			("cut_part" args "iron_sheet15"		"iron_sheet15"			0.3)
			("cut_part" args "iron_sheet16"		"iron_sheet16"			0.3)
			("cut_part" args "iron_sheet17"		"iron_sheet17"			0.3)
			("cut_part" args "iron_sheet18"		"iron_sheet18"			0.3)
			("cut_part" args "iron_sheet19"		"iron_sheet19"			0.3)
			("cut_part" args "iron_sheet20"		"iron_sheet20"			0.3)
			("cut_part" args "iron_sheet21"		"iron_sheet21"			0.3)
			("cut_part" args "iron_sheet21"		"iron_sheet21a"			0.3)
			("cut_part" args "iron_sheet22"		"iron_sheet22"			0.3)
			("cut_part" args "iron_sheet22"		"iron_sheet22a"			0.3)
			("cut_part" args "iron_sheet23"		"iron_sheet23"			0.3)
			("cut_part" args "iron_sheet24"		"iron_sheet24"			0.3)
			("cut_part" args "iron_sheet25"		"iron_sheet25"			0.3)
			("cut_part" args "iron_sheet26"		"iron_sheet26"			0.3)
			("cut_part" args "iron_sheet27"		"iron_sheet27"			0.3)
			("cut_part" args "iron_sheet28"		"iron_sheet28"			0.3)
			("cut_part" args "iron_sheet29"		"iron_sheet29"			0.3)
			("cut_part" args "iron_sheet30"		"iron_sheet30"			0.3)
			("cut_part" args "iron_sheet31"		"iron_sheet31"			0.3)
		}
	}
	{on bullet_hit
		{if stuff "bullet"
			{if volume "glass"
				{volume disable bullet contact blast}
				{spawn "glass_hit_small" volume x}
				{delay_ex 0.1 uniq
					{bone cut}
				}
			}
			{ani_play "hit" 1}
		}
	}
	{on "end_stage"
		{if "end_stage"
			(define "cut_part"
				{if rand %1
					{ani_play %0 1}
					{delay 0
						{tear "piece_small_steel" bone %0
							{impulse up 1 dir 1 }
						}
					}
				}
			)	
			("cut_part" args "steel00"				0.0001)
			("cut_part" args "steel01"				0.0001)
			("cut_part" args "steel02"				0.0001)
			("cut_part" args "steel03"				0.0001)
			("cut_part" args "steel04"				0.0001)
			("cut_part" args "steel05"				0.0001)
			("cut_part" args "steel06"				0.0001)
			("cut_part" args "steel07"				0.0001)
			("cut_part" args "steel08"				0.0001)
			("cut_part" args "steel09"				0.0001)
			("cut_part" args "steel10"				0.0001)
			("cut_part" args "steel11"				0.0001)
			("cut_part" args "steel12"				0.0001)
			("cut_part" args "steel13"				0.0001)
			("cut_part" args "steel14"				0.0001)
			("cut_part" args "steel15"				0.0001)
			("cut_part" args "steel16"				0.0001)
			("cut_part" args "steel17"				0.0001)
			("cut_part" args "steel18"				0.0001)
			("cut_part" args "steel19"				0.0001)
			("cut_part" args "steel20"				0.0001)
			("cut_part" args "steel21"				0.0001)
			("cut_part" args "steel22"				0.0001)
			("cut_part" args "steel23"				0.0001)
			("cut_part" args "steel24"				0.0001)
			("cut_part" args "steel25"				0.0001)
			("cut_part" args "steel26"				0.0001)
			("cut_part" args "steel27"				0.0001)
			("cut_part" args "steel28"				0.0001)
			("cut_part" args "steel29"				0.0001)
			("cut_part" args "steel30"				0.0001)
			("cut_part" args "steel31"				0.0001)
		}
	}
}

{"damaged"
	{inflammation_time 5}
	{on "crush_container"
		{impulse dir 2 1 up 2 1 dir 7 2 cx 0 0.5 cy 0 0.5}
	}
	{on "drop_item"
		{impulse dir 2 1 cx 0 1 cy 0 1}
	}
	{on contact
		{if effector "fraction_small" ;дробь
			{if contact_velocity 2
				(define "cut_part"
					{if rand %2
						{if volume %1
							{tear "piece_large_steel" bone %0
								{impulse up 4 1 dir 2 1}
							}
						}
					}
				)	
				("cut_part" args "hand"	 		"hand"			0.3)
				("cut_part" args "plank00"		"parts00"		0.3)
				("cut_part" args "plank01"		"parts01"		0.3)
				("cut_part" args "plank02"		"parts01"		0.8)
				("cut_part" args "plank03"		"parts01"		0.8)
				("cut_part" args "plank04"		"parts01"		0.8)
				("cut_part" args "plank05"		"parts01"		0.8)
				("cut_part" args "roof"			"roof"			0.3)
				("cut_part" args "firstaid"		"body"			0.2)
			}
		else effector "vehicle" 
			{if contact_velocity 2
				(define "cut_part"
					{if rand %2
						{if volume %1
							{tear "piece_large_steel" bone %0
								{impulse up 4 1 dir 2 1}
							}
						}
					}
				)	
				("cut_part" args "hand"	 		"hand"			0.3)
				("cut_part" args "plank00"		"parts00"		0.3)
				("cut_part" args "plank01"		"parts01"		0.3)
				("cut_part" args "plank02"		"parts01"		0.8)
				("cut_part" args "plank03"		"parts01"		0.8)
				("cut_part" args "plank04"		"parts01"		0.8)
				("cut_part" args "plank05"		"parts01"		0.8)
				("cut_part" args "roof"			"roof"			0.3)
				("cut_part" args "firstaid"		"body"			0.2)
			}
		}
	}
	{on blast_hit
		(define "cut_part"
			{if rand %2
				{if volume %1
					{tear "piece_large_steel" bone %0
						{impulse up 4 1 dir 2 1}
					}
				}
			}
		)	
		("cut_part" args "hand"	 		"hand"			0.8)
		("cut_part" args "plank00"		"parts00"		0.8)
		("cut_part" args "plank01"		"parts01"		0.8)
		("cut_part" args "plank02"		"parts01"		0.8)
		("cut_part" args "plank03"		"parts01"		0.8)
		("cut_part" args "plank04"		"parts01"		0.8)
		("cut_part" args "plank05"		"parts01"		0.8)
		("cut_part" args "roof"			"roof"			0.8)
		("cut_part" args "firstaid"			"body"			0.7)
	}
	{on bullet_hit
		{if stuff "bullet"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_large_steel" bone %0
							{impulse up 2 1 dir 2 1}
						}
					}
				}
			)	
			("cut_part" args "hand"	 		"hand"			0.4)
			("cut_part" args "plank00"		"parts00"		0.4)
			("cut_part" args "plank01"		"parts01"		0.4)
			("cut_part" args "plank02"		"plank02"		0.8)
			("cut_part" args "plank03"		"plank03"		0.8)
			("cut_part" args "plank04"		"plank04"		0.8)
			("cut_part" args "plank05"		"plank05"		0.8)
			("cut_part" args "roof"			"roof"			0.4)
			("cut_part" args "firstaid"		"body"			0.1)
		else stuff "zenite"
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_large_steel" bone %0
							{impulse up 2 1 dir 2 1}
						}
					}
				}
			)	
			("cut_part" args "hand"	 		"hand"			0.8)
			("cut_part" args "plank00"		"parts00"		0.8)
			("cut_part" args "plank01"		"parts01"		0.8)
			("cut_part" args "plank02"		"plank02"		0.9)
			("cut_part" args "plank03"		"plank03"		0.9)
			("cut_part" args "plank04"		"plank04"		0.9)
			("cut_part" args "plank05"		"plank05"		0.9)
			("cut_part" args "roof"			"roof"			0.6)
			("cut_part" args "firstaid"		"body"			0.1)
		else stuff "fg"
			{bullet_detonate}		
			(define "cut_part"
				{if rand %2
					{if volume %1
						{tear "piece_large_steel" bone %0
							{impulse up 2 1 dir 2 1}
						}
					}
				}
			)	
			("cut_part" args "hand"	 		"hand"			0.7)
			("cut_part" args "plank00"		"parts00"		0.7)
			("cut_part" args "plank01"		"parts01"		0.7)
			("cut_part" args "plank02"		"plank02"		0.9)
			("cut_part" args "plank03"		"plank03"		0.9)
			("cut_part" args "plank04"		"plank04"		0.9)
			("cut_part" args "plank05"		"plank05"		0.9)
			("cut_part" args "roof"			"roof"			0.6)
			("cut_part" args "firstaid"		"body"			0.1)
		}
	}
}



{"wooden_walls"
	{inflammation_time 10}
	{on spawn
		{link_sound 	"start_small" 			"fire/start_small/emt_fire_med_fuel_01"}
		{link_sound 	"flame_small"			"fire/small_stuff/fire_small"}		
	}
	{on "burn_volume"
		{call "fire_sound"}
		{delay 40
			{stop_sound "flame_small" }	
		}
		;{if not "burned"
			;{set "burned" 1}
		(define "cut_subpiece_wood"
			{if volume "wood_%0"
				{if not tagged "burned_wood_%0"
					{tags add "burned_wood_%0"}
					{burn volume "wood_%0" fx "smoke_wood_small" time 20 fake even_law}	
					{delay 10 3
						{burn volume "wood_%0" fx "smoke_wood_small_fire" time 90 fake even_law}	
						{fire volume "wood_%0" radius 0.1 heating 2  time 60 follow}
						{delay 80 20							
							{tear "piece_small_wood_burn" bone "wood_plank_down_%0"
								{volumes disable contact }	
								{tex_morph "burned" 10}
								{fire radius 0.1 heating 2  time 15 follow}
								{burn volume "wood_%0" fx "smoke_wood_small_fire" time 20 fake even_law}	
								{impulse forward 0.1}
								{start_sound "fire/crush_wood/"}
							}
						}
					}
				}
			}
		)
		("cut_subpieces_wood")
		;}
	}
	{on "fire_sound"
		{if not tagged "burned_sound"
			{tags add "burned_sound"}
			;{play_sound "start_small"}
			{play_sound "flame_small" 1}	
			{delay 20
				{tags remove "burned_sound"}
			}
		}
	}
	{on pierce
		(define "bullet_hit"
			{if stuff %stuff
				{if rand %rand
					{if volume "wood"
						{start_sound "crush/medium/wood/"}
						{tear "piece_medium_wood_crushed" bone from_volume
							{tags add "crush"}
							;{burn volume fx "tree_fall" time 0.5 fake even_law}
							%impact
						}
					}
				}
			}
		)
		;                  stuff   		   
		("bullet_hit" stuff("shell")			rand(1) 		impact({impulse dir 7 4		cx 4 2 cy 4 2  	no_position}))
		("bullet_hit" stuff("heavy_zenite")		rand(0.6) 		impact({impulse dir 8 4 	cx 7 3 cy 7 3  	no_position}))
		("bullet_hit" stuff("zenite")			rand(0.3) 		impact({impulse dir 4 2 	cx 4 1 cy 4 1 	no_position}))
		("bullet_hit" stuff("bullet big")		rand(0.3) 		impact({impulse dir 2 1 	cx 2 1 cy 2 1 	no_position}))
		("bullet_hit" stuff("bullet normal")	rand(0.1) 		impact({impulse dir 1 0.5 	cx 0.5 cy 0.5  	no_position}))
		("bullet_hit" stuff("bullet small")		rand(0.01) 		impact({impulse dir 0.5 	cx 0.5 cy 0.5  	no_position}))
	}
	{on contact 		
		{if effector "car"
			{if contact_velocity 25
				(define "cut_subpiece_wood"
					{if rand 0.01
						{tear "piece_small_wood" bone "wood_plank_down_%0"
							{impulse forward 0.5 0.2 cx 2 1 cy 2 1 }
						}
					}
				)
				("cut_subpieces_wood")
			}
		}
		{if not effector "obstacle"	
			(define "contact_hit"
				{if effector %0
					{if contact_velocity 10
						{if volume "wood"
							{if rand %1
								{start_sound "crush/medium/wood/"}
								{tear "piece_small_wood" bone from_volume
									{impulse dir 1.5 0.7 cx 2 1 cy 2 1 rnd_dir 2 no_position}
								}
							}
						}
					}
				}
			)
			;                  ------   первичный вторичный финальный
			("contact_hit" args "fraction"	0.2 )
			("contact_hit" args "vehicle"	1 )
		}
	}
	{on blast
		{if stuff "damage_overlap"
			{tear "piece_small_wood" bone from_volume
				{impulse up 0.5 0.2  	dir 8 4		cx 4 2 cy 4 2  	no_position}
			}
		else
			(define "blast_hit"
				{if min_energy %blast
					{if rand %shard
						{start_sound "crush/medium/wood/"}
						{burn volume fx "tree_fall" time 0.5 fake even_law}
						{tear "piece_small_wood" bone from_volume
							%impact
						}
					}
				}
			)
			;                  ------   первичный вторичный финальный
			("blast_hit" blast(4)  shard(1) impact({impulse up 0.5 0.2  	dir 8 4		cx 4 2 cy 4 2  	no_position}))
			("blast_hit" blast(2)  shard(1) impact({impulse up 0.5 0.2 		dir 4 2		cx 2 1 cy 2 1  	no_position}))
		}
	}
}
